### ISSUE TITLE
Cluster mode: Client will not send `READONLY` command when reconnecting to replicas

### ISSUE THREAD

**Issue by johnduhart** [redis/redis-rb#1017]
After switching our application to use a cluster-mode redis setup, we discovered that (nearly) all reads to replicas were being redirected to the primary instance. Our application is an API, running in puma with multiple workers (ie. multiple forked processes).

After reviewing the library code, our current theory is that after forking the connection is forced to be re-established because of the process ID change ([code](https://github.com/redis/redis-rb/blob/01768dab789c7f819fbbcdcec85802cbbcc83d5d/lib/redis/client.rb#L394-L399)). However, because the `READONLY` command is only sent [when the client is initially created](https://github.com/redis/redis-rb/blob/01768dab789c7f819fbbcdcec85802cbbcc83d5d/lib/redis/cluster/node.rb#L80), the new connection is not in the correct state to allow for read only commands.

A potential fix for this would be to introduce a new [`Connector` implementation](https://github.com/redis/redis-rb/blob/01768dab789c7f819fbbcdcec85802cbbcc83d5d/lib/redis/client.rb#L541) for cluster mode clients that sends the `READONLY` command after connection.

**Comment by byroot** [comment]
> the `READONLY` command is only sent [when the client is initially created](https://github.com/redis/redis-rb/blob/01768dab789c7f819fbbcdcec85802cbbcc83d5d/lib/redis/cluster/node.rb#L80)

That's a bug indeed. That `READONLY` should be moved inside the client, and re-issued on reconnect.

**Comment by byroot** [comment]
@johnduhart I pushed https://github.com/redis/redis-rb/commit/ae807083c2e4737bece306cbc403f845a1a5962a, could you test the master branch just to make sure I haven't overlooked anything.

If that fix your issue as expected I can cut a release.

**Comment by johnduhart** [comment]
I'll try to get this deployed into a testing environment today and report back.

**Comment by johnduhart** [comment]
@byroot I deployed with ae80708 and everything looks good, no more `MOVED` errors reported by our telemetry and the number of reads on the primary instance is near-zero.
