### ISSUE TITLE
`CrossSlotPipeliningError` validation seems incorrect?

### ISSUE THREAD

**Issue by ejinotti-mdsol** [redis/redis-rb#1019]
From my reading of https://redis.io/topics/cluster-spec#keys-hash-tags it seems that the magic squiggly brackets to force a specific value for hashing should be acceptable anywhere in the key.  However the raise of `CrossSlotPipeliningError` here:

https://github.com/redis/redis-rb/blob/6542934f01b9c390ee450bd372209a04bc3a239b/lib/redis/cluster.rb#L82

Seems to only accept the magic squigglies as a prefix:

```
irb(main):001:0> REDIS.pipelined { ['{zed}one', '{zed}two'].each { |k| REDIS.exists?(k) } }
=> [false, false]
irb(main):002:0> REDIS.pipelined { ['one{zed}', 'two{zed}'].each { |k| REDIS.exists?(k) } }
Traceback (most recent call last):
        1: from (irb):2
Redis::Cluster::CrossSlotPipeliningError (Cluster client couldn't send pipelining to single node. The commands include cross slot keys. ["zed", "zed"])
irb(main):003:0> REDIS.pipelined { ['one{zed}one', 'two{zed}one'].each { |k| REDIS.exists?(k) } }
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):3:in `rescue in irb_binding'
Redis::Cluster::CrossSlotPipeliningError (Cluster client couldn't send pipelining to single node. The commands include cross slot keys. ["zed", "zed"])
```

This is v4.3.1

**Comment by ejinotti-mdsol** [comment]
One additional piece of info: this was using a cluster with one shard and 5 replicas.

**Comment by johnduhart** [comment]
I had a brief look at this for the team, and I'm a bit suspicious of this code path:

https://github.com/redis/redis-rb/blob/baf57060a8dfca433fc840eedcd85c786fdd2101/lib/redis/cluster.rb#L290

This is going to call `find_node_key` for each command individually, which results in looking up a slot (okay), and then  calling `find_node_key_of_slave`. And then, here:

https://github.com/redis/redis-rb/blob/baf57060a8dfca433fc840eedcd85c786fdd2101/lib/redis/cluster/slot.rb#L25-L30

A random replica will be chosen, which may result in different `node_keys` even though all keys are in the same slot.

**Comment by supercaracal** [comment]
It is a bug. It seems that the cross-slot validation should be skipped when commands in pipeline are sent to replicas.

**Comment by supercaracal** [comment]
Actually, forget about that. The cross-slot validation in pipelining should be geared toward primary nodes.
