### ISSUE TITLE
DB index unintentionally copied over from REDIS_URL env var

### ISSUE THREAD

**Issue by danhsiung** [redis/redis-rb#1043]
v4.1.4 include a fix for [888](https://github.com/redis/redis-rb/issues/888), but introduced an issue for me.  In my environment, I have `REDIS_URL=redis://HOSTNAME:6379/5` which is used for most of my interactions with Redis.  However, in one code path I'm connecting to a separate Redis Cluster like this:
`client = Redis.new({ cluster: "redis://DIFFERENT_HOSTNAME:6379", password: "PASSWORD" })`

If I don't specify `db: 0` in the initializer, or add a `/0` to the end of the cluster string, my new client connects to DB index of `5`, which is inadvertently copied over from the `REDIS_URL` config.

This is likely an uncommon case, and I'm not even sure there is an adequate heuristic that works well, but I figured I'd reach out and see if anyone has an idea on this.  Happy to write up a patch if there's a good approach.

**Comment by supercaracal** [comment]
Since Redis cluster only uses `0` db, it might be that the following code should be hard-coded zero.

https://github.com/redis/redis-rb/blob/b373362eba86fcef75571af2a2accffc8cee8b78/lib/redis/cluster/option.rb#L66-L68

**Comment by danhsiung** [comment]
That could work for `db`, but I'm wondering if there could be cases where other parameters could also be copied over inadvertently.  E.g. `username`.  I believe that is usually left blank, but what if the `REDIS_URL` config specifies one?

**Comment by supercaracal** [comment]
`REDIS_URL` environment variable is used indeed when it specified.

https://github.com/redis/redis-rb/blob/b373362eba86fcef75571af2a2accffc8cee8b78/lib/redis/client.rb#L454-L477

Common options are legitimate even if we specified cluster option. They are able to be overwritten with cluster option. It might be a bug when we cannot overwrite it with empty value.

**Comment by byroot** [comment]
This is solved in 5.0
