### ISSUE TITLE
Big integer issue

### ISSUE THREAD

**Issue by adrianomic** [redis/redis-rb#1050]
There's a big issue with redis. I am using this in ruby script
```
irb(main):026:0> redis.zrangebyscore('feed:home:7', '(-inf', '(+inf', with_scores: true)
=> [["107241582127494388", 1.0724224662752986e+17]]
irb(main):027:0> tid = redis.zrangebyscore('feed:home:7', '(-inf', '(+inf', with_scores: true)[0][1]
=> 1.0724224662752986e+17
irb(main):028:0> redis.zscore('feed:home:7', tid)
=> nil
irb(main):029:0> redis.zadd('feed:home:7', 107241582127494388, 107241582127494388)
=> false
irb(main):031:0> redis.zadd('feed:home:7', 107241582127494389, 107241582127494389)
=> true
irb(main):032:0> redis.zscore('feed:home:7', 107241582127494389)
=> 1.0724158212749438e+17
irb(main):033:0> redis.zscore('feed:home:7', 107241582127494380)
=> nil
irb(main):034:0> redis.zscore('feed:home:7', 107241582127494388)
=> 1.0724158212749438e+17
irb(main):035:0> redis.zscore('"feed:home:7', 107241582127494388)
=> nil
irb(main):036:0> redis.ztrm('feed:home:7', 107241582127494389)
Traceback (most recent call last):
        1: from (irb):36
Redis::CommandError (ERR unknown command `ztrm`, with args beginning with: `feed:home:7`, `107241582127494389`, )
irb(main):037:0> redis.zrem('feed:home:7', 107241582127494389)
=> true
irb(main):038:0> redis.zscore('feed:home:7', 107241582127494388)
=> 1.0724158212749438e+17
irb(main):039:0> tid = redis.zrevrangebyscore('feed:home:7', '(+inf', '(107241582127494388', limit: [0, 20], with_scores: true)
=> []
irb(main):040:0> tid = redis.zrevrangebyscore('feed:home:7', '(+inf', '(-inf', limit: [0, 20], with_scores: true)
=> [["107241582127494388", 1.0724158212749438e+17]]
```

These are logs from rails console. And There was typo '"feed:home:7'
I am putting full logs to help you track issue.
I don't think my script changed 107241582127494388. But the key is actually changed.

**Comment by byroot** [comment]
I'm sorry but I can't make sense of your issue discussion, please try to go to the point.

**Comment by adrianomic** [comment]
@byroot Please check first and last result
Those 2 commands should output same result. Can you please check if any script changed redis value?

**Comment by byroot** [comment]
I don't mind helping people dig into bugs once in a while, but this is the most disrespectful bug report I've ever seen. If you want help you must first properly explain the context, you can't just copy paste a console session like this.

**Comment by adrianomic** [comment]
```ruby
irb(main):026:0> redis.zrangebyscore('feed:home:7', '(-inf', '(+inf', with_scores: true)
=> [["107241582127494388", 1.0724224662752986e+17]]
irb(main):040:0> redis.zrevrangebyscore('feed:home:7', '(+inf', '(-inf', limit: [0, 20], with_scores: true)
=> [["107241582127494388", 1.0724158212749438e+17]]
```
Those 2 commands should put same result. But they're not. I've run some scripts between those values and I don't think they've updated that value
This is the issue. So I thought redis has issue with handling big integer
Do you need more details?

**Comment by byroot** [comment]
> Do you need more details?

**I** don't need anything, but if you need people to help you, you have to understand that we can't read your mind, not the current state of your Redis server.

So if you want me to look at this issue, please start by providing a reproductible script, something that starts from an empty redis server, and demonstrate the issue you have.
