### ISSUE TITLE
Extend expire command to allow for options like NX, XX, GT, LT

### ISSUE THREAD

**Issue by mbykovskyy** [redis/redis-rb#1062]
At the moment there's no way to pass expiry options to EXPIRE command via the interface. I would like to be able to do the following:

```
redis.sadd("key", "value")
redis.expire("key", 5, nx: true)
```

**Comment by byroot** [comment]
It's a `redis 7.0` feature, PR welcome, however 7.0 is still a release candidate, so would need to be integrated in the CI etc.

In the meantime you can do `redis.call("EXPIRE", key, "NX")`.

**Comment by fatkodima** [comment]
@byroot This issue can be closed - https://github.com/redis/redis-rb/pull/1090.
