### ISSUE TITLE
Minimum Redis version for gem versions

### ISSUE THREAD

**Issue by kamur** [redis/redis-rb#1085]
I have many project with a different version of redis gem and I need to know which is the minimum version of it for each version. How can I do it?

The gem versions I need to know the minimum redis version are these:
2.2.2
3.1.0
3.2.0
3.3.0
3.3.3
3.3.5
4.0.1
4.1.0
4.1.1

**Comment by byroot** [comment]
You can get this information on Rubygems, e.g. https://rubygems.org/gems/redis/versions/4.0.1 tells you:

```
REQUIRED RUBY VERSION:
>= 2.2.2
```

**Comment by kamur** [comment]
I need to know the minimum Redis version and not the Ruby version

**Comment by byroot** [comment]
I don't think there ever was a minimum redis version.
