### ISSUE TITLE
Redis in RoR using ActiveRecord

### ISSUE THREAD

**Issue by marikaner** [redis/redis-rb#1099]
I am a total newbie to Ruby, Ruby on Rails and Redis. I would like to exchange the default sqlite database through redis in my application. I have a basic understanding how to connect to redis from my app, but I don't understand how I can configure RoR to use Redis with ActiveRecord. Do you have any examples or resources you could point me to?

**Comment by byroot** [comment]
That's not possible. Redis is a Key/Value store, Active Record is an Object Relational Mapper for SQL databases.

`Ohm`, may be somewhat close to what you are looking for: https://github.com/soveran/ohm.

Good luck, but please don't open issues on bug trackers for this kind of questions.
