### ISSUE TITLE
Support for Reader endpoint in AWS Elasticache cluster mode disabled?

### ISSUE THREAD

**Issue by waitstime** [redis/redis-rb#1110]
Is there support for cluster mode disabled read replicas similar to the setup of [Elasticache's cluster mode disabled](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Replication.Redis-RedisCluster.html)?

In another language Redis driver we were able to accomplish this by manually setting up one ClusterSlot with a master and read replica node address which didn't use cluster mode or Redis sentinel. I see that in redis-rb there is a ClusterSlot class but I can't figure out how to configure that with the Cluster so that it is in cluster mode disabled(sorry ruby noob).

**Comment by supercaracal** [comment]
You can specify a reader endpoint like this:

```ruby
r = Redis.new(url: 'rediss://your-reader-endpoint', reconnect_attempts: 10, reconnect_delay: 1.5, reconnect_delay_max: 10.0)

r.get('foo')
```

https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticache-launches-reader-endpoint-for-redis/

**Comment by supercaracal** [comment]
There is only the latter way unless using sentinel or cluster mode.

```ruby
w = Redis.new(url: 'redis://your-primary-endpoint')
r = Redis.new(url: 'redis://your-reader-endpoint')

w.set('foo', 1)
r.get('foo')
```

**Comment by waitstime** [comment]
Thanks for the info! Closing this.

**Comment by dominicfollett** [comment]
Apologies for commenting on this closed ticket. But I'd like to ask for clarification.

I have an AWS Elasticache (cluster mode disabled) replication group with a write primary endpoint, and a readonly endpoint. In my scenario I am configuring Rails' cache store:

```
  config.cache_store = :redis_cache_store, {
    url: [
      ENV['REDIS_WRITE_HOST'],
      ENV['REDIS_READ_HOST'],
    ],
    ...
```

As it stands, I think I might run into problems with write operations being made on the readonly endpoint. You mention above that using cluster mode is a potential option. How would I leverage redis-clustering with ActiveSupport::Cache for my use-case? Thank you.

**Comment by supercaracal** [comment]
```ruby
config.cache_store = :redis_cache_store, { cluster: "ENV['ELASTICACHE_ENDPOINT_URL']", replica: true }
```

The above setting might work for you if you use the redis gem version `4.*` or earlier. Also, Redis cluster (cluster mode is enabled in ElastiCache) has some constraints because it does sharding. If bulk processing commands such as 'MSET', 'MGET', pipelining, and transaction features are used in `redis_cache_store` internally, some errors may occur. And clients need consideration of the replication delay. Sorry, I'm not familiar with `redis_cache_store` codes.
