### ISSUE TITLE
`zrange` with `rev: true` fails with Redis::CommandError

### ISSUE THREAD

**Issue by nikita8** [redis/redis-rb#1147]
Passing `rev` option as `true` to `zrange`, fails with `ERR syntax error (Redis::CommandError)`. It fails for both 4.8.0 and latest 5.0.2 version as seen in the screenshots below.

![image](https://user-images.githubusercontent.com/2724290/188221603-785225e2-def6-4bfc-8a3a-5c5996af751b.png)

![image](https://user-images.githubusercontent.com/2724290/188221397-08c9ae9c-7dc4-4b98-8e22-8c4d094b4aa3.png)

**Comment by byroot** [comment]
Quick tip, it's always best to submit snippets and such as text rather than images. Images are hard to work with, I can't copy paste them, etc.

As for your issues, It works fine, `REV` was added in Redis server 6.2.0, I assume your server is too old.
