### ISSUE TITLE
Redis::CannotConnectError: RedisClient::ReadTimeoutError

### ISSUE THREAD

**Issue by dominicfollett** [redis/redis-rb#1152]
I have a single node (cluster mode disabled) AWS Elasticache for Redis Cluster, with at-rest and in-transit encryption enabled. Redis Engine version 6.2.6.

I am able to run the following commands **successfully** from my Rails server (running on Fargate, in the same VPC as the elasticache for redis cluster):

```
curl -v telnet://master.staging-redis-cluster-replication-group.figuyt.usw2.cache.amazonaws.com:6379
```
and

```
openssl s_client -connect master.staging-redis-cluster-replication-group.figuyt.usw2.cache.amazonaws.com:6379
```
 

However, in a rails console on the same server, I am unable to connect to Redis:

```
redis = Redis.new(url: "redis://:urlencodedpassword@master.staging-redis-cluster-replication-group.figuyt.usw2.cache.amazonaws.com:6379/0", ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE})
```

Attempting to write or read results in:

```
Redis::CannotConnectError: RedisClient::ReadTimeoutError
from /usr/local/bundle/gems/redis-client-0.8.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer'
Caused by RedisClient::CannotConnectError: RedisClient::ReadTimeoutError
from /usr/local/bundle/gems/redis-client-0.8.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer'
Caused by RedisClient::ReadTimeoutError: RedisClient::ReadTimeoutError
from /usr/local/bundle/gems/redis-client-0.8.0/lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer'
```

**Comment by casperisfine** [comment]
Was it working with the 4.x branch and started failing when you upgraded, or is this a new app?

Also could you include a longer backtrace please? It would be helpful to know wether it's failing on the authentication prelude or later.

**Comment by dominicfollett** [comment]
Thank you for your response @casperisfine. I am using the latest branch 5.x. I have not tried 4.x but will do so today.
The trace I included above is the only trace I get. I'm not sure how to get a longer backtrace?

**Comment by dominicfollett** [comment]
Hi @casperisfine I've tested the same connection with redis 4.8.0, and I get a timeout error:

```
 => #<Redis client v4.8.0 for redis://master.staging-redis-cluster-replication-group.figuyt.usw2.cache.amazonaws.com:6379/0>
2.7.4 :007 > redis.set('test', 'test')
Traceback (most recent call last):
       16: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:139:in `block in connect'
       15: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:161:in `call'
       14: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:268:in `process'
       13: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:356:in `logging'
       12: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:269:in `block in process'
       11: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:420:in `ensure_connected'
       10: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:279:in `block (2 levels) in process'
        9: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:161:in `block in call'
        8: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:310:in `read'
        7: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:299:in `io'
        6: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/client.rb:311:in `block in read'
        5: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/connection/ruby.rb:382:in `read'
        4: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/connection/ruby.rb:47:in `gets'
        3: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/connection/ruby.rb:54:in `_read_from_socket'
        2: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/connection/ruby.rb:54:in `loop'
        1: from /usr/share/rvm/gems/ruby-2.7.4/gems/redis-4.8.0/lib/redis/connection/ruby.rb:58:in `block in _read_from_socket'
Redis::TimeoutError (Connection timed out)
```

**Comment by dominicfollett** [comment]
Hi @casperisfine I did some more testing and have narrowed it down to _encryption-in-transit_. I can connect to an AWS Elasticache for Redis Cluster using redis-rb just fine **if I do not use a password**.

It seems that the gem doesn't appear to work with password protected clusters?

For clarity, my passwords were simple strings, url encoded, and all my other tooling was able to use the same password and connect successfully to the cluster.

**Comment by casperisfine** [comment]
It does work with passwords.

I've seen something similar once but couldn't figure it out. 

When you use a password, the client issues a command right after connecting `AUTH <password>`. What I've seen happen is that when you use both a password and SSL, writing in the connection before the SSL handshake is completed cause the client to timeout.

I'd need to be able to reproduce this consistently to figure it out.

No idea wether it will fix it, but I'd recommend trying to enable the hiredis driver, its connection implementation is entirely different, maybe it handle this better. You can enable it by simply adding `gem "hiredis-client"` in your `Gemfile`.

**Comment by casperisfine** [comment]
Hum, wait, In your example you don't specify that the connections should be SSL in any way:

Can you try:

```ruby
redis = Redis.new(
  url: "redis://:urlencodedpassword@master.staging-redis-cluster-replication-group.figuyt.usw2.cache.amazonaws.com:6379/0",
  ssl: true,
  ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE},
)
```

?

**Comment by dominicfollett** [comment]
Thank you @casperisfine that was what I was missing. Thank you for your help.

**Comment by fernandoaleman** [comment]
> Hum, wait, In your example you don't specify that the connections should be SSL in any way:
> 
> Can you try:
> 
> ```ruby
> redis = Redis.new(
>   url: "redis://:urlencodedpassword@master.staging-redis-cluster-replication-group.figuyt.usw2.cache.amazonaws.com:6379/0",
>   ssl: true,
>   ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE},
> )
> ```
> 
> ?

@casperisfine Hey, just found this and wanted to let you know this solved my issue for me. Thank you 👍
