### ISSUE TITLE
Have any plan of supports RedisSearch?

### ISSUE THREAD

**Issue by roharon** [redis/redis-rb#1154]
I guess redis-rb is not supports RedisSearch in Redis Stack yet, although [redis-py](https://github.com/redis/redis-py/tree/master/redis/commands/search) supports it.

Is there any consideration of supports RedisSearch's command?
Or just not supports because it's just included in RedisStack, not Redis?

If there is no reason and will supports RedisSearch's commands in the future, can I add commands of RedisSearch?

**Comment by byroot** [comment]
I have no plan to support extensions, we're already behind on core commands, and as lined-out in https://github.com/redis/redis-rb/issues/1070, having to keep up with commands signature changes is quite painful.

What I'd be open to would be to make it easy for gems to add extensions commands. Right now it's fairly easy, just not documented.

But basically:


```ruby
module MyRedisExtension
  def some_command(some_args)
    send_command(["COMMAND", some_args]) do |reply|
      reply # do any transformation needed here
    end
  end
end

Redis.include(MyRedisExtension)
```

**Comment by roharon** [comment]
Got it!
I will use that.
