### ISSUE TITLE
Deprecation warnings for 4.x

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [redis/redis-rb#1160]
5.x raises an exception if values are not of type String, Array or Hash (or [a subclass in an unreleased version](https://github.com/redis-rb/redis-client/issues/51)).
4.x just calls `to_s`, so it is allowing many more types of input.

It would make it a safer upgrade path, if 4.x could log a deprecation warning when the arguments are such that 5.x would not allow them.

**Comment by byroot** [comment]
Sorry but no, 4.8 added some easy deprecations to help the transition, but I have no plan to be exhaustive, and this one is just too much work.
