### ISSUE TITLE
Returning bad values when using ConnectionPool and Parallel testing

### ISSUE THREAD

**Issue by Linuus** [redis/redis-rb#1162]
This is a weird one and I'm not sure if it's related to the redis gem, ConnectionPool or my own code... It's only happening when running multiple tests at the same time with Rails' parallel testing.

We have a `RedisPool` class in a Rails initializer that looks like this:

```rb
class RedisPool
  def initialize
    @pool_size = ENV.fetch("REDIS_POOL", 5).to_i
    @config = YAML.load_file(Rails.root.join("config", "redis.yml")).fetch(Rails.env).deep_symbolize_keys
    set_connection_pool
  end

  def reconfigure(db:)
    @config[:db] = db
    set_connection_pool
  end

  delegate(:with, to: :connection_pool)

  def safe_with(returning, &)
    with(&)
  rescue ::Redis::BaseError => error
    report_to_error_service(error)
    returning
  end

  private

  attr_reader(:connection_pool)

  def set_connection_pool
    @connection_pool = ConnectionPool.new(size: @pool_size, timeout: 5.0) { Redis.new(@config) }
  end
end

REDIS_POOL = RedisPool.new
```

Then, in a test helper we run:

```rb
    parallelize_setup do |worker|
      REDIS_POOL.reconfigure(db: worker + 1)
    end

    setup do
      REDIS_POOL.with(&:flushdb)
    end

    teardown do
      REDIS_POOL.with(&:flushdb)
    end
```

To give each worker process its own DB and clean up before/after tests.

This works fine with redis gem 4.8.0 but when bumping to 5.0 we have issues. Some commands seems to return "OK" sometimes when they shouldn't. For instance, sometimes `redis.ttl` returns "OK" instead of an integer.

Also, code like this:

```rb
  GET_OR_SET = <<~LUA
    -- Name: get_or_set
    local key = KEYS[1]
    local next_value = ARGV[1]
    local expire_in = tonumber(ARGV[2] or -1)

    if redis.call("exists", key) == 1 then
      return redis.call("get", key)
    else
      redis.call("setex", key, expire_in, next_value)
      return next_value
    end
  LUA

  def get_or_set_status
    value = REDIS_POOL.safe_with(nil) do |redis|
      redis.eval(GET_OR_SET, keys: [key], argv: [id, time_to_perform.to_i])
    end

    # value is sometimes "OK" and sometimes the correct value of `next_value`/ `key`.
  end
```

I don't really know what's going on but I know that when running `PARALLEL_WORKERS=1 rails test` the issue goes away.

It _might_ have something to do with those `flushdb` calls in `setup` and `teardown`. `flushdb` returns `"OK"` so it's like the response from those calls are leaking into the other calls 😕 

Oh, also, I have tested this with both Redis 4 and 5 and the same issue is there in both of those versions.

Any ideas of anything in the 5.0 gem version that might cause this?

**Comment by byroot** [comment]
Hello. Can you tell me which version of redis 5 you are using, as well as the version of the `redis-client` gem? Because that looks a lot like what was fixed in redis-client `0.8.1` https://github.com/redis-rb/redis-client/blob/master/CHANGELOG.md#081

**Comment by byroot** [comment]
> redis 5

I mean the gem here, not the server.

**Comment by Linuus** [comment]
It's 5.0.1. I'll test with the latest version. I missed there were some newer releases.

**Comment by byroot** [comment]
:ok_hand: Yes please test the latest ones.

Also while we're at it, if I were you I'd change:

```ruby
  def reconfigure(db:)
    @config[:db] = db
    set_connection_pool
  end
```

Into 
```ruby
  def reconfigure(db:)
    @config = @config.merge(db: db)
    set_connection_pool
  end
```

As it's best not to assume clients won't hold onto that original config hash (probably fine right now, but it's not part of the contract)

**Comment by byroot** [comment]
Hum, actually, the more I look at your RedisPool, the lest I understand how it can work in a parallel test environment. Each parallel worker should have it's own pool instance, it doesn't seem like it's doing that.

**Comment by byroot** [comment]
Ah, nevermind, if you use workers (forked processes) then it likely work (still not very safe IMO but...)

**Comment by Linuus** [comment]
Tried with 5.0.5 and it seems to be working! 

> Hum, actually, the more I look at your RedisPool, the lest I understand how it can work in a parallel test environment. Each parallel worker should have it's own pool instance, it doesn't seem like it's doing that.

Hm, I think they do?

**Comment by Linuus** [comment]
> Ah, nevermind, if you use workers (forked processes) then it likely work (still not very safe IMO but...)

Ok :) Yeah it's probably due for some refactoring.

Thanks!
