### ISSUE TITLE
Redis `#get` in 5.0.5 takes longer to run than in 4.8.0

### ISSUE THREAD

**Issue by kaylareopelle** [redis/redis-rb#1164]
While working on updating Redis instrumentation for the New Relic Ruby agent, I noticed a consisten 3 ms duration difference when making a single call to `#get` between version 4.8.0 and 5.0.5. 

This doesn't show up when testing with `Benchmark.ips`, which looks like the method of choice in `redis-client`, but there a time difference does show up using `Benchmark.bmbm`.

Here's a gist with my testing scripts and the results: https://gist.github.com/kaylareopelle/f9e213c126f85a57fac1853e2911523e 

Unfortunately, I don't have any ideas about where this slowdown may have been introduced between the two versions. I mostly wanted to make sure your team was aware! 

Thanks for your work maintaining this critical gem!

**Comment by casperisfine** [comment]
Thank you for the report, I'll try to have a look soonish. A few observations:

  - Not sure if it's a typo, but both benchmark use `gem('redis', '5.0.5')`.
  - `Redis.new.get('key")` means you benchmark both connecting an doing a query. I'm pretty sure 5.0 should be faster on query, but it's possible it got slower on connecting I'll have to check that.
  - Generally speaking `Benchmark.bmbm` give much less precise results than `benchmark-ips`, so I suspect it's likely just an artifact of the benchmark, but I'd still like to figure out the reason.

**Comment by casperisfine** [comment]
So I reworked the benchmark a bit. As suspected, the performance of `get` (and all other commands) is very much on par with 4.x.

Where the performance degraded very significantly, is during connection establishment, it's about 6x slower on my machine. I'll dig more.

**Comment by casperisfine** [comment]
A quick profiling show that we're spending lots of time in `Addrinfo.getaddrinfo`:

redis 4:

```
==================================
  Mode: wall(1000)
  Samples: 145 (0.00% miss rate)
  GC: 2 (1.38%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
        34  (23.4%)          34  (23.4%)     IO#wait_readable
        34  (23.4%)          34  (23.4%)     IO#wait_writable
        23  (15.9%)          20  (13.8%)     Socket#__connect_nonblock
         6   (4.1%)           6   (4.1%)     IO#read_nonblock

```

redis 5:

```
==================================
  Mode: wall(1000)
  Samples: 263 (0.38% miss rate)
  GC: 2 (0.76%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       149  (56.7%)         149  (56.7%)     Addrinfo.getaddrinfo
        36  (13.7%)          36  (13.7%)     IO#wait_writable
        27  (10.3%)          27  (10.3%)     IO#wait_readable
        19   (7.2%)          19   (7.2%)     Socket#__connect_nonblock
         8   (3.0%)           8   (3.0%)     Socket#initialize
         5   (1.9%)           5   (1.9%)     IO#read_nonblock
         5   (1.9%)           5   (1.9%)     IO#write_nonblock
```

**Comment by casperisfine** [comment]
Ok, I figured it out. The difference is that in `4.x` the default `host` is `127.0.0.1` whereas in `5.x` it's `localhost`.

So 5.x has to resolve the domain every time, which is a bit more costly.

I'm not sure if it's really worth changing the default back to `127.0.0.1`, as it's not a good idea to connect that often anyway, and in most production scenarios the Redis server won't be on `localhost` anyway.

I think I'll close as WONTFIX.

**Comment by kaylareopelle** [comment]
Thank you, @casperisfine for digging into this! Glad to see the impacts are just on localhost and that nothing serious needs to change.
