### ISSUE TITLE
XAUTOCLAIM throws NoMethodError if entry is nil

### ISSUE THREAD

**Issue by wcmonty** [redis/redis-rb#1165]
If an entry in the PEL is deleted, `xautoclaim` returns nil for the event in the response. When processing that event, it is passed to the `HashifyStreamAutoclaim` lambda where it throws an error because the lambda assumes there's an actual event. See the following sample script. I tested with v4.5.1, but it looks like the lambda is [unchanged in the current version](https://github.com/redis/redis-rb/blob/787462e8a120bf08759109c8ff68309d5efebe7f/lib/redis/commands.rb#L119-L124).

```ruby
redis.xgroup(:create, 'key', 'group1', '$', mkstream: true)
# => "OK"
redis.xadd('key', { foo: :bar }, id: '1')
# => "1-0"
redis.xreadgroup('group1', 'consumer1', 'key', '>', count: 1)
# => {"key"=>[["1-0", {"foo"=>"bar"}]]}
redis.xdel('key', '1-0')
# => 1
redis.xautoclaim('key', 'group1', 'consumer2', 0, '0-0', count: 1)
# NoMethodError: undefined method `[]' for nil:NilClass
# 
#      'entries' => reply[1].map { |entry| [entry[0], entry[1].each_slice(2).to_h] }
#                                                ^^^
# from /usr/local/bundle/gems/redis-4.5.1/lib/redis.rb:3704:in `block (2 levels) in <class:Redis>'
```

This is similar to https://github.com/redis/redis-rb/issues/905. It looks like [Redis server is changing its behavior as of v7.0](https://github.com/redis/redis/pull/10227), so this will no longer be an issue.

I think the solution is to compact the array before we map over it.

**Comment by byroot** [comment]
Fixed in https://github.com/redis/redis-rb/pull/1166
