### ISSUE TITLE
Support for circuit-breaker RedisClient config option

### ISSUE THREAD

**Issue by Juanmcuello** [redis/redis-rb#1171]
RedisClient recently introduced a [circuit_breaker](https://github.com/redis-rb/redis-client/pull/70) config option, which seems to be very useful for handling temporally down Redis servers.

Is there any chance we can support this option here too?

**Comment by byroot** [comment]
`redis-rb` pass initialization options to `redis-client`, so it's automatically supported if `redis-client` is recent enough.

That said I haven't cut a release with circuits breakers yet.
