### ISSUE TITLE
Redis::CommandError: ERR wrong number of arguments for 'hset' command when using v5+ but not v4.8.0

### ISSUE THREAD

**Issue by crimson-knight** [redis/redis-rb#1172]
I found an interesting bug between v4.7.1 & v5.0.5 that I can't seem to wrap my head around why it's happening.

Verify you have v5+ `gem list redis$` and as long as there is any v5 version listed, you can run this one file app and get the error.

Then I would just uninstall whichever version you have, install 4.8.0 and re-run the code below and it works without raising the error.

use this example file:
```ruby
require "redis"

job_run_meta_data = { 
  "job_options": {}
}

redis_adapter = Redis.new(host: "localhost", port: "6379")
puts redis_adapter.inspect
redis_adapter.hset("example_key", job_run_meta_data)
```

I tried fussing around with this but couldn't get further than identifying this issue.

**Comment by byroot** [comment]
It's because 4.x would call `to_s` on all arguments, so it wasn't doing what you think it was doing:

```ruby
>> Redis.new.hgetall("example_key")
=> {"job_options"=>"{}"}
```

If for some reason you want to keep that behavior, you can do:

```ruby
redis_adapter.hset("example_key", job_run_meta_data.transform_values(&:to_s))
```

But yes, 5.x is stricter to avoid these explicit conversions to string.
