### ISSUE TITLE
Redis 5 hset TypeError: Unsupported command argument type: ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by javinto** [redis/redis-rb#1173]
In Redis 4.x

`$redis.hset('mykey', created_at: Time.current) => 1`

In Redis 5.x

```
$redis.hset('mykey', created_at: Time.current) =>
TypeError: Unsupported command argument type: ActiveSupport::TimeWithZone

```
Any other (Date)Time class value raises an exception:
```
$redis.hset('mykey', created_at: Time.now) =>
TypeError: Unsupported command argument type: Time

```
The same for NIL class:

```
$redis.hset 'mykey', by: nil
TypeError: Unsupported command argument type: NilClass

```
The Workaround is to use Time.current.to_s but is this behavior meant to be? I guess this is a bug?

**Comment by byroot** [comment]
That is by design. All arguments must be casted to one of the supported types. Mostly strings or numerics.
