### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_read: shutdown while in init

### ISSUE THREAD

**Issue by jordanfbrown** [redis/redis-rb#1174]
We're using version 4.8.0 of this gem and recently switched to an [AWS ElastiCache cluster with in-transit encryption enabled](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html) for our Sidekiq Redis cluster (engine version 6.2.6) and our caching Redis cluster (engine version 7.0.4). 

Since switching over, we've been seeing approximately 100-200 `OpenSSL::SSL::SSLError: SSL_read: shutdown while in init` errors per day. We're seeing this issue in both Redis clusters (6.26 and 7.0.4). We're connecting to Redis via the `rediss://` protocol in the URL (not using the `ssl` option):

```ruby
Redis.new(
  url: "rediss://:somepassword@master.some-redis-url.wze32a.usw2.cache.amazonaws.com:6379"
)
```

Here's an example (abbreviated) stack trace:

```
OpenSSL::SSL::SSLError: SSL_read: shutdown while in init
  from openssl/buffering.rb:214:in `sysread_nonblock'
  from openssl/buffering.rb:214:in `read_nonblock'
  from redis (4.8.0) lib/redis/connection/ruby.rb:55:in `block in _read_from_socket'
  from redis (4.8.0) lib/redis/connection/ruby.rb:54:in `loop'
  from redis (4.8.0) lib/redis/connection/ruby.rb:54:in `_read_from_socket'
  from redis (4.8.0) lib/redis/connection/ruby.rb:47:in `gets'
  from redis (4.8.0) lib/redis/connection/ruby.rb:382:in `read'
  from redis (4.8.0) lib/redis/client.rb:311:in `block in read'
  from redis (4.8.0) lib/redis/client.rb:299:in `io'
  from redis (4.8.0) lib/redis/client.rb:310:in `read'
  from redis (4.8.0) lib/redis/client.rb:238:in `block (2 levels) in call_pipelined'
  from redis (4.8.0) lib/redis/client.rb:234:in `each'
  from redis (4.8.0) lib/redis/client.rb:234:in `each_with_index'
  from redis (4.8.0) lib/redis/client.rb:234:in `block in call_pipelined'
  from redis (4.8.0) lib/redis/client.rb:279:in `block (2 levels) in process'
  from redis (4.8.0) lib/redis/client.rb:420:in `ensure_connected'
  from redis (4.8.0) lib/redis/client.rb:269:in `block in process'
  from redis (4.8.0) lib/redis/client.rb:356:in `logging'
```

We're using OpenSSL 1.1.1 on our application server:

```
$ openssl version
OpenSSL 1.1.1n  15 Mar 2022
```

I haven't been able to find much information on this error, so I'm wondering if anybody else has run into something similar or has any ideas regarding what the root cause might be. Based on another [similar-looking issue](https://github.com/redis/redis-rb/issues/1106), it looks like it may have to do with connections that are failing to shut down gracefully.

**Comment by jordanfbrown** [comment]
It looks like version 5 of this gem introduces a dependency on the [redis-client](https://github.com/redis-rb/redis-client) gem and moves a lot of the logic into there instead. I'm hoping to eventually schedule an upgrade to see if it solves the issue.

In the meantime, I was able to solve this issue by monkey-patching the `Redis::Connection::Ruby#read` method with a new condition in the `rescue` block for the `SSL_read: shutdown while in init` error. I'm raising a `Errno::ECONNABORTED` which is caught here: https://github.com/redis/redis-rb/blob/v4.8.0/lib/redis/client.rb#L305-L307, which I believe causes it to retry establishing the connection instead of failing loudly. 

```ruby
class Redis
  module Connection
    class Ruby
      def read
        line = @sock.gets
        reply_type = line.slice!(0, 1)
        format_reply(reply_type, line)
      rescue Errno::EAGAIN
        raise TimeoutError
      rescue OpenSSL::SSL::SSLError => ssl_error
        if ssl_error.message.match?(/SSL_read: unexpected eof while reading/i)
          raise EOFError, ssl_error.message
        elsif ssl_error.message.match?(/SSL_read: shutdown while in init/i)
          # This condition is new
          raise Errno::ECONNABORTED, ssl_error.message
        else
          raise
        end
      end
    end
  end
end
```

**Comment by byroot** [comment]
Interesting fix. If you can reproduce this on version 5, I'd merge such a fix for redis-client.

**Comment by byroot** [comment]
This is stale, and 4.x is no longer maintained. Closing.

**Comment by ngan** [comment]
Hey @jordanfbrown what OS and version were you on were you were seeing this error?
