### ISSUE TITLE
Require `redis/connection/hiredis` no longer works

### ISSUE THREAD

**Issue by vietqhoang** [redis/redis-rb#1178]
See the following issue: https://github.com/redis/hiredis-rb/issues/92

I was trying to trace the issue. I noticed the `/lib/redis/connection/hiredis.rb` file is no longer present and it seem it has disappeared within the last year.

Reviewing the change log for major version 5 didn't make any mention of this being dropped: https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#500

The use of hiredis has been supported since version 2.2: https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#220

> Use [hiredis](https://github.com/pietern/hiredis-rb) (v0.3 or higher) by requiring "redis/connection/hiredis".

And https://github.com/redis/hiredis-rb#redis-rb

> gem "redis", ">= 3.2.0", :require => ["redis", "redis/connection/hiredis"]

Can some clarity be given on the change? Is there an alternative available?

**Comment by vietqhoang** [comment]
I did some digging and was able to source the PR responsible for the change here: https://github.com/redis/redis-rb/pull/1120

And specifically this commit: https://github.com/redis/redis-rb/pull/1120/commits/d113f69155e8753c57f07d0deaf69b9141eba4b6

It looks like a lot of the work was to remove the `synchrony` driver, which the change log did mention (both in major version 5 and a deprecation warning in 4.2). But it looks like `hiredis` was the quiet participant in the changes.

--

My motivation is to have our application move from version ~4 to version ~5 and the primary roadblock is the hiredis driver no longer available.

Have the changes done in version 5 suggest the need for hiredis is no longer required? I am just looking for information so I can make the best informed decision on how to approach our apps integration of hiredis, such as the consideration of just dropping it...

**Comment by byroot** [comment]
See https://github.com/redis/redis-rb#hiredis-binding

**Comment by contentfree** [comment]
So how does one get hiredis working these days? The docs in the redis/hiredis-rb project say to do:

```
gem 'hiredis'
gem 'redis', require: ["redis", "redis/connection/hiredis"]
```

But that doesn't work. 

The link that @byroot mentioned talks about using hiredis-client which, as far as I can tell, is a completely different gem than redis/hiredis-rb. Is it a drop in replacement? Can it be used with Rails cache in the same way? 

It would be great if a redis / hiredis maintainer could update the documentation to let us know the current way to use hiredis. Much thanks!

**Comment by byroot** [comment]
AFAIK the `hiredis` gem isn't maintained.

As for `hiredis-client`, it's compatible with `redis-rb` 5.x.

If you are still on redis-rb 4.x, I don't recommend trying to use `hiredis`.
