### ISSUE TITLE
Facing Redis::ConnectionError (EOFError)

### ISSUE THREAD

**Issue by rishijain** [redis/redis-rb#1180]
Heroku-18, 20, 22 (fails with all)
Rails 6.1
Ruby 3.1.3
Redis 6
redis (5.0.6)
redis-client (0.12.2)

I am doing something like:
`Rails.cache.redis.keys` where I get the error at.

I am doing this at 2 places, one a initializer file, and other at controller action level.

I get `Redis::ConnectionError (EOFError)` when I sit idle for 4 minutes or so.
I thought this would be related to:
```
https://github.com/sidekiq/sidekiq/issues/5402
https://github.com/redis/redis/issues/10915
https://github.com/redis/redis-rb/issues/1106
https://github.com/redis/redis-rb/pull/1107
https://github.com/redis/redis/pull/10931
```

I even tried to set the timeout to a larger value to see if that fixes the issue but the issue persists.
```
Redis.new(url: "REDIS_URL", timeout: 90000
```

I think the redis connection is lost when idle after a certain time, but not sure how to fix it.
Thanks!

**Comment by byroot** [comment]
Ok, I think see where the problem is. `redis-rb` 4.x used to set SO_KEEPALIVE and that was lost in translation. I'll fix this very soon.

**Comment by rishijain** [comment]
Thanks!

I ended up adding `reconnect_attempts` for now which seems to fix it:
```
config.cache_store = :redis_cache_store, { url: REDIS_URL, reconnect_attempts: 3 }
```

**Comment by byroot** [comment]
`redis-client 0.13.0` should fix this.
