### ISSUE TITLE
logger support

### ISSUE THREAD

**Issue by dgeller-OUHSC** [redis/redis-rb#1182]
Hi! I am curious if there is any more info on the removal of the [logger ](https://github.com/redis/redis-rb/commit/08a21001b5f27088a412fbe7a6fba8d558eade40#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)as option part of the 5.0 release.  Is there another logging solution that is recommended?

**Comment by byroot** [comment]
Not much more info, It's just that the performance overhead wasn't justified in my opinion and the logs weren't very useful.

If you really want a logger back, it can be implemented using a middleware: https://github.com/redis-rb/redis-client#instrumentation-and-middlewares

**Comment by rapito** [comment]
> Not much more info, It's just that the performance overhead wasn't justified in my opinion and the logs weren't very useful.
> 
> If you really want a logger back, it can be implemented using a middleware: https://github.com/redis-rb/redis-client#instrumentation-and-middlewares

Is there an option for instrumentation for users that don't rely on redis-client? 

I would want to avoid beating around the bush for the reasoning behind using the `redis-client` gem or not, but it would be helpful to know if there are any existing solutions to adding a logger or instrumentation middleware without instantiating a redis-client sourced instance.

**Comment by rapito** [comment]
> > adding a logger or instrumentation middleware without instantiating a redis-client sourced instance.
> 
> `redis-rb` is just a decorator around `redis-client`. So if you add a logger to redis-client using its middleware API, it will log everything `redis-rb` does.

I see.... I thought `redis-client` was the decorator around `redis-rb` instead. 

I am not using redis-client directly, only Redis.new and then pass the config myself. This is for some special cases I have and I'd rather just have `redis-rb` + `connection_pool` handle  any thread-safety concerns as [described here](https://github.com/redis/redis-rb?tab=readme-ov-file#connection-pooling-and-thread-safety).

Regardless, I can see that redis-rb does require redis-client as a dependency, so I will try to adapt my current config to use the middleware then.

Thanks
