### ISSUE TITLE
Correct official redis-rb cluster client?

### ISSUE THREAD

**Issue by raansari** [redis/redis-rb#1197]
While exploring redis-ruby cluster for implementation in prod, came across [redis-cluster gem](https://github.com/bukalapak/redis-cluster) 

In the [redis repo](https://github.com/redis/redis-rb#cluster-support) there is reference to [redis-clustering gem](https://github.com/redis/redis-rb/tree/master/cluster) however in the [clients section](https://redis.io/resources/clients/) the reference is to [redis-cluster gem] (https://github.com/bukalapak/redis-cluster) 

https://redis.io/resources/clients/

<img width="1792" alt="Screenshot 2023-06-07 at 5 45 44 PM" src="https://github.com/redis/redis-rb/assets/6706803/5e1bee2a-7d24-46ba-99e0-b534baf1d682">

Is [redis-cluster gem](https://github.com/bukalapak/redis-cluster) an official recommendation too to used in prod environment?

One reason of exploration is to know if clustering can be implemented on an app running on ruby 2.2 and using 'redis', '~> 3.2.1' or if there is a unavoidable need to upgrade app's ruby version to >=2.7  as an upgrade is not planned for this quarter 

Thank you,
@raansari

**Comment by byroot** [comment]
The gem to use with `redis-rb` is `redis-clustering` https://github.com/redis/redis-rb/blob/fde7873de430e46302869d52e23fa6fd0aab1470/cluster/redis-clustering.gemspec#L6



> however in the [clients section](https://redis.io/resources/clients/) the reference

I have no control over this website, it's owned by Redis Lab, and I doubt they care much about this, but feel free to report it there.

**Comment by supercaracal** [comment]
* https://github.com/redis/redis-doc/pull/2041
* https://github.com/redis/redis-doc/pull/2297

`redis-clustering` was added in the former PR, but their site generator doesn't support mono repo, so it was deleted as a dead link in the latter PR.
