### ISSUE TITLE
Handling redirection when migrating to cluster

### ISSUE THREAD

**Issue by gayanW** [redis/redis-rb#1198]
I'm trying to migrate some data from standalone Redis server to a new cluster.

```
require 'redis'
require 'redis-clustering'

redis_source = Redis.new(host: host, port: port)
redis_source.migrate(key_to_migrate, { :host => cluster_host, :port => cluster_port })
```

But the above code would result in the error:

> redis-client-0.14.1/lib/redis_client/connection_mixin.rb:35:in `call': MOVED 10772 101.37.68.10:7100 (RedisClient::CommandError)

I've looked into the interfaces provided by [redis-clustering](https://github.com/redis/redis-rb/tree/master/cluster). But I'm not sure how to make use of it in my scenario.
```
target = Redis::Cluster.new(nodes: (7100..7101).map { |port| "#{cluster_host}:#{port}" })
puts target_cluster.inspect
```

**Comment by supercaracal** [comment]
@gayanW Unfortunately, our redis client is just a client, it doesn't support migration from standalone servers to a cluster. Since redis cluster does sharding, keys should be migrated to corresponding nodes. The redis-client is for standalone server, so it doesn't know the destination node which the key should be migrated. There might be some ways using 3rd party tools for migration or making it yourself.

**Comment by supercaracal** [comment]
A naive tool be like:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'redis-cluster'
  gem 'redis-cluster-client'
end

src = RedisClient.config(host: '127.0.0.1', port: 6378).new_client
dest = RedisClient.cluster(host: '127.0.0.1', port: 6379).new_client

# clear test data
src.call('FLUSHALL')
dest.call('FLUSHALL')

# register test data
100.times do |i|
  src.call('SET', "key#{i}", i)
end

# migrate a standalone server to a cluster
src.scan do |key|
  slot = ::RedisClient::Cluster::KeySlotConverter.convert(key)
  node_key = dest.instance_variable_get(:@router).instance_variable_get(:@node).find_node_key_of_primary(slot)
  host, port = ::RedisClient::Cluster::NodeKey.split(node_key)
  raise "host: #{host}, port: #{port}, key: #{key}" if host.nil? || port.nil? || key.nil?

  src.blocking_call(10, 'MIGRATE', host, port, key, 0, 7, 'COPY', 'REPLACE')
end

# print test data
dest.scan do |key|
  print "#{key}\n"
end
```
