### ISSUE TITLE
Add support for KEEPTTL option

### ISSUE THREAD

**Issue by davkim** [redis/redis-rb#1202]
From Redis version >= 6.0, the set command supports KEEPTTL option which retains the ttl associated with the key, but the current redis-rb library doesn't seem to support it.

**Comment by davkim** [comment]
Looks like there is keepttl option supported, but somehow in our project the installed gem doesn't seem to support it

**Comment by byroot** [comment]
Are you on 4.2+? That's when it was added.

If it still doesn't work, try `p redis.method(:set)`, that should tell you if something decorated or monkey patched the method.
