### ISSUE TITLE
Calling set with keepttl=true returns false

### ISSUE THREAD

**Issue by davkim** [redis/redis-rb#1203]
I am currently on redis gem version=4.2.0

I see that in the code the keepttl is supported, however calling `cache.set(key, value, keepttl: true)` returns false instead of OK. I tried for the same key and value pair calling without `keepttl: true` returns OK.

Any idea why this is failing?

**Comment by byroot** [comment]
First Redis 4.2.0 is way outdated.

But even then:

```ruby
>> Redis::VERSION
=> "4.2.0"
>> Redis.new.set("foo", "bar", keepttl: true)
=> "OK"
```

So whatever is happening isn't a problem with the gem, perhaps you have something monkey patching it or something.
