### ISSUE TITLE
Redis::CommandError < RedisClient::CommandError

### ISSUE THREAD

**Issue by pboling** [redis/redis-rb#1206]
Why not this?

It seems like it would be helpful for libraries initially built on top of `redis` that later switch to `redis-client` for fine tuning (e.g. seems this is what happened with `redlock`).

For more context: https://github.com/leandromoreira/redlock-rb/issues/135

**Comment by byroot** [comment]
Because `Redis::CommandError` already has a superclass.

**Comment by pboling** [comment]
Fair. 👯
