### ISSUE TITLE
sadd? srem? - rant

### ISSUE THREAD

**Issue by taf2** [redis/redis-rb#1207]
This interface change in 4.7/4.8 gem series really makes no sense.  question mark methods usually implement a read only method... File.exist? for example makes sense does the file exist does not change the file.   Breaking compatibility in 5.0 also seems unnecessary what is the performance/usability improvement?

I realize this is a rant... but I'm faced now with updating thousands of lines of code and i think it will be easier to just fork.

**Comment by byroot** [comment]
Help yourself, that's what open source is for.
