### ISSUE TITLE
Redis 7.2 test failures

### ISSUE THREAD

**Issue by voxik** [redis/redis-rb#1208]
A while ago, Redis 7.2 RC landed in Fedora and since that we observe several test suite issues. Trying to enable Redis 7.2 upstream ([my test PR](https://github.com/voxik/redis-rb/pull/1)), I have hit the same failures:

~~~
  1) Failure:
TestScanning#test_sscan_with_encoding [/home/runner/work/redis-rb/redis-rb/test/redis/scanning_test.rb:142]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"hashtable"
+"listpack"


  2) Failure:
TestRemoteServerControlCommands#test_object [/home/runner/work/redis-rb/redis-rb/test/redis/remote_server_control_commands_test.rb:78]:
Wrong encoding for list
~~~

Not sure what causes them.

**Comment by sundb** [comment]
The reason is that `set` support `listpack` encoding since Redis 7.2.
