### ISSUE TITLE
5.0.7 started sending username & password to sentinels?

### ISSUE THREAD

**Issue by jdelStrother** [redis/redis-rb#1213]
Hi there - it looks like 5.0.7 (or the recent redis-client release?) started defaulting to the username & password from the main config when talking to sentinels.

Our redis-rb configuration looks like:

```ruby
{
  username: "rails",
  password: "xxx",
  sentinels: [
    { host: "1.2.3.4", port: "26379"},
    { host: "1.2.3.5", port: "26379"},
    { host: "1.2.3.6", port: "26379"}
  ],
  name: "redis-vanilla"
}
```

We have ACL users set up on our redis instance, but not on the sentinels, which just use the default nopass user. On upgrading to redis-rb 5.0.7 & redis-client 0.15.0, we started getting `WRONGPASS invalid username-password pair or user is disabled` on every redis call.

I can avoid this by adding `username: nil, password: nil` to the sentinel config, but wondered if it was worth highlighting the change in the release notes or sentinel documentation.

**Comment by byroot** [comment]
Yes, it's after https://github.com/redis-rb/redis-client/pull/117

It's considered a bug fix because this restore a behavior that was lost in the 4.x -> 5.x transition.

> wondered if it was worth highlighting the change in the release notes or sentinel documentation.

PR welcome.

**Comment by moofkit** [comment]
@byroot I see the little problem here.

with current client interface we are assuming that username/password for sentinels and for redis master/replicas are the same. But is not always the case.
Sometimes admins wants different acl's for sentinels.
Let me provide some examples:

1. Redis master/replica has auth with user/password and sentinels doesn't have it (@jdelStrother case)
it can be solved by this code [from related PR](https://github.com/redis/redis-rb/pull/1214/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R135-R139)
```
# Use 'mysecret' to authenticate against the mymaster instance, but skip authentication for the sentinels:
SENTINELS = [{ host: '127.0.0.1', port: 26380, password: nil },
             { host: '127.0.0.1', port: 26381, password: nil }]

redis = Redis.new(name: 'mymaster', sentinels: SENTINELS, role: :master, password: 'mysecret')
```

2. Redis master/replica has auth but sentinels has different credentials.
It can be solved with this configuration
```
# Use 'mysecret' to authenticate against the mymaster instance, but skip authentication for the sentinels:
SENTINELS = [{ host: '127.0.0.1', port: 26380, password: 'supersecret' },
             { host: '127.0.0.1', port: 26381, password: 'supersecret' }]

redis = Redis.new(name: 'mymaster', sentinels: SENTINELS, role: :master, password: 'mysecret')
```
However there also [Sentinels list automatic refresh](https://redis.io/docs/reference/sentinel-clients/) and we have to substitute  auth credentials for new sentinel and with current solution there will be wrong password though (for the master/client). There was related issue about [similar case](https://github.com/redis-rb/redis-client/commit/cb53368b6cc98146e4b379f9edfd48e06bf6f193)

3. Master/replica and sentinels credentials are the same. We are good here.

So, it looks like we have to have shared credentials for sentinels but it probably should be under their own explicit kwargs. What do you think about to introduce a little different interface for it?
Something like that
```ruby
SENTINELS = [{ host: '127.0.0.1', port: 26380},
             { host: '127.0.0.1', port: 26381}]

redis = Redis.new(
  name: 'mymaster',
  role: :master,
  username: 'backend',
  password: 'mysecret',
  sentinels: SENTINELS,
  sentinel_username: 'backend',
  sentinel_password: 'supersecret'
)
```

Thus we will solve both case 1, 2 and make it a little more clear in my opinion. I can prepare PR for `redis-client`

**Comment by byroot** [comment]
> What do you think about to introduce a little different interface for it?

I'm not a huge fan, but I get your point and don't have a better suggestion, so I'd say go ahead.

**Comment by moofkit** [comment]
@byroot should I prepare PR with updated readme for `redis-rb` itself related with this? https://github.com/redis-rb/redis-client/pull/137

**Comment by byroot** [comment]
Sure. Thank you.
