### ISSUE TITLE
Problem with Sentinel passwords

### ISSUE THREAD

**Issue by tycooon** [redis/redis-rb#1216]
The [documentation](https://github.com/redis/redis-rb#sentinel-support) currently states:

> If you specify a username and/or password at the top level for your main Redis instance, Sentinel will default to using those credentials. You can pass nil or override them for each sentinel.

However, it turns out it doesn't work like this. The top-level password is not used for sentinels, so I had to put it **both** on top-level and for each Sentinel to make it work. Also I'm not sure why I needed top-level password in case it's present in each Sentinel.

So I think either the code or the docs should be fixed since it took some time for me to find out the problem, and I know I'm not the only one who faced it.

**Comment by byroot** [comment]
Are you using the latest `redis-rb` and `redis-client`?

**Comment by byroot** [comment]
I'm going to assume you are using an older version. I'll reopen if not.
