### ISSUE TITLE
Cluster Mode: Transactions (multi)

### ISSUE THREAD

**Issue by nicdal** [redis/redis-rb#1224]
Hi 👋 ,

After 5.0.0 it's not possible to use the multi call due to the error message:
`Redis::Cluster::AmbiguousNodeError: Cluster client doesn't know which node the multi command should be sent to.`

What is the recommended solution for transactions in cluster mode?

One example of how we use transactions.
```
MULTI
DEL key
PFADD key 1
EXPIRE key 60
EXEC
```

**Comment by supercaracal** [comment]
Unfortunately, current client doesn't implement transaction method. It may be able to make it by lua scripts.

https://redis.io/docs/interact/transactions/#redis-scripting-and-transactions
