### ISSUE TITLE
not able to subscribe to channels

### ISSUE THREAD

**Issue by quadriq** [redis/redis-rb#1228]
Hi,
I am trying to subscribe to a channel and display results

```
require "redis"

redis = Redis.new(
  host: "123.222.111.11",
  port: 6379,
)

redis.psubscribe("test") do |on|
  on.psubscribe do |pattern, total|
    puts "Subscribed to ##{pattern} (#{total} subscriptions)"
  end

  on.message do |channel, message|
    # Print the message when it is received
    puts "Received message on channel #{channel}: #{message}"
  end
end

```

if I run script from the console with `ruby sub.rb` then it does just nothing.
If I post messages to the channel, I see them in redis console

```
127.0.0.1:6379> psubscribe test
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "test"
3) (integer) 1
1) "pmessage"
2) "test"
3) "test"
4) "xxxxxxxxx"
```
But there is no output in the ruby-script console.

I am sure that connection to server works, because I can read keys like  `p redis.get("mykey")`
And I can publish messages with `redis.publish("test", "xxxxxxxxx")`

**Interessting**, that after aborting the script, or restarting redis server, I am getting
`Subscribed to test (1 subscriptions)
`
As if something blocking the ruby-script...

what could it be ?

**Comment by supercaracal** [comment]
It seems that we should track 'pmessage' instead of 'message'.

https://github.com/redis/redis-rb/blob/ccdf15f4e99eb0bf8f7cc41d5afe6d7dd2782dff/test/redis/publish_subscribe_test.rb#L73-L92

**Comment by quadriq** [comment]
thanks. it works with `on.pmessage`
Also stucking with output until script exit was due to git-bash console on windows. it works fine on cmd or linux.
