### ISSUE TITLE
`.connection` method raises error in a Sentinel-based setup 

### ISSUE THREAD

**Issue by slai11** [redis/redis-rb#1231]
### Issue

Sentinel creation uses `client_implementation: ::RedisClient` in https://github.com/redis/redis-rb/blob/2b183addb9175641a48e1d8616772282a31c0532/lib/redis/client.rb#L27C38-L27C74 which differs from a standalone client which defaults to `Redis::Client` as part of a compatibility fix in https://github.com/redis/redis-rb/pull/1210.

This leads to different behaviours w.r.t `@client` in `Redis::Client`. In this case, when `.connection` is called, it breaks for a sentinel-setup since the dependent methods like `.host` are in the `config` object in `::RedisClient`.

### Locally reproducible example

Note: i've configured a Redis sentinel setup using https://gitlab.com/schin1/redis-sentinel-setup if it helps.

```
➜  redis-rb git:(master) ✗ bin/console
irb(main):001:0> redis = ::Redis.new
=> #<Redis client v5.0.8 for redis://localhost:6379/0>
irb(main):002:0> sentinel = ::Redis.new({:password=>"password123",:name=>"mymaster", :sentinels=>[{:host=>"localhos
t", :port=>26480, :password=>"password456"},{:host=>"localhost", :port=>26481, :password=>"password456"},{:host=>"l
ocalhost", :port=>26482, :password=>"password456"}]})
=> #<Redis client v5.0.8 for redis://127.0.0.1:6480/0>


irb(main):003:0> redis.connection
=> {:host=>"localhost", :port=>6379, :db=>0, :id=>"redis://localhost:6379/0", :location=>"localhost:6379"}
irb(main):004:0> sentinel.connection
/Users/sylvesterchin/oss_repos/redis-rb/lib/redis.rb:124:in `connection': undefined method `host' for #<RedisClient redis://127.0.0.1:6480/0> (NoMethodError)
        from (irb):4:in `<main>'
        from bin/console:8:in `<main>'

## the underlying @client differs as seen
irb(main):005:0> sentinel.instance_variable_get(:@client)
=> #<RedisClient redis://127.0.0.1:6480/0>
irb(main):006:0> redis.instance_variable_get(:@client)
=> #<Redis::Client redis://localhost:6379/0>
```

### Suggestions

We could expose the methods (`.host`, `.port`, `.path`, etc) on `RedisClient` like with `server_url` or fix the calls in this gem to try `.config.host` if `@client` is a `RedisClient`. wdyt?

The former would benefit other dependent gems like https://github.com/redis-store/redis-store/issues/370 which also has a similar issue when a sentinel set-up is configured.

Happy to help submit a PR on `redis-rb/redis-client` if you are at capacity!

**Comment by byroot** [comment]
> Happy to help submit a PR on `redis-rb/redis-client` if you are at capacity!

That would be very welcome yeah, I'm a bit swamped these days.

**Comment by byroot** [comment]
Ok, we can consider this fixed in https://github.com/redis-rb/redis-client/pull/144, could be good to bump the redis-client version in redis-rb though.
