### ISSUE TITLE
redis-client requires Redis 6+ with HELLO command available

### ISSUE THREAD

**Issue by bhaskar-f22** [redis/redis-rb#1233]
Hello,

I am seeing redis upto  [redis 5.0.8](https://rubygems.org/gems/redis), but app requires minimum Redis 6+ .

Can any one tell me ETA for this or any patch I can go with.

**Comment by byroot** [comment]
Your question isn't clear. 

The `redis` gem has no particular Redis server requirement.

**Comment by zegal1974** [comment]
When using redis-client connect redis server, the error message "redis-client requires Redis 6+ with HELLO command available" is displayed. 
class RedisClient  connect() method：raise UnsupportedServer Exception.
The server returned an error message：ERR unknown command `hello`

What should I do if my Redis Server cannot be upgraded to 6+ temporarily?
