### ISSUE TITLE
LMPOP not working

### ISSUE THREAD

**Issue by CoderMiguel** [redis/redis-rb#1237]
I am working with Redis to build some queues and would like to have a primary and secondary queue / lists.  LMPOP feels like the right method to be using to get values from the primary list first and the secondary only providing values when the primary list is exhausted.

If I build 2 lists as follows:

```ruby
redis = Redis.new
redis.rpush(:numbers, [*1..5])
redis.rpush(:letters, [*'a'..'e'])
```

I am able to verify that they have been populated:
```ruby
redis.lrange(:numbers, 0, -1) # => ["1", "2", "3", "4", "5"]
redis.lrange(:letters, 0, -1) # => ["a", "b", "c", "d", "e"]
```

I expect to get '1' if I were to `lmpop` from these lists as follows:
```ruby
redis.lmpop(:numbers, :letters)
```
Instead I get the following error:
```console
Redis::CommandError: ERR unknown command `lmpop`, with args beginning with: `2`, `numbers`, `letters`, `LEFT`, 
from /usr/local/bundle/gems/redis-client-0.18.0/lib/redis_client/connection_mixin.rb:35:in `call'
Caused by RedisClient::CommandError: ERR unknown command `lmpop`, with args beginning with: `2`, `numbers`, `letters`, `LEFT`, 
from /usr/local/bundle/gems/redis-client-0.18.0/lib/redis_client/connection_mixin.rb:35:in `call'
```

I am using:
Using rails 7.0.7.2
Using redis 5.0.8
Using redis-client 0.18.0

I was able to find this open issue: https://github.com/redis/redis-rb/issues/1187
but it appears that the code for LMPOP and BLMPOP have both been merged and are in the version of the gem that I am using: https://github.com/redis/redis-rb/blob/2b183addb9175641a48e1d8616772282a31c0532/lib/redis/commands/lists.rb#L231

So it feels like these methods should be accessible and working, but maybe they are still in development and we would need to find a workaround until they are finished?

**Comment by CoderMiguel** [comment]
Possible workaround:
```ruby
redis.lpop(:numbers) || redis.lpop(:letters)
```

**Comment by byroot** [comment]
What's your redis server version?

You can check it with `redis.info["redis_version"]`

**Comment by CoderMiguel** [comment]
redis.info["redis_version"] # => "6.2.6"

**Comment by byroot** [comment]
LMPOP was added in 7.0, your Redis server is too old: https://redis.io/commands/lmpop/

**Comment by CoderMiguel** [comment]
Thanks for pointing me to the problem, I was able to update the Redis server and this started working.
