### ISSUE TITLE
Sentinel TLS: Sentinel TLS not supported

### ISSUE THREAD

**Issue by garry-t** [redis/redis-rb#1249]
Am I correctly understood that no possible connect to sentinel via TLS?

**Comment by byroot** [comment]
I'm not aware of any such limitation.

**Comment by garry-t** [comment]
@byroot perfect point me in Readme.md how to configure in case Sentinel configured TLS.

**Comment by jlledom** [comment]
I would say TLS for sentinels is actually not supported. I wrote this script to test it:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem 'redis'
  gem 'hiredis-client'
end

def main
  config = {
    url: 'rediss://redis-master',
    name: 'redis-master',
    sentinels: [
      { host: 'localhost', port: 56380},
      { host: 'localhost', port: 56381},
      { host: 'localhost', port: 56382}
    ],
    ssl_params: {
      ca_file: '/path/to/ca-root-cert.pem'
    }
  }
  client = Redis.new(config)

  while true
    begin
      sleep 1
      result = client.ping
      puts result
    rescue StandardError => e
      puts e.message
      retry
    end
  end
end

main

```

Sentinels are launched in container following [this configuration](https://gist.github.com/jlledom/3e99def1dc38cbc4cb92f6619bd613f9).

I fails with the error: `No sentinels available`. Am I missing something?

**Comment by garry-t** [comment]
@jlledom it was also quite tricky for me. The doc doesn't show you exact example how to do it. You need to add param  
`ssl => true`. 

```ruby
sentinel_options = {
    name: 'master-name',
    sentinels: sentinel_addresses,
    role: :master,
    password: pass,
    sentinel_password: pass,
    :ssl => true
  }
sentinel_options[:ssl_params] = ssl_params if use_ssl
sentinel = Redis.new(sentinel_options)
```
hope it will help you.

**Comment by jlledom** [comment]
@garry-t that worked for me, thanks!

**Comment by stanhu** [comment]
I think https://github.com/redis-rb/redis-client/pull/277 should avoid the need to add `ssl: true` if you have `rediss://` in the URL.
