### ISSUE TITLE
redis-clustering: NoMethodError: undefined method `node_keys' for nil:NilClass

### ISSUE THREAD

**Issue by ccutrer** [redis/redis-rb#1282]
With [a recent redis-cluster-client commit](https://github.com/redis-rb/redis-cluster-client/commit/c1b7dd7cd135aad86355c817f8c0a1d3bdb5ee07), `@router` can be `nil`, so https://github.com/redis/redis-rb/blob/v5.2.0/cluster/lib/redis/cluster/client.rb#L56 is failing. 

```
#<NoMethodError: undefined method `node_keys' for nil:NilClass

        @router.node_keys.join(' ')
               ^^^^^^^^^^>
/var/web/canvas/shared/bundle/ruby/3.1.0/gems/redis-clustering-5.2.0/lib/redis/cluster/client.rb:56:in `id'
/var/web/canvas/shared/bundle/ruby/3.1.0/gems/redis-5.2.0/lib/redis.rb:111:in `id'
/var/web/canvas/shared/bundle/ruby/3.1.0/gems/redis-5.2.0/lib/redis.rb:115:in `inspect'
(irb):8:in `<top (required)>'
```
is a full backtrace.

Note that in [redis-cluster-client's inspect method](https://github.com/redis-rb/redis-cluster-client/commit/c1b7dd7cd135aad86355c817f8c0a1d3bdb5ee07#diff-737532d46e36c72be00bbbbce4de81b98dc9cdd82466bd1a0b6058b9c77f8da0R28), it checks if `@router` is `nil` before using it now.

**Comment by supercaracal** [comment]
Sorry, I'll fix it ASAP.
