### ISSUE TITLE
Use of RedisClient built-in connection pool

### ISSUE THREAD

**Issue by Juanmcuello** [redis/redis-rb#1284]
As far as I understand, RedisClient has a [built-in](https://github.com/redis-rb/redis-client?tab=readme-ov-file#usage) connection pool, so I'm wondering if it's possible to use it instead of the ConnectionPool gem [suggested](https://github.com/redis/redis-rb?tab=readme-ov-file#connection-pooling-and-thread-safety) in the README.

**Comment by byroot** [comment]
redis-client uses the `connection_pool` gem: https://github.com/redis-rb/redis-client/blob/6d55f61cac62af91aebbd5a1d00eae7a8d940b9e/redis-client.gemspec#L31.

**Comment by techiespace** [comment]
@byroot Could you please help me understand this better?

I noticed that the redis gem is using the redis-client, and redis-client uses connection pooling. Does this mean that the redis gem is indirectly using connection pooling? If so, is the README out of date, and does the redis gem now support connection pooling?

I would appreciate any clarification you can provide. Thank you!

**Comment by byroot** [comment]
> Does this mean that the redis gem is indirectly using connection pooling?

No. `redis-client` has a way to pool connection, but the `redis-rb` interface doesn't allow to use it.

It's theoretically possible to refactor `redis-rb` to use a pool under the hood, but it would likely break quite a lot of code, so I'm not very kin on doing it.
