### ISSUE TITLE
Support for RESP3 / protocol 3

### ISSUE THREAD

**Issue by veesahni** [redis/redis-rb#1297]
Does redis-rb support RESP3 / protocol 3?

**Comment by byroot** [comment]
Yes and no. You can instruct it to use the RESP3 protocol via `Redis.new(protocol: 3)` and it will work for some commands, but any command that return new RESP3 type may be broken.

If you are interested in RESP3 you are better off with `redis-client` directly: https://github.com/redis-rb/redis-client
