### ISSUE TITLE
read_timeout vs write_timeout: Unexpected Redis::TimeoutError with introduced latency

### ISSUE THREAD

**Issue by agrajgarg1526** [redis/redis-rb#1303]
I was under the impression that:

**read_timeout**: This specifies the maximum time the client will wait for a response from the Redis server after sending a command. Basically, used for read commands
**write_timeout**: This indicates the maximum time the client will wait for the server to acknowledge that data has been written. Basically, used for write commands

However, when I tested these timeouts by introducing latency using Toxiproxy, I observed unexpected behavior. In a Redis cluster with the following settings:

read_timeout: 0.1s
write_timeout: 5s
I introduced a latency of 0.2s, but both SET and GET commands failed with a Redis::TimeoutError, even though the write_timeout is set to 5 seconds.

Can someone help explain why both read and write operations failed despite the configured timeouts?

**Comment by byroot** [comment]
Both `SET` and `GET` command have to write a command and then read the response. 

So:

> read_timeout:  ... Basically, used for read commands
> write_timeout: ...  used for write commands

Is just wrong. Both apply to all commands.
