### ISSUE TITLE
Document Redis::Distributed

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#219]
I can't find any documentation on how to spread my Redis load across many different machines / redis instances.  A wiki page or readme entry would go a long way to help.

**Comment by drandahl** [comment]
Just bumping this thread. Anyone whether Redis::Distributed will at least be supported moving forward?

**Comment by yaauie** [comment]
@drandahl: if you'd like to see a solution, and to see it supported, you're more than welcome to contribute improvements. This project is run entirely by volunteers, and the to-do list is entirely driven by those who have the time & energy to make this project suit their needs.

**Comment by djanowski** [comment]
@drandahl The plan is to move Redis::Distributed to a separate gem for 4.0. I'll probably do the split but I'll look for people who want to take up the maintainer role.
