### ISSUE TITLE
CommandHelper encoding problem

### ISSUE THREAD

**Issue by unnu** [redis/redis-rb#348]
Saving mixed encoded key value pairs is actually not possible. Shouldn't the commands be converted to bytes before they get joined in the method `build_command`?

``` ruby
command.join(COMMAND_DELIMITER)
```

Following you find an example of the problem. Note that the strings could not be converted to either the one or the other encoding.

``` ruby
$ irb
irb(main):001:0> require "redis"
=> true
irb(main):002:0> include Redis::Connection::CommandHelper
=> Object
irb(main):003:0> build_command(["\u00E4", "\x80".force_encoding("ASCII-8BIT")])
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
    from /Users/unnu/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/redis-3.0.3/lib/redis/connection/command_helper.rb:28:in `join'
    from /Users/unnu/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/redis-3.0.3/lib/redis/connection/command_helper.rb:28:in `build_command'
    from (irb):3
    from /Users/unnu/.rbenv/versions/1.9.3-p327/bin/irb:12:in `<main>'
```

**Comment by andywatts** [comment]
As per Pietern's answer...this code works nice for getting binary strings....

`    with_external_encoding("ASCII-8BIT") do
        str = $redis.get("myBinaryString")
        logger.info str.encoding
        logger.info str.valid_encoding?
    end

    def with_external_encoding(encoding)
        original_encoding = Encoding.default_external
        begin
            #silent { Encoding.default_external = Encoding.find(encoding) }
            Encoding.default_external = Encoding.find(encoding)
            yield
        ensure
            #silent { Encoding.default_external = original_encoding }
            Encoding.default_external = original_encoding
        end
    end


    def silent
        verbose, $VERBOSE = $VERBOSE, false
        begin
            yield
        ensure
            $VERBOSE = verbose
        end
    end`
