### ISSUE TITLE
Redis::CommandError (ERR wrong number of arguments for 'sadd' command)

### ISSUE THREAD

**Issue by jfabre** [redis/redis-rb#349]
I keep receiving this error while adding values to a set.

redis (3.0.4)
redis-objects (0.7.0)
  redis (>= 3.0.2)

I googled a bit and it seems to be an incompatibility issue, but I updated the server and it is still not working.

Redis 2.6.14 (00000000/0) 64 bit
Darwin 12.4.0 x86_64

Any idea?

Thanks!

**Comment by mllanes** [comment]
Agree that output message should be more intuitive
