### ISSUE TITLE
wait until redis loads data into memory?

### ISSUE THREAD

**Issue by gingerlime** [redis/redis-rb#350]
I already [posted this](https://github.com/nevans/resque-pool/issues/76) on one of the downstream projects using redis-rb (resque-pool), but I'm wondering if redis-rb is the right place for this.

Currently, when redis loads data into memory, and you try to fetch anything from redis, redis-rb throws a `CommandError`. However, this is not really an error. Redis simply tells us to wait until data is loaded, or retry shortly, instead of holding the request until data is there and then returning it (which probably most data stores would typically do).

```
[6] pry(main)> redis = Redis.connect 
[7] pry(main)> redis.get "some-key"
Redis::CommandError: LOADING Redis is loading the dataset in memory
from /root/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/redis-rb-5fb35b85c048/lib/redis/client.rb:85:in `call'
```

Perhaps it makes more sense for this to be decided by the applications that are using redis-rb. I still wonder where this belongs to. It could be really useful to implement a retry mechanism (by default or as an option) in redis-rb, so commands that _could_ get successfully executed later would be kept waiting (at least until some kind of a timeout is reached), instead of throwing a command error? Something similar to the way redis-rb will wait to connect the socket, and timeout after a while if it can't connect.

**Comment by tamaloa** [comment]
If you need a one-liner (for instance for capistrano run) this worked well for me
```bash
until [ `redis-cli ping | grep -c PONG` = 1 ]; do echo "Waiting 1s for Redis to load"; sleep 1; done
```
