### ISSUE TITLE
Redis::InheritedError on Puma restart

### ISSUE THREAD

**Issue by swoker** [redis/redis-rb#366]
I get a Redis::InheritedError  _(Tried to use a connection from a child process without reconnecting. You need to reconnect to Redis after forking.)_ for the first request after restarting my puma (with SIGUSR2). 
The problem disappears with the second request however.

How can I fix this so Redis reconnects correctly?

This is my code:

```
# initializer
$redis = Redis.new(:host => 'localhost', :port => 6379)

# puma.rb
on_restart do 
  $redis.client.reconnect
end
on_worker_boot do
  $redis.client.reconnect
end
```

**Comment by stereobooster** [comment]
```ruby
# initializer
$redis = Redis.new(:host => 'localhost', :port => 6379)

# puma.rb
on_restart do 
  $redis.client.reconnect
end
on_worker_boot do
  $redis.client.reconnect
end
```

Is this thread-safe code anyway? I'm under impression that this code should use `connection_pool`. Also I suppose `Redis.current` isn't thread safe. Would be nice to have example of puma setup in repo, the same way there is unicorn example.
