### ISSUE TITLE
$redis.psubscribe wildcards?

### ISSUE THREAD

**Issue by fredkelly** [redis/redis-rb#367]
I may be going about this in the wrong way, but I'm trying to do the following:

``` ruby
$redis.psubscribe('update.*') do |on|
  # do something..
end
```

...and then from various places:

``` ruby
# myclass1.rb
$redis.publish('update.myclass1', @something)
# myclass2.rb
$redis.publish('update.myclass2', @something_else)
# etc..
```

Currently, the subscribe doesn't pick these up using a wildcard, only working if I explicitly specify the name - is there a way to use a wildcard in this manor?

**Comment by bobzhen** [comment]
Thank you!
