### ISSUE TITLE
Encoding issue with data from Redis

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#421]
See https://github.com/mperham/sidekiq/issues/1597 for backstory.

The suspicious code IMO is in [command_helper.rb](https://github.com/redis/redis-rb/blob/master/lib/redis/connection/command_helper.rb#L35).  What is the purpose of force_encoding here?  Is this a matter of data going into Redis in a bad format and throwing an error when it comes out, due to this force_encoding call?

**Comment by byroot** [comment]
This should be solved in 5.0 (to be released soon). `redis-client` assumes UTF-8 first, but check for validity, and return `Encoding::BINARY` strings otherwise.
