### ISSUE TITLE
Provide separate connection timeout and response timeout options

### ISSUE THREAD

**Issue by mfischer-zd** [redis/redis-rb#437]
Currently the `:timeout` option to the Redis constructor applies a latency ceiling both to the initial connection to the Redis server and to any responses to requests.  This means you can't easily fail a connection within 1ms but fail a response (assuming the client successfully connected) that takes longer than 300ms.

Also, the error message is always `Redis::TimeoutError: Connection timed out`, even if the client successfully connected and the response timed out.  This is highly misleading.

**Comment by plashchynski** [comment]
If there is `:connect_timeout`, so not obvious the meaning of `:timeout`, isn't it?

**Comment by mperham** [comment]
I'd love to see:

1. timeout deprecated and replaced with `read_timeout`, the same term as used by Net::HTTP.
2. the README updated to document the timeout options.

I will do this soon unless a committer objects.

**Comment by byroot** [comment]
This has been solved for a while.
