### ISSUE TITLE
Client#Disconnect not working properly on linux

### ISSUE THREAD

**Issue by ThomasAlxDmy** [redis/redis-rb#466]
Hey there!

I spent the last 3 days diving into the code trying to figure out the following issue.
Scenario:
- A redis client issuing a #blpop on a key, basically waiting to get data. 
- A little bit after another Thread decides to close the client connection. 

Expected result:
- The blpop raise an exception (Redis::TimeoutError) and returns 

Current result on Mac os X:
- The blpop raise an exception (Redis::TimeoutError) and returns 

Current result on Linux(Ubuntu 1304):
- The blpop never returns, program looks stuck

After diving really deeply into it here's what I found:
On Linux the code is blocked on IO.select: https://github.com/redis/redis-rb/blob/master/lib/redis/connection/ruby.rb#L52 and never returns, because if a file descriptor being monitored by select() is closed in another thread, the result is UNSPECIFIED (more information on a SOF I found: http://stackoverflow.com/questions/16637086/linux-cancel-blocking-read).

Because I hate doing things half way, I have the fix, PR coming up...

**Comment by djanowski** [comment]
Closing until we hear compelling reasons to merge. Thanks.
