### ISSUE TITLE
HGETALL returns array instead of hash

### ISSUE THREAD

**Issue by jamesfzhang** [redis/redis-rb#469]
`hgetall` is supposed to return a hash as shown by this [spec](https://github.com/redis/redis-rb/blob/7c4a95413009cefa0c74d8d320f1ae90a1c953c2/test/lint/hashes.rb#L92). However, I am seeing this behavior:

![screen shot 2014-09-17 at 1 44 52 pm](https://cloud.githubusercontent.com/assets/2057670/4308410/98b994c6-3e92-11e4-8993-28625d849e10.png)

redis: stable 2.8.11
redis-rb: 3.0.7
ruby: 2.1.2

**Comment by raphaottoni** [comment]
I am experiencing the same problem when using wolverine gem to call a lua script.
