### ISSUE TITLE
Connection to a remote redis way too slow

### ISSUE THREAD

**Issue by AlexCppns** [redis/redis-rb#495]
So far it seems to be doing one request per 'sadd' command, with 3000 entries it takes at least 5 minutes to perform an action. Is there a way to send a batch of sadd commands at once?

**Comment by yaauie** [comment]
There are a couple approaches, which can be combined to improve things:

Let's take the following (contrived) example, and refactor it:

~~~ ruby
redis = Redis.new

redis.sadd('fruit', 'apple') # => 1
redis.sadd('fruit', 'banana') # => 1
redis.sadd('fruit', 'grape') # => 1

redis.smembers('fruit') #=> ["grape", "apple", "banana"]
~~~

First, the `sadd` command takes multiple arguments, in the form of an array, so this could be :

~~~ ruby
redis = Redis.new

redis.sadd('fruit', ['apple', 'banana', 'grape']) #=> 3
redis.smembers('fruit') #=> ["apple", "grape", "banana"]
~~~

This gem also provides the ability to pipeline commands together, and not just `SADD`. Essentially right now your code is waiting for the response of each command before issuing the next command; when you have network latency, this can really slow things down. Pipelining allows us to issue many commands on a single connection, then resolve their results once we're done issuing commands:

~~~ ruby
redis = Redis.new

results = redis.pipelined do |pipeline|
  pipeline.sadd('fruit', 'banana')
  pipeline.sadd('fruit', 'orange')
  pipeline.sadd('fruit', 'apple')
end
results #=> [1,1,1]
redis.smembers('fruit') #=> ["apple", "grape", "banana"]
~~~

**Comment by AlexCppns** [comment]
The pipeline command didn't work for us (at least the improvement was not significant enough) but the array did solve our problem.
