### ISSUE TITLE
Sentinel connection with Hiredis driver

### ISSUE THREAD

**Issue by sixfeetover** [redis/redis-rb#503]
If you attempt to connect to Redis using Sentinel and the hiredis driver, the connection fails. To reproduce, simply modify examples/sentinel.rb to require hiredis and re-run, e.g.:

```ruby
require 'redis' # Version 3.2
require 'redis/connection/hiredis'
require 'hiredis'


Sentinels = [{:host => "127.0.0.1", :port => 26379},
             {:host => "127.0.0.1", :port => 26380}]
r = Redis.new(:url => "redis://master1", :sentinels => Sentinels, :role => :master)

r.keys
```

Results in

```
.../redis-3.2.0/lib/redis/connection/hiredis.rb:16:in `connect': undefined method `*' for nil:NilClass (NoMethodError)
```

This is coming from https://github.com/redis/redis-rb/blob/master/lib/redis/connection/hiredis.rb#L16 - the `connect_timeout` option is not being passed along (even if it is specified in `Redis.new`).

/cc @badboy

**Comment by badboy** [comment]
Ok, just took a look at the problem. I think we need to cleanup a bit how we pass options around. Right now [we pass only server and port](https://github.com/redis/redis-rb//blob/master/lib/redis/client.rb#L322), which is clearly wrong (also we don't make sure port is a Integer, which will break hiredis)

**Comment by badboy** [comment]
I pushed a change here: https://github.com/badboy/redis-rb/commit/fa1abe727712f2efcbebd38f56bd28233f2b6088
I'm not sure if we really need all the `dup`s. And I'll add a regression test for the behaviour before sending a PR.

**Comment by sixfeetover** [comment]
Awesome, thanks for looking at this so quickly! I'm heading out for the day but will test your changes tomorrow.

**Comment by badboy** [comment]
Oops, the first commit broke the tests. Make sure to test on the `iss503-fix` with all 3 commits. 
I'm not too happy with this yet, we still have a hardcoded (rather short) timeout in there and quite a lof of complexity just to figuring out wether to use a Sentinel, fetch a node or just connect directly.

**Comment by sixfeetover** [comment]
Alright, just tested this. We are getting closer - the original error is gone, but now there are errors if you try to set `password` or `db`. It fails trying to execute the `auth` or `select` commands: https://github.com/badboy/redis-rb/blob/iss503-fix/lib/redis/client.rb#L95-L96. The error returned is: `Redis::CommandError - ERR unknown command 'select'` (same for `auth`).

**Comment by badboy** [comment]
Ah, yes. Gnaaah. I'll think of a better solution.

**Comment by badboy** [comment]
@djanowski Need your input on this. How should we handle options for the sentinel connections? Just passing on the same options as given to `Redis.new` (minus things like db, pass, sentinels, etc) or should we let the user pass different options here? What about the short `timeout` we currently use when contacting Sentinels?

**Comment by badboy** [comment]
Going to work on a proper (first) fix tomorrow

**Comment by sixfeetover** [comment]
Sounds good, thanks for the update.

**Comment by djanowski** [comment]
Trying to add some tests to reproduce (also we were lacking Sentinel tests in general).

**Comment by djanowski** [comment]
See #505.

**Comment by ZhangHanDong** [comment]
The same problem for me

**Comment by djanowski** [comment]
Resolved by #505, will release soon.

**Comment by djanowski** [comment]
Included in 3.2.1.

**Comment by sixfeetover** [comment]
Thanks guys; I will try this out in my app tomorrow.

**Comment by ZhangHanDong** [comment]
@djanowski   thanks， good job

**Comment by sixfeetover** [comment]
One final update: This is working perfectly in production. Thanks again.
