### ISSUE TITLE
CLIENT SETNAME support

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#510]
I'd like to be able to pass in a String for the name of the Redis connection, per http://redis.io/commands/client-setname.  Many Sidekiq users are on Heroku with free Redis connection plans where their connections are quickly exhausted.  This would allow much easier connection count debugging if I can set names like "Sidekiq $PID".

I'd envision something like:

```ruby
Redis.new(:setname => "Sidekiq #{$$}")
```

**Comment by badboy** [comment]
Would be as easy as this: https://github.com/badboy/redis-rb/commit/83b0995ad1250135fda968f40e1335d2b038bab9

**Comment by djanowski** [comment]
What about reusing the `id` option we already have?

**Comment by amatriain** [comment]
I'm currently hurting from exhausted redis connections using sidekiq (with a max of 128 connections, not heroku). Being able to name client connections would be very useful to see if sidekiq is misbehaving or the connections come from somewhere else.

@badboy , I think you haven't submitted a PR with that commit, maybe things would move forward if you did?

**Comment by badboy** [comment]
I'll talk to djanowski how we proceed

**Comment by fedenusy** [comment]
+1, this would be helpful.

**Comment by djanowski** [comment]
This will be available soon in 3.2.2 (minor bump from current version).

**Comment by djanowski** [comment]
This is available in 3.2.2.
