### ISSUE TITLE
Rails app freeze in deadlock with global $redis and tubesock

### ISSUE THREAD

**Issue by nateless** [redis/redis-rb#511]
Spent whole day trying to figure out what's happening. We use Redis and initialize it at load in initialize file with global variable `$redis`. In controller we have something like this:

``` ruby
class StreamController < ApplicationController
    include Tubesock::Hijack

    respond_to :json

    def index
        hijack do |tubesock|
            tubesock.onopen do
                StreamService.add(current_user, tubesock)

                $redis.publish('online', {params: online}.to_json)
            end

            tubesock.onmessage do |data|
                #...
            end

            tubesock.onclose do
                $redis.publish('online', {params: online}.to_json)
            end
        end
    end

    private
    def online
        StreamService.size
    end
end
```

At random time app freeze, `strace` shows:

```
futex(0x7fc845d826a4, FUTEX_WAIT_PRIVATE, 1, NULL
```

I've added another thread at rails initialization which just dumps Threads.list with backtrace for each of them each second, after some load (just open a lot of connections to site) app freeze and this is what I have [I've removed irrelevant threads]:

```
I, [2015-02-11T20:23:01.618508 #6876]  INFO -- : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I, [2015-02-11T20:23:01.618533 #6876]  INFO -- : #<Thread:0x007f42108f3640>
I, [2015-02-11T20:23:01.620581 #6876]  INFO -- : #<Thread:0x007f421158ce60>
I, [2015-02-11T20:23:01.622522 #6876]  INFO -- : #<Thread:0x007f42112f5df0>
I, [2015-02-11T20:23:01.620616 #6876]  INFO -- : /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:185:in `lock'
I, [2015-02-11T20:23:01.620641 #6876]  INFO -- : /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:185:in `mon_enter'
I, [2015-02-11T20:23:01.620663 #6876]  INFO -- : /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:209:in `mon_synchronize'
I, [2015-02-11T20:23:01.620683 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
I, [2015-02-11T20:23:01.620702 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:1994:in `publish'
I, [2015-02-11T20:23:01.620722 #6876]  INFO -- : /home/ubuntu/test/releases/20150211154256/app/controllers/stream_controller.rb:45:in `block (2 levels) in index'
I, [2015-02-11T20:23:01.620742 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:62:in `call'
I, [2015-02-11T20:23:01.620762 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:62:in `each'
I, [2015-02-11T20:23:01.620790 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:62:in `block in listen'
I, [2015-02-11T20:23:01.620839 #6876]  INFO -- : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I, [2015-02-11T20:23:01.622768 #6876]  INFO -- : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I, [2015-02-11T20:23:01.622787 #6876]  INFO -- : #<Thread:0x007f42112f77e0>
I, [2015-02-11T20:23:01.622827 #6876]  INFO -- : /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:185:in `lock'
I, [2015-02-11T20:23:01.622853 #6876]  INFO -- : /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:185:in `mon_enter'
I, [2015-02-11T20:23:01.622876 #6876]  INFO -- : /home/ubuntu/.rbenv/versions/2.2.0/lib/ruby/2.2.0/monitor.rb:209:in `mon_synchronize'
I, [2015-02-11T20:23:01.622933 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
I, [2015-02-11T20:23:01.622957 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:1994:in `publish'
I, [2015-02-11T20:23:01.622977 #6876]  INFO -- : /home/ubuntu/test/releases/20150211154256/app/controllers/stream_controller.rb:84:in `block (2 levels) in index'
I, [2015-02-11T20:23:01.623007 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:71:in `call'
I, [2015-02-11T20:23:01.623030 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:71:in `each'
I, [2015-02-11T20:23:01.623050 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:71:in `close'
I, [2015-02-11T20:23:01.623070 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:43:in `rescue in send_data'
I, [2015-02-11T20:23:01.623090 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:36:in `send_data'
I, [2015-02-11T20:23:01.623110 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:88:in `block (2 levels) in keepalive'
I, [2015-02-11T20:23:01.623131 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:86:in `loop'
I, [2015-02-11T20:23:01.623151 #6876]  INFO -- : /home/ubuntu/test/shared/bundle/ruby/2.2.0/bundler/gems/tubesock-f74c2bceb86a/lib/tubesock.rb:86:in `block in keepalive'
I, [2015-02-11T20:23:01.623172 #6876]  INFO -- : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

First backtraces `stream_controller.rb:45` refers to our line `$redis.publish` in `onopen` callback and second regarding `$redis.publish` in `onclose`.

I've tried to change onopen and onclose callbacks to this version:

``` ruby
            tubesock.onopen do
                StreamService.add(current_user, tubesock)

                redis = Redis.new(:driver => :hiredis)
                redis.publish('online', {params: online}.to_json)
            end
```

And at the moment it works fine, however the question is why it stuck in deadlock using global var?

**Comment by yaauie** [comment]
It looks like the tubesock plugin (with which I am unfamiliar) is attempting to share a single REDIS connection across multiple threads; in order to make the redis connection threadsafe, we use a mutex to ensure that only one thread is writing to (and processing responses from) the underlying socket at a time.

Your workaround works (at significantly higher overhead) by establishing a new redis connection for each publish command; since only one command is issued & processed on the connection, there is no lock contention.

Worth noting, redis pubsub commands like `subscribe` will acquire a lock on a connection and never release it (by design), so it is possible that a portion of your code that you thought irrelevant is actually monopolising the global connection.

**Comment by nateless** [comment]
Well it's establishing new connections only on websocket initialization and not for each command. However I've got your point. 

I've checked tubesock gem, its almost one short file, all the work is in this method:
```ruby
def listen
    keepalive
    Thread.new do
      Thread.current.abort_on_exception = true
      @open_handlers.each(&:call)
      each_frame do |data|
        @message_handlers.each{|h| h.call(data) }
      end
      close
    end
  end
```

However it can throw an exception [tubesock rescue's a lot of them]. 
```ruby
def send_data data, type = :text
    frame = WebSocket::Frame::Outgoing::Server.new(
      version: @version,
      data: data,
      type: type
    )
    @socket.write frame.to_s
  rescue IOError, Errno::EPIPE, Errno::ETIMEDOUT
    close
  end
```
I think when I used global $redis, it throwed an websocket exception while code was in onopen\onclose callbacks, and redis got stuck in synchronize block. I haven't fully checked redis-rb code as it's much bigger than tubesock's but that's my guess. Also tubesock's owner closed my issue by linking it with not-threadsafe redis gem.

**Comment by yaauie** [comment]
Looking at Tubesock, it looks like it's not the problem and is fairly irrelevant to this issue; all the callbacks (at least in [current master](https://github.com/ngauthier/tubesock/blob/master/lib/tubesock.rb#L62)) occur outside of the bits that do exception handling (even if the `onclose` is triggered in response to tubesock losing its websocket connection, which appears to be the case for one of your stuck threads).

Is it possible that elsewhere in your application (perhaps in another thread) you're sending `subscribe` to the global `$redis` to consume the messages you're publishing here?

**Comment by nateless** [comment]
Nope, I'm getting another deadlocks even with those updates. I start a thread for each connected user. After few hours extensive use it also freeze. If I replace `$redis` with another thread connection everything is fine.

```ruby
	def index
		hijack do |tubesock|
			chat  = Thread.new do
				redis_chat = Redis.new(:driver => :hiredis)
				redis_chat.psubscribe 'message.*' do |on|
					on.pmessage do |_channel, message, data|
						# ....
						tubesock.send_data(data) if $redis.exists('some_key')
						# ....
					end
				end
			end
			# all the rest code
	end
```

**Comment by nateless** [comment]
Regarding tubesocks execution. When tubesock for one user process `onopen` callback it can be in `onclose` for another one. In both of them I use `send_data` for clients, thus `send_data` can trigger another `close` [call](https://github.com/ngauthier/tubesock/blob/master/lib/tubesock.rb#L43) even for the same client.

**Comment by byroot** [comment]
Each Redis client has a mutex to ensure commands happen sequentially. If you need to use blocking commands like subscribe & such, you should use another connection to the redis server for this.
