### ISSUE TITLE
Add `close` method

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#516]
Is it possible to get a close method which just shuts down the socket?  I see there's a `quit` method which round trips to Redis.

```ruby
r = Redis.new
r.close
```

This is for the connection pool when it wants to discard a connection due to suspected socket corruption.

**Comment by djanowski** [comment]
`Redis#disconnect!` it is. See #506.

**Comment by mperham** [comment]
I still wish you aliased this to `close`.  If all network clients used `close`, we could have a de-facto standard and not require customization per client, e.g. Dalli uses `close`.

https://github.com/mperham/dalli/blob/master/lib/dalli/client.rb#L235
