### ISSUE TITLE
Explanation 

### ISSUE THREAD

**Issue by zotherstupidguy** [redis/redis-rb#518]
in redis-rb/lib/redis/client.rb

Marshal.load(Marshal.dump(@options))                                                                

what does this line do? and isn't this as effective as simply returning @options ?

**Comment by badboy** [comment]
It's effectively a deep clone of options. A `.dup` would only duplicate the top-level array, but we want a complete new clone of the nested options.

**Comment by zotherstupidguy** [comment]
Thanks @badboy  I think this should be closed!
