### ISSUE TITLE
brpop character encoding problem Encoding::InvalidByteSequenceError

### ISSUE THREAD

**Issue by shine60vn** [redis/redis-rb#520]
Hi guys,
I stored a Thai string (with utf-8 encoding) in a list and get it by using brpop(). In redis-cli brpop worked fine but I recieved an Encoding::InvalidByteSequenceError with the message is ""\xE0" on US-ASCII'  in my application. I failed to find out the solution for this problem. Can anybody help me please!

**Comment by badboy** [comment]
Where was this error raised? in `redis-rb` code or in your code trying to interact with a returned value?
What's the encoding of your environment?

In general neither Redis nor `redis-rb` know anything about encodings, they just handle everything as byte strings. It's up to your application to give the bytes meaning by interpreting it using the right encoding.

**Comment by shine60vn** [comment]
@badboy thanks for your quick reply!
The error raised in redis-rb code "redis.brpop('key')". In my local machine (Ubuntu), everything is ok, this problem occur on production environment (Redis 2.6.x on Amazon Linux). Is there any way to check redis-rb work fine with encoding (I used redis-rb 3.1.0). Thanks!

**Comment by badboy** [comment]
Without seeing any code it's hard to help you. As I said, redis-rb doesn't touch the encoding. 

What's the default external and internal encoding on the production machine?
Can you maybe just set the encoding explicitly?

**Comment by shine60vn** [comment]
I'm so sorry I can't reply you last weekend!
This is my code for brpop calling, check it please:
```ruby
def brpop
    JSON.parse(self.queue.brpop(BannerProcessor.config['redis']['process']).last)
end
      
# Caches a connection
def queue
    @queue ||= queue!
end 
      
# Always returns a new connection
def queue!
    Redis.new :host      => BannerProcessor.config['redis']['host'], 
                 :port      => BannerProcessor.config['redis']['port'], 
                 :password  => BannerProcessor.config['redis']['password']
end
```
I didn't set explicitly encoding, everything is default. How can I check "default external and internal encoding" on the production machine?

**Comment by badboy** [comment]
```ruby
Encoding.default_external
Encoding.default_internal
```

Compare to the output of the machine, where it is working. 
I assume the `JSON.parse` fails and _not_ the actual `self.queue.brpop` call?

**Comment by shine60vn** [comment]
Hi @badboy , thanks for your advice!
In my app, Encoding.default_external is Encoding::US_ASCII and I also found the error raised at
```
.rvm/gems/ruby-2.1.5/gems/redis-3.1.0/lib/redis/connection/command_helper.rb line 35
```
```ruby
if defined?(Encoding::default_external)
    def encode(string)
      string.force_encoding(Encoding::default_external)
    end
else
    def encode(string)
      string
    end
end
```
I have solved this problem, I will close this issue. Again, thanks @badboy

**Comment by badboy** [comment]
Oh, I'm sorry. My quick grepping through the source turned out to be false, so yes, the Ruby adapter relies on `default_external` and thus affects encoding.
Glad you could fix this issue.
