### ISSUE TITLE
Options need to be documented

### ISSUE THREAD

**Issue by nileshtrivedi** [redis/redis-rb#522]
We should document the options. In particular, i couldn't find the following information easily:

- How do `timeout`, `connect_timeout`, `tcp_keepalive`, `reconnect_attempts`, and `inherit_socket` work?
- What are the units for `timeout`, `connect_timeout` and `tcp_keepalive`? Minutes? Seconds? Miliseconds?
- What are the difference between different values for `driver`?

I personally would prefer these details either in the README or in the code itself. Wiki is the last place I look for such basic information.

**Comment by badboy** [comment]
There's a first step already done in #514, does this already help?
I'm in favour of documenting all this properly, I just hadn't had the time to work on it

**Comment by nileshtrivedi** [comment]
Yes, that commit was helpful. Thank you.
