### ISSUE TITLE
Client no longer accepts URIs with http as their scheme rather than redis

### ISSUE THREAD

**Issue by carols10cents** [redis/redis-rb#523]
As of d71bff38b3e90bb4bc4e5bc4817b1eb2927738db, the client will now throw an exception if the URI's scheme is `http`; changing the URI's scheme to `redis` works as expected.

Was it ever valid to specify a redis URI as something like `http://localhost:6380`? Or were we relying on accidentally supported behavior?

If `http` is supposed to be valid, I'm more than happy to submit a pull request changing the relevant conditional `elsif uri.scheme == "redis"` to include `|| uri.scheme == "http"` and adding some tests, but I wanted to see what the intended behavior was before submitting.

Thanks!!! :heart:

**Comment by yaauie** [comment]
Nope :smile: redis has always been the only acceptable scheme, as we use the redis protocol, and other schemes have always been invalid, if silently ignored. The change you noticed now enforces the url matching what we've long assumed.

**Comment by carols10cents** [comment]
Thank you for letting me know! We have updated our URLs to use `redis://` and all is well :) :sunglasses:
