### ISSUE TITLE
Feature request: When throwing a Timeout:Error, print the query too

### ISSUE THREAD

**Issue by nileshtrivedi** [redis/redis-rb#527]
I get random Timeout errors while connecting from my Rails app to Redis in AWS ElastiCache. It will make it a lot easier to debug if the exception message also contained the query which timed out. This way, I can be sure that the libraries I used are not doing a "SAVE" or "KEYS *".

**Comment by trantuantai** [comment]
@nileshtrivedi, to investigate your issue. It would be good, if you can provides more info from CloudWatch, such as:
- Were there high read/write throughputs when the timeout happened? 
- Is the number of ElastiCache connections normal?

**Comment by byroot** [comment]
I don't think that's necessary.
