### ISSUE TITLE
ZADD options are not supported

### ISSUE THREAD

**Issue by jcmfernandes** [redis/redis-rb#545]
While for instance method `set` supports all SET command options, method `zadd` doesn't offer support for any ZADD options (NX, XX, CH, INCR).

**Comment by jcmfernandes** [comment]
I'll be scratching my own itch here and hence opening a PR fixing this soon.

**Comment by yaauie** [comment]
Sweet. Feel free to tag me when you're ready, and I'll be glad to help fine-tune & get your PR merged :simple_smile:

**Comment by jcmfernandes** [comment]
Thanks @yaauie ! Tagging you on #547 :smile_cat:

**Comment by jcmfernandes** [comment]
Well, I cannot tag people in PRs but you know what to do! :)
