### ISSUE TITLE
Support for Redis Cluster (3.0)

### ISSUE THREAD

**Issue by iandyh** [redis/redis-rb#546]
Hi

Surprisingly, I haven't found too much information on the status of cluster support in Ruby client. I am aware of `redis-rb-cluster` from @antirez . But apparently, it's not production ready yet.

So any plans in `redis-rb`? Or when `redis-rb-cluster` can be merged into `redis-rb`?

**Comment by spuder** [comment]
I'm also finding that there is no documented way to follow ASK and MOVED redirections (`redis-cli -c`)

```
2.2.0 :014 > redis = Redis.new(:host => "10.10.10.10")
 => #<Redis client v3.2.1 for redis://10.10.10.10:6379/0> 
2.2.0 :015 > redis.get("foo")
Redis::CommandError: MOVED 12365 10.10.10.10:6379
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/redis-3.2.1/lib/redis/client.rb:113:in `call'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/redis-3.2.1/lib/redis.rb:789:in `block in get'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /Users/sowen/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/redis-3.2.1/lib/redis.rb:788:in `get'
	from (irb):15
	from /Users/sowen/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by iandyh** [comment]
@spuder The doc is here: http://redis.io/topics/cluster-spec. It explains how to handle the redirections.

**Comment by spuder** [comment]
Thanks. I've read that document twice and I'm not able to grok what needs to change. Is this a client side or server side configuration change?

**Comment by badboy** [comment]
The redirect needs to be handled on the client side.
redis-rb currently does no handling of Cluster, and thus also don't follows the redirect.
redis-rb-cluster is a reference implementation on top of the existing redis-rb, that you can use. 
Check [its code](https://github.com/antirez/redis-rb-cluster/blob/master/cluster.rb#L247) to see how it handles the redirect. 
It might need a bit more work, but it already handles most cases. I'm not sure it should actually end up in redis-rb, but that is up to the maintainers and/or contributors anyway.
If you want to see it get merged in or improve, you're invited to help as best as you can.

**Comment by iandyh** [comment]
@spuder You didn't pay too much attention to the "Redirection and resharding" section, did you? :) quote from the doc:

*A client must be also able to handle -ASK redirections that are described later in this document, otherwise it is not a complete Redis Cluster client.*

Anyway, if you want to play with the cluster, `redis-rb-cluster` is the best bet now. But for production, it still needs more work.

**Comment by spuder** [comment]
Thanks @iandyh

**Comment by danmaz74** [comment]
So basically there's still no production ready adapter for Ruby to use Redis cluster? I'm speechless.

**Comment by badboy** [comment]
Why speechless? This is a community-effort. We're not here to provide you with everything. You're very welcome to help out and improve stuff though.
Not everyone considers Cluster a priority, not everyone has the time and motivation to provide a production-ready client implementation.
Redis Cluster itself is still very new, there are probably not even that many companies out there using it in production yet. If anyone _is_ using Redis Cluster in production, I encourage those to contribute back what they found and built.

**Comment by danmaz74** [comment]
@badboy it wasn't against anybody in particular, but I was really frustrated (during an emergency) by the fact that it's impossible to reliably use Cluster from Ruby - even if the example client was written in Ruby.

Fortunately (for us) most of our Redis operations are done from Node.js; right now we're considering to actually move the few direct accesses we did from Ruby to Node (ie, Ruby will get the data from Node, not directly from Redis). But if we'll work directly inside Ruby and find anything useful, we'll for sure contribute back.

**Comment by agwozdowski** [comment]
:+1:

**Comment by raphi** [comment]
:+1:

**Comment by CloudMarc** [comment]
This from @antirez is super helpful:  https://github.com/antirez/redis-rb-cluster

But this really needs to be rolled into the redis-rb client.  redis-cluster cannot be said to be "production-ready" if there are no production-ready clients to support it.

**Comment by badboy** [comment]
@CloudMarc You are free to provide an implementation that satisfies your definition of "production-ready"

**Comment by iandyh** [comment]
@CloudMarc If you look at the pull requests for redis-rb-cluster, you can see one from me which is my effort to make the client production ready(and currently waiting for review). You can test that branch and provide feedback to me.

**Comment by danmaz74** [comment]
@badboy just noticed you closed this issue in march - but I don't see any mention of cluster support in the docs. Any news?

**Comment by badboy** [comment]
@danmaz74 No, there's no Cluster support in redis-rb and we do not have any plans to integrate it at the moment.

**Comment by danmaz74** [comment]
@badboy ok thanks for the update. Will have to continue with javascript then!

**Comment by skippy** [comment]
@badboy can we keep this open?  It is a part of the redis engine, and other drivers support it; this would be useful to track for driver parity, even if you don't plan on implementing it at the moment.

thanks!

**Comment by badboy** [comment]
There's no point in keeping this open. We do not have any plans to integrate it into redis-rb at this point.
If we ever plan with that, we might open a issue or PR. Until then we keep this closed.

**Comment by MatayoshiMariano** [comment]
@iandyh  This gem supports redirection https://github.com/inkel/redic-cluster
