### ISSUE TITLE
Add support for array of arguments to `pfcount`

### ISSUE THREAD

**Issue by ArunSakthivel** [redis/redis-rb#548]
I can't able to pass array of value as a argument to PFCOUNT.
https://github.com/antirez/redis-rb-cluster/issues/5

**Comment by badboy** [comment]
Use `r.pfcount("foo", "bar")` or `a = ["foo", "bar"]; r.pfcount(*a)`

**Comment by ArunSakthivel** [comment]
Thanks :+1:
