### ISSUE TITLE
Allow sentinel configuration to accept String URIs and not just a Hash

### ISSUE THREAD

**Issue by jcblitz** [redis/redis-rb#549]
A main Redis connection is flexible enough to accept a String URI and parse out the parameters, but the Sentinel configuration section is not, it only accepts a Hash. Please add in support from connection Strings. My use case is to make it easier to externalize those values as environment variables.

**Comment by marceloboeira** [comment]
It would make my life easier, currently I have to parse the ENV incoming variable from a service to extract in order to generate the hash.

**Comment by coleton** [comment]
This would be amazing, as I use a local Redis server for development and push to a sentinel cluster, having the config in the same ENV variable would save so much code!

Lettuce has implemented this in their client (https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/com/lambdaworks/redis/RedisURI.java)

**Comment by byroot** [comment]
fixed in #599

**Comment by byroot** [comment]
Nevermind, I misread.

**Comment by byroot** [comment]
That's is solved in 5.0
