### ISSUE TITLE
Interest in supporting AWS Elasticache replication group failover

### ISSUE THREAD

**Issue by craigmcnamara** [redis/redis-rb#550]
I made a gem here: https://github.com/craigmcnamara/redis-elasticache

I'd happily make it an optional addon to redis-rb if you'd accept a pull request.

**Comment by ndbroadbent** [comment]
Hi @craigmcnamara, thanks for working on this! I didn't realize I would need to do something extra to support ElastiCache failover. I have seen some ReadOnly errors in the past that this gem should fix, so I will try it out!

However, now I'm struggling with a different error during failover: https://github.com/redis/redis-rb/issues/949

Would the `redis-elasticache` addon also help with this?

Also, does `redis-elasticache` break a standard Redis installation? (e.g. during tests on CI, or for other deployments that don't use ElastiCache.) Do you think it is safe to always use `redis-elasticache`, or should I add a way to manually enable it when needed?

Thanks!

**Comment by ndbroadbent** [comment]
Ahh, I can see the code just checks for some error messages and changes the error class to force a reconnect: https://github.com/craigmcnamara/redis-elasticache/blob/master/lib/redis/elasticache/failover.rb

So it looks like this won't help with my current issue, but I'll definitely use this anyway! Thanks!

**Comment by uiur** [comment]
I was seeing a similar issue,
but I've found that current elasicache doesn't have this issue by default.

`close-on-replica-write` is enabled by default, and it disconnects connections with write command to replica automatically.

> If enabled, clients who attempt to write to a read-only replica will be disconnected. 

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ParameterGroups.Redis.html#ParameterGroups.Redis.2-8-23

**Comment by timanovsky** [comment]
> I was seeing a similar issue,
> but I've found that current elasicache doesn't have this issue by default.
> 
> `close-on-replica-write` is enabled by default, and it disconnects connections with write command to replica automatically.
> 
> > If enabled, clients who attempt to write to a read-only replica will be disconnected.
> 
> https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ParameterGroups.Redis.html#ParameterGroups.Redis.2-8-23

It may still be needed. Looks like LUA invocations are not handled properly and still fail with READONLY error
