### ISSUE TITLE
How to configure/instantiate Redis sentinel?

### ISSUE THREAD

**Issue by HenleyChiu** [redis/redis-rb#555]
In the Wiki, here is the code on instantiating a Redis sentinel instance:
redis = Redis.new(:url => "redis://mymaster", :sentinels => SENTINELS, :role => :master)

Question:
What should the url value be? "redis://mymaster"
What is mymaster here? Should it be the master name (same name we gave to it in /etc/redis/sentinel.conf)? the IP address of the master redis server? 

The reason I am asking is because I set it to the master name, and get this error when I try to set/get any value through redis:

```ruby
redis = Redis.new(:url => "redis://mymaster", :sentinels => SENTINELS, :role => :master)
redis.set("test", 1)

**ERROR:
SocketError: getaddrinfo: Name or service not known
	from /home/sshadmin/.rvm/gems/ruby-2.1.2/gems/redis-3.2.1/lib/redis/connection/ruby.rb:152:in `getaddrinfo'
```

The error is from this line: addrinfo = ::Socket.getaddrinfo(host, nil, Socket::AF_UNSPEC, Socket::SOCK_STREAM)

**Comment by badboy** [comment]
It should be the name given to the monitored instance in the Sentinel config.
What is in your `SENTINELS`? Looks like there you might have the wrong hostname used.

**Comment by HenleyChiu** [comment]
SENTINELS is:
[{ host: "192.168.1.101", port: 26379 }, { host: "192.168.1.102", port: 26379 }, { host: "192.168.1.103", port: 26379 }]

The code that is instantiating this redis object does not have Redis sentinel running, if that helps.

I'm also using:
Ruby 2.1.2

**Comment by badboy** [comment]
Do you have a full backtrace? It's not clear where this exception is coming from.

**Comment by richardhsu** [comment]
I'm getting a very similar error and have sentinels configured in the same manner, here is backtrace: @HenleyChiu did you figure it out?

```
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/connection/ruby.rb:152:in `getaddrinfo'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/connection/ruby.rb:152:in `connect'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/connection/ruby.rb:211:in `connect'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:316:in `establish_connection'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:91:in `block in connect'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:273:in `with_reconnect'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:90:in `connect'
......shared/bundle/ruby/2.2.0/gems/redis-sentinel-1.5.0/lib/redis-sentinel/client.rb:33:in `connect_with_sentinel'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:337:in `ensure_connected'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:204:in `block in process'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:286:in `logging'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:203:in `process'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis/client.rb:109:in `call'
......shared/bundle/ruby/2.2.0/gems/redis-sentinel-1.5.0/lib/redis-sentinel/client.rb:177:in `readonly_protection_with_timeout'
......shared/bundle/ruby/2.2.0/gems/redis-sentinel-1.5.0/lib/redis-sentinel/client.rb:134:in `call_with_readonly_protection'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:784:in `block in get'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `block in synchronize'
from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:37:in `synchronize'
......shared/bundle/ruby/2.2.0/gems/redis-3.2.0/lib/redis.rb:783:in `get'
```

**Comment by richardhsu** [comment]
Figured this out, apparently in `redis-sentinel` it is expecting a option named `master_name` so configuration becomes:

```ruby
redis = Redis.new(:url => "redis://mymaster", :master_name => "mymaster", :sentinels => SENTINELS, :role => :master)
redis.set("test", 1)
=> "OK"
```

**Comment by nikhilthombare** [comment]
/app/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/connection/ruby.rb:152:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
:from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/connection/ruby.rb:152:in `connect'
:from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/connection/ruby.rb:211:in `connect'
 :from /app/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:322:in `establish_connect



In my application Redis config and provide a path in the environment but still giving me an error on production
