### ISSUE TITLE
Connection using hiredis driver instead of ruby driver.

### ISSUE THREAD

**Issue by manojmj92** [redis/redis-rb#563]
I am connecting to redis via redis-rb in my project. But I can see that it is using hiredis driver instead of the default ruby driver. I am not passing :driver as an argument while creating the connection, nor have I installed hiredis gem. Why is this happening?

**Comment by badboy** [comment]
How do you "see" that it is using the hiredis driver then? It's impossible for redis-rb to just use code you never installed. Maybe you're requiring `redis/connection/hiredis` somewhere?
Also check again whether or not the hiredis gem is installed.

**Comment by manojmj** [comment]
I use $redis.connection.client to see it. No, my gemfile doesn't have hiredis. But my Gemfile.lock has hiredis.

**Comment by badboy** [comment]
There you go. The Gemfile.lock is the ultimate source of truth.

**Comment by manojmj** [comment]
Got it. We are using the redis-queue gem which is using hiredis. My bad.
