### ISSUE TITLE
the documentation for #multi method differs in README and rdoc/tests

### ISSUE THREAD

**Issue by yeonhoyoon** [redis/redis-rb#564]
Following is the documentation for #multi method in the README page.
```ruby
redis.multi do
  redis.set "foo", "bar"
  redis.incr "baz"
end
# => ["OK", 1]
```
however, the rdoc comments for the #multi method and the tests for #multi command both uses the following style, sending commands to the `multi` variable given in the block.
```ruby
redis.multi do |multi|
  multi.set "foo", "bar"
  multi.incr "baz"
end 
# => ["OK", 1]
```
Are the two styles functionally equivalent?

**Comment by badboy** [comment]
Fun fact: yes, they are, thanks to an ugly hack.
