### ISSUE TITLE
NilValue Error on `.dup`

### ISSUE THREAD

**Issue by rjrobinson** [redis/redis-rb#566]
Kind of found an odd error to track down. 

in the redis.rb file. 

Starting at line 49 

``` ruby
def initialize(options = {})
    @options = options.dup
    @original_client = @client = Client.new(options)

    super() # Monitor#initialize
  end
```

The .dup method throws a NilValue for dup error if there is not a redis.yml (rails app) that has the params that it is looking for. Though totally my error,  Would you be interested in having this raise a Undefined Environment error?

Though this was a minor error. It took considerable time for a few of us.

**Comment by uros93** [comment]
So how did you fix this?
