### ISSUE TITLE
undefined method `invoke_with_build_args' for nil:NilClass

### ISSUE THREAD

**Issue by wanzhou** [redis/redis-rb#573]
`gem install -l redis-3.2.2.gem`:
ERROR: Loading command: install (LoadError)
/home/test/tools/ruby/lib/ruby/2.0.0/x86_64-linux/openssl.so: undefined symbol: d2i_ECPKParameters - /home/test/tools/ruby/lib/ruby/2.0.0/x86_64-linux/openssl.so
ERROR: While executing gem ... (NoMethodError)
undefined method `invoke_with_build_args' for nil:NilClass

Why? Because of openssl.so?
I installed ruby by src in redhat 6, command:
`./config -prefix=/home/test/tools/ruby`
`make && make install`

After install, I run `ruby -v` and it works well.

**Comment by badboy** [comment]
Looks like your installed Ruby is broken. That's not a bug with redis-rb and this is not the place to fix it. 
Please try to get help with some Ruby support channel or just use your system's Ruby package.

**Comment by asdf2014** [comment]
@wanzhou @badboy I meet the same problem, should i reinstall ruby?
```bash
$ gem install -l redis-3.2.2.gem

ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

**Comment by badboy** [comment]
Yes, and you are missing zlib

**Comment by asdf2014** [comment]
@badboy Thx for your comment. You are right. Already fix it.

**Comment by anupt3389** [comment]
how did you fix it.
I am facing same problem.

**Comment by byroot** [comment]
You need to get the `zlib` package installed and then reinstall ruby. But that's very dependent on your system so here is not really the proper place.
