### ISSUE TITLE
NX argument in ZAdd not working

### ISSUE THREAD

**Issue by mingyeow** [redis/redis-rb#584]
I am trying to use the NX argument in the ruby gem, but it does not seem to work. Using it in the Redis CLI seems to work fine.

    // NX argument in cli works
    127.0.0.1:6379> ZADD myzset NX 2 "two " 3 "three" 
    (integer) 1

    // Works without NX
    irb(main):030:0* RClient.zadd("ss",[[5,"two"],[3,"three"]])

    // NX command in ruby does not work
    irb(main):027:0* RClient.zadd("ss",[[5,"two"],[3,"three"]],{:nx=>true})
    Redis::CommandError: ERR syntax error

    // i am running 3.0.5
    irb(main):011:0> RClient.info
    => {"redis_version"=>"3.0.5"...

If I cannot do this here, possible to simply call the command directly?

**Comment by badboy** [comment]
Works for me. Do you have the latest `redis-rb` gem installed?
