### ISSUE TITLE
A Redis class is being added to every namespace in the app

### ISSUE THREAD

**Issue by rbishop** [redis/redis-rb#587]
While writing a configurable Storage backend for an app that happened to have a class inside the namespace named `Redis` I encountered a failing initialization. Upon looking into it further it seems the `initialize` method was expecting a hash rather than what my class needed (a String).

Looking into this more I realized what was actually happening is my classes initializer was not a `MyCoolApp::Storage::Redis` initializer but rather a `Redis` initializer. And then for more curiosity I decided to try the same thing with all the other namespaces in my app. `SomeImportantModel::Redis.new(host: ..., port: ...)` and even `String::Redis.new` all work. What gives?

**Comment by badboy** [comment]
Welcome to the wonderful world of constant lookups in Ruby.

> When you write `Foo::Bar` in Ruby, it does not mean `Bar` within namespace `Foo`, but rather `Bar` as “seen” from `Foo`

Even `String::String::String::String.new` works

See this article for more info: http://makandracards.com/makandra/20633-ruby-constant-lookup-the-good-the-bad-and-the-ugly

**Comment by rbishop** [comment]
Thanks for the reminder and sharing that link. I forget about this intricacy until it bites me in the butt.
