### ISSUE TITLE
Link to documentation in project wiki/readme

### ISSUE THREAD

**Issue by matildasmeds** [redis/redis-rb#592]
Project wiki/readme would ideally link to the actual API: 
http://www.rubydoc.info/github/ezmobius/redis-rb/
If it's there, it could certainly be located more prominently.

**Comment by badboy** [comment]
Except that link is about 4 years out of date.

**Comment by matildasmeds** [comment]
How about a slight reframing then, would be cool to have up-to-date link to API on the project readme and wiki. :)

**Comment by badboy** [comment]
We already indirectly link to [the docs](http://www.rubydoc.info/github/redis/redis-rb/master/frames) through the doc badge on top. I'm in favor of changing the link to it directly.
