### ISSUE TITLE
IO.select never returns

### ISSUE THREAD

**Issue by ldlamarc** [redis/redis-rb#597]
File: lib/redis/connection/ruby.rb
Commit: f8ed909
Line: 52 (if IO.select([self], nil, nil, @timeout))
args: @timeout is nil, self is a "Redis::Connection::TCPSocket:fd 19" when line is called

I found this issue while trying to debug why my application was freezing. I came upon this exact line with the byebug gem (going step by step).

**Comment by badboy** [comment]
Got any code to reproduce?

**Comment by ldlamarc** [comment]
The bug has disappeared by destroying my development vagrant image and reprovisioning it (which reset Redis locally). I haven't been able to reproduce the bug.
