### ISSUE TITLE
Heroku: Redis::CommandError: ERR max number of clients reached 

### ISSUE THREAD

**Issue by sajjadmurtaza** [redis/redis-rb#604]
Hello

Am facing Redis::CommandError: ERR max number of clients reached error on heroku. kindly guide me how i can fix it.

**Comment by itamarhaber** [comment]
You've most likely reached the maximum number of connections allowed by your Redis add-on provider. Upgrade your Redis plan or close connections - these are your choices. In any case, this does not appear to redis-rb issue.
