### ISSUE TITLE
Client initialize error ?   must have timeout parameter in options when Redis.new(options)? 

### ISSUE THREAD

**Issue by rogerluo410** [redis/redis-rb#611]
when `Redis.new` without timeout parameter in options,   throw an exception: can't convert nil into Float .

I found in method `_parse_options ` of lib/redis/client.rb, line number 444 
```
  if options.has_key?(:timeout)
        options[:connect_timeout] ||= options[:timeout]
        options[:read_timeout]    ||= options[:timeout]
        options[:write_timeout]   ||= options[:timeout]
      end

      # meet "can't convert nil into Float" error while don't put timeout parameter in options 
      # for Redis.new(options)
      options[:connect_timeout] = Float(options[:connect_timeout])  


      options[:read_timeout]    = Float(options[:read_timeout])
      options[:write_timeout]   = Float(options[:write_timeout])
```

Is that an error , or , it has to have timeout in options while `Redis.new` ?  like  
`Redis.new({host: xxx, port: xxx , timeout: 55}) ` it is ?   

something else, options' access key only supports symbol,  supports  string is available ?

**Comment by rogerluo410** [comment]
I found in  version 3.2.2 ,   the converting used `to_f`, `nil.to_f == 0.0`  which is ok, 
 but, the new version  is using `Float(options[:connect_timeout])` which throws the exception "can't convert nil into Float" without timeout  parameter.

**Comment by bikramwp** [comment]
Same issue here. v3.2.2 was ok, v3.3.0 breaks.
This happened for me using Rails mailer deliver_later and sidekiq.

**Comment by rogerluo410** [comment]
@bikramwp 

Just adding timeout access key in options to avoid the issue :) 
That's what we can do now...

**Comment by badboy** [comment]
Uhm, what code are you using? The initialization uses the default values if no value is passed for an option. So I'm not sure how you are triggering this bug.

**Comment by bikramwp** [comment]
@rogerluo410, yes, it worked with that option.

Some more information from debugging:

I am using [Redis with ConnectionPool](https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control) and the error occurs (via Sidekiq) only when using ConnectionPool. If I don't use the ConnectionPool, I don't see that error.

**Comment by badboy** [comment]
Thanks, I'm looking into it.

**Comment by badboy** [comment]
I tried with this small snippet and everything worked just fine: https://gist.github.com/badboy/55b69647ff64b154fea93cf3cab9a24c

Can you provide the used code, used versions of Redis and other gems as well as the full error including a backtrace?

**Comment by bikramwp** [comment]
Thanks @badboy. I have some more information:

It appears the problem has something to do with the type of hash key being string or symbol in [`_parse_options`](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L382).

[Looking at this line](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L438) :

If the options contain: `{ :timeout => 5.0 }`, then (it fails):
```
puts options[:timeout].inspect # 5.0
puts options.has_key?(:timeout) # false
```

If the options contain: `{ "timeout" => 5.0 }`, it works:
```
puts options["timeout"].inspect # 5.0
puts options.has_key?("timeout") # true
```

I will have to investigate this further later though.

**Comment by bikramwp** [comment]
@badboy, it turns out redis-rb is not the issue. Thanks for your time!

In my case the issue stems from using the [settingslogic](https://github.com/settingslogic/settingslogic) gem. It breaks the Hash contract.

**Comment by badboy** [comment]
@bikramwp Thanks for confirming.
@rogerluo410 Do you still have the problem?

**Comment by rogerluo410** [comment]
@badboy  

It's ok now,  the same problem as @bikramwp, the settingslogic gem makes the hash access key be string, which causes the problem.   

Thanks for attention,  @badboy  and @bikramwp
