### ISSUE TITLE
3.3.0 creates tons of threads

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#614]
The new write_timeout support from #482 results in lots of short-lived threads created, since each timeout block creates a separate thread.  Now every write to Redis requires the creation of a new Thread.  Can we do better?  Is there any work around, e.g. can we set `write_timeout: nil` and not use Timeout?

**Comment by mperham** [comment]
To be explicit, this is the line in question: https://github.com/redis/redis-rb/blob/master/lib/redis/connection/ruby.rb#L85

**Comment by mperham** [comment]
If I switch to `driver: :hiredis`, my load tester performance doubles.  While that's an easy workaround, I'd like to see the pure Ruby performance as optimized as possible.

**Comment by djanowski** [comment]
Mike, we're looking into it: #612.

We're investigating if there's a way to use `Timeout` without this issue. Otherwise, move to low-level socket timeouts. I know you have experience with these problems, so any insight is appreciated.

**Comment by mperham** [comment]
Thanks for the pointer, no one had contacted me.  AFAIK the only efficient way to do a write timeout is with IO.select.
