### ISSUE TITLE
Support for Redis 3.2 Geospatial searches

### ISSUE THREAD

**Issue by Danieth** [redis/redis-rb#620]
Our team is considering using Redis to do geospatial searches. Redis 3.2 added this [functionality](http://redis.io/commands/#geo). Is this something redis-rb is planning to support in the future? How difficult would these methods be to add to redis-rb?

**Comment by badboy** [comment]
It already works (kinda):

```
[1] pry(main)> r=Redis.new
=> #<Redis client v3.3.0 for redis://127.0.0.1:6379/0>
[5] pry(main)> r.geoadd "foo", 52.4, 7, "abc"
=> 1
[7] pry(main)> r.geohash "foo", "abc"
=> ["t1jrb6k9bq0"]
```

**Comment by Danieth** [comment]
Thanks! I originally installed Redis it using brew (which still uses version 3.0.7), but didn't properly clean it up before installing 3.2 manually. In my tests I was still connected to 3.0.7 so the methods weren't piped through - I searched the repository for geo and didn't find anything so I assumed it just wasn't implemented. If we use Redis for geospatial data, and we need a nicer API, I'll fork the project and pull-request it with a proposal.
