### ISSUE TITLE
scan_each returns unusable iterator when nothing matches

### ISSUE THREAD

**Issue by maxim** [redis/redis-rb#624]
When there are no matching keys, any of these lines (or similar lines)

```ruby
$redis.scan_each(match: 'non-existent-*').to_a
$redis.scan_each(match: 'non-existent-*').count
$redis.scan_each(match: 'non-existent-*') { |e| e }
```

Raise this error:
```
NoMethodError: undefined method `each' for nil:NilClass
from /Users/max/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.0/lib/redis.rb:2505:in `block in scan_each'
```

Imo would make sense to return an empty iterator here.

**Comment by maxim** [comment]
@joshuaflanagan hey, looks like this might be related to your code in https://github.com/redis/redis-rb/pull/379, would appreciate your thoughts.

**Comment by maxim** [comment]
Looks like there are cases where `keys` in this line (inside redis gem) is set to `nil`, this doesn't happen every time, e.g. this happens in my test env in rails, but not in development env.

```ruby
cursor, keys = scan(cursor, options)
```

**Comment by joshuaflanagan** [comment]
I can take a look at it in the next couple days.

I wonder if it might be related to a new redis server version? What version are you running?
That code has been running for over 2 years and haven't heard of this before, so that might be a clue.

**Comment by maxim** [comment]
@joshuaflanagan appreciate the response. I'm actually seeing something completely bizarre, the more I look. If I run in Rails dev env it doesn't error, but in test it does. I can't find any meaningful difference aside from using fakeredis in test, and I have no idea what Rails could possibly have to do with it. Fakeredis doesn't seem responsible because it works correctly when I try it in dev env.

**Comment by maxim** [comment]
Fixed this issue with 1 of 2 things (not 100% sure which one):

1. switched from fakeredis to mock_redis
2. changed from `redis.mget(keys)` to `redis.mget(*keys)` (note the splat)

Therefore I'm closing this for now. Joshua, thank you for quick response.
