### ISSUE TITLE
Read distribution across Slaves in Master Slave mode

### ISSUE THREAD

**Issue by debbiswal** [redis/redis-rb#633]
Hi ,
I am using redis-rb ruby gem(https://rubygems.org/gems/redis/versions/3.3.1) to connect to Redis Master Slave.
I am creating the  client using sentinel information.

sentinel_nodes = [{:host => "127.0.0.1", :port => 26380},
             {:host => "127.0.0.1", :port => 26381},{:host => "127.0.0.1", :port => 26382}]
$rc = Redis.new(:url => "redis://MYMASTER", :sentinels => sentinel_nodes, :role => :master)

But with this code , all my read and write goes to master.

Then I changed to this :
# Client for Write

$rcW = Redis.new(:url => "redis://MYMASTER", :sentinels => sentinel_nodes, :role => :master)
# Client for Read

$rcR = Redis.new(:url => "redis://MYMASTER", :sentinels => sentinel_nodes, :role => :slave)

In this case I am writing to master . But all read only goes to a single slave(randomly selected).

Is there any option in redis-rb gem , in which reads will be distributed across slaves.

**Comment by islemaster** [comment]
You may be interested in the [redis-slave-read gem](https://github.com/cheald/redis-slave-read) for this purpose.

**Comment by byroot** [comment]
This question is rather vague and outdated. Clustering support as been added a while ago, so I'm closing this.
