### ISSUE TITLE
Notification events when a node goes down in Redis Cluster

### ISSUE THREAD

**Issue by debbiswal** [redis/redis-rb#635]
Hi @badboy ,
I have implemented redis cluster using redis 3.0.7 version.
I want to know is there any channel or event to which I will subscribe and come to know that a node has gone down. Whether redis supports that.

I have implemented the same concept in my Master-Slave setup using Sentinel notification shell script.

But not sure how to do that in Redis Cluster mode with or without using redis client.

**Comment by badboy** [comment]
Redis Cluster does not have those notifications. It's up to external systems to do so.
