### ISSUE TITLE
lpop dosen't remove the top element

### ISSUE THREAD

**Issue by arpitkashyapnestaway** [redis/redis-rb#637]
while using redis.lpop(key) an element is poped but not element is removed from the list..

**Comment by badboy** [comment]
Sounds unlikely. Can you give a specific example?
Can't reproduce on 3.2:

```
127.0.0.1:6379> lpush foo 1 2 3
(integer) 3
127.0.0.1:6379> lrange foo 0 -1
1) "3"
2) "2"
3) "1"
127.0.0.1:6379> lpop foo
"3"
127.0.0.1:6379> lrange foo 0 -1
1) "2"
2) "1"
```

**Comment by arpitkashyapnestaway** [comment]
this is surely working form redis-cli. but try it form rube code

**Comment by badboy** [comment]
```
[1] pry(main)> r=Redis.new
=> #<Redis client v3.3.1 for redis://127.0.0.1:6379/0>
[2] pry(main)> r.del :foo
=> 1
[3] pry(main)> r.lpush :foo, [1,2,3]
=> 3
[4] pry(main)> r.lrange :foo, 0, -1
=> ["3", "2", "1"]
[5] pry(main)> r.lpop :foo
=> "3"
[6] pry(main)> r.lrange :foo, 0, -1
=> ["2", "1"]
```

If this wouldn't work, that would be a serious bug in either Redis or redis-rb, and it would have been caught by either test suite.
There might be other problems on your side however, like someone immediately pushing a new element or `LPOP` done against a different key.

(Sorry, didn't realize you filed this against redis-rb in the first place)

**Comment by arpitkashyapnestaway** [comment]
yes
@redis.rpop key.to_s.downcase
it worked .
Thanks alot

**Comment by nitin302** [comment]
This issue does exist in higher versions of redis-rb even 4.2.2. Only when doing key.to_s.downcase we are able to lpop. You can easily reproduce by using string keys like "HelloWorld" - which has both upper and lower case characters.
