### ISSUE TITLE
Bad Array reference

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#638]
The [code here](https://github.com/redis/redis-rb/blob/master/lib/redis/connection/ruby.rb#L405) doesn't use `::` to ensure the core Array class is used.  If the user creates Redis::Array, the driver breaks.

Seen in the wild here: https://github.com/mperham/sidekiq/issues/3167

**Comment by djanowski** [comment]
So now we have to reference all constants using `::` just in case someone pollutes the namespace?

Per RubyGems de-facto standards, if you're using a `redis` gem you can expect it to own the `Redis` namespace.

I don't think this is a problem in this gem, sorry.

**Comment by mperham** [comment]
In retrospect, I agree. Thanks for the reality check.

**Comment by djanowski** [comment]
👍
