### ISSUE TITLE
Are gem maintainers interested in ActiveSupport::Notifications integration?

### ISSUE THREAD

**Issue by lukeasrodgers** [redis/redis-rb#639]
I'm wondering if there is any interest in providing `ActiveSupport::Notifications` instrumentation so that applications and other gems can subscribe to salient events from `redis-rb` to, e.g. monitor redis latency, track the number of commands, etc.

A few other gems and monitoring services exist that monkeypatch redis to get this information, e.g.:
- https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/probes/redis.rb
- https://github.com/evanphx/newrelic-redis/blob/master/lib/newrelic_redis/instrumentation.rb
- https://github.com/lautis/redis-rails-instrumentation/blob/master/lib/redis/rails/instrumentation.rb

Providing AS::N instrumentation with the right naming/granularity to obviate the need for such any such custom solution is probably not a practical goal. However, it might make some of this monkeypatching unnecessary and would also permit additional monitoring. For example, I don't believe skylight or newrelic provide high-level metrics like "what is the 95% latency of all my redis queries."

If there is interest, I'd be happy to submit a PR. As outlined [here](http://www.railstips.org/blog/archives/2013/01/23/an-instrumented-library-in-30-lines/) (not my article, just one I used as a guide for AS::N integration on another gem) it is easy to provide such instrumentation without making `ActiveSupport` a hard dependency.

Thanks

**Comment by djanowski** [comment]
Not interested in doing anything related to ActiveSupport, but I'm sure a separate gem could achieve that. Thank you.

**Comment by lukeasrodgers** [comment]
@djanowski fair enough, but it wouldn't require a dependency on AS, just implementation of a fairly minimal interface:

(pseudo-code)

```ruby
module Redis
  module Instrumenters
    class Noop
      def self.instrument(name, payload = {})
        yield payload if block_given?
      end
    end
  end
end

module Redis
  class Client
    def initialize(options = {})
      # some other setup for the client ...
      @instrumenter = options[:instrumenter] || Instrumenters::Noop
    end
  end
end
```

Then users of the redis gem are free to provide their own instrumenter that supports that interface if they want. Doesn't have to be AS, and if you don't specify any instrumenter, there is very little overhead.

**Comment by badboy** [comment]
Still requires us to maintain another interface inside the main client. @djanowski's proposed way seems fine to me: put that into another Gem.
