### ISSUE TITLE
Extract RedisMock

### ISSUE THREAD

**Issue by brodock** [redis/redis-rb#641]
I would like to ask for RedisMock to be extracted into a separate gem (or included in the released gem), so redis dependent libraries that do lower-level integration can benefit from it.

cc @djanowski @badboy

**Comment by badboy** [comment]
RedisMock is pretty limited in scope. If anyone wants to use it, they are free to copy it over for their use case. But I don't see the need (nor do I have the time and motivation) to maintain it in a stable released way.
