### ISSUE TITLE
Redis connection not being proxied

### ISSUE THREAD

**Issue by scttnlsn** [redis/redis-rb#642]
I'm using [`socksify`](https://rubygems.org/gems/socksify) to proxy TCP connections in a Ruby application.

``` ruby
unless ENV['PROXY_URL'].nil?
  require 'socksify'
  uri = URI.parse(ENV['PROXY_URL'])
  TCPSocket::socks_server = uri.host
  TCPSocket::socks_port = uri.port
  TCPSocket::socks_username = uri.user
  TCPSocket::socks_password = uri.password
end
```

I can successfully open a proxied TCP connection to the Redis server (the proxied IP is whitelisted by the Redis server's firewall):

``` ruby
require 'socket'
TCPSocket.open(IP, PORT)
```

But when using the `Redis` client I get a timeout.

``` ruby
require 'redis'
redis_uri = URI.parse(ENV[‘REDIS_URL’])
redis = Redis.new(host: redis_uri.host, port: redis_uri.port, password: redis_uri.password)
redis.connect
```

Gives the following error:

`Redis::CannotConnectError: Error connecting to Redis on <IP:PORT> (Redis::TimeoutError)`

It looks like `socksify` works by monkey-patching the initialization of TCPSocket.  Any idea why the Redis connection is not being proxied?  I'm using the default driver.

Thanks!

**Comment by badboy** [comment]
Monkey-patching core classes sounds bad.
redis-rb internally inherits from `::TCPSocket`, adding it's own methods. That might be the issue. 
Or you're using hiredis, which does not use `::TCPSocket` at all.

**Comment by scttnlsn** [comment]
OK, thanks.  Do you have any suggestions about an alternative way to setup SOCKS proxying for the Redis connection?  Do I need to write a custom driver?

**Comment by badboy** [comment]
Yes, you could take the current implementation as a basis for adding the proxy yourself and then use that as a custom driver.

(sorry for not responding earlier)
