### ISSUE TITLE
how is a best method to cache a image ?

### ISSUE THREAD

**Issue by luizamboni** [redis/redis-rb#645]
i m usin the follow code in a rails action, but some times, none is returned

```ruby
    size = params[:size] || :original
    key = "images::user::#{size}::#{params[:user_id]}::"
    data = RedisClient.get key 
    if data
      logger.info "cache avatar"
      send_data data, status: 304
    else
      logger.info "no cache avatar"
      user = User.find(params[:user_id])
      url = (Rails.env.production?)? user.avatar.url(size) :  user.avatar.path(size)
      data = open(url).read
      content_type = user.avatar.content_type
      Thread.new { RedisClient.setex("#{key}", PICTURES_CH, data) }.join
      send_data data
    end
```

**Comment by badboy** [comment]
Track down which part is returning the wrong result. From a first look without further knowledge about the code it looks ok.

Keep in mind that these issues should be used for issues and bugs in redis-rb. We can't debug your overall usage of the library in a larger context.

**Comment by luizamboni** [comment]
well, none exception is throwed, but nothing in url responded after a time
