### ISSUE TITLE
TimeoutError when creating Redis cluster

### ISSUE THREAD

**Issue by thethomp** [redis/redis-rb#651]
After moving from 3.3.1 to 3.3.2 last week, I started running into the following error when creating a Redis cluster using this script. There's about 30 seconds where nothing happens after I type "yes", before the exception is thrown. I've removed the IPs in the output below for security. 

Rolling back to 3.3.1 fixed the problem immediately, so it seems some change in 3.3.2 is causing this.

>>> Creating cluster
>>> Performing hash slots allocation on 9 nodes...
Using 3 masters:
ip1:6001
ip2:6001
ip3:6001
Adding replica ip2:6002 to ip1:6001
Adding replica ip3:6002 to ip1:6001
Adding replica ip1:6002 to ip2:6001
Adding replica ip1:6003 to ip2:6001
Adding replica ip2:6003 to ip3:6001
Adding replica ip3:6003 to ip3:6001
M: 70f6a853d98f4098ecbf2a21706ac982c70dc486 ip1:6001
   slots:0-5460 (5461 slots) master
M: 9852075a8c2d7d0489efdc00d9be4264b8655ac8 ip2:6001
   slots:5461-10922 (5462 slots) master
M: 9b58fe3d67ecfe0adb25f49972507dc3c750da50 ip3:6001
   slots:10923-16383 (5461 slots) master
S: 556e6019002b1f1fb825ef620fd966d06b968e27 ip1:6002
   replicates 9852075a8c2d7d0489efdc00d9be4264b8655ac8
S: 175304d226482af875b6551b77127978bcded1e3 ip2:6002
   replicates 70f6a853d98f4098ecbf2a21706ac982c70dc486
S: cbf10ea8f30c5604813041d1bd1cf67c39ada3e6 ip3:6002
   replicates 70f6a853d98f4098ecbf2a21706ac982c70dc486
S: acdb0f342f68dbc54f44ef0a0db7bee3e794beea ip1:6003
   replicates 9852075a8c2d7d0489efdc00d9be4264b8655ac8
S: 1f9485ac3790325e3e01bd61d99be096c3300aa6 ip2:6003
   replicates 9b58fe3d67ecfe0adb25f49972507dc3c750da50
S: c6fd1da84f7db9b2a69172e048949cb53931db1a ip3:6003
   replicates 9b58fe3d67ecfe0adb25f49972507dc3c750da50
Can I set the above configuration? (type 'yes' to accept): yes
/var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/connection/ruby.rb:111:in `rescue in _write_to_socket': Connection timed out (Redis::TimeoutError)
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/connection/ruby.rb:104:in `_write_to_socket'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/connection/ruby.rb:131:in `block in write'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/connection/ruby.rb:130:in `loop'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/connection/ruby.rb:130:in `write'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/connection/ruby.rb:374:in `write'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:271:in `block in write'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:250:in `io'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:269:in `write'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:228:in `block (3 levels) in process'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:222:in `each'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:222:in `block (2 levels) in process'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:367:in `ensure_connected'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:221:in `block in process'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:306:in `logging'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:220:in `process'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis/client.rb:120:in `call'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis.rb:2705:in `block in method_missing'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis.rb:58:in `block in synchronize'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis.rb:58:in `synchronize'
        from /var/lib/gems/1.9.1/gems/redis-3.3.2/lib/redis.rb:2704:in `method_missing'
        from redis-3.2.3/src/redis-trib.rb:212:in `flush_node_config'
        from redis-3.2.3/src/redis-trib.rb:776:in `block in flush_nodes_config'
        from redis-3.2.3/src/redis-trib.rb:775:in `each'
        from redis-3.2.3/src/redis-trib.rb:775:in `flush_nodes_config'
        from redis-3.2.3/src/redis-trib.rb:1296:in `create_cluster_cmd'
        from redis-3.2.3/src/redis-trib.rb:1696:in `<main>'

**Comment by badboy** [comment]
Yes, seems like the last release is buggy. We're on it. Until then please use the previous version.

**Comment by ggarnier** [comment]
@badboy shouldn't this issue be left open until it's fixed?
