### ISSUE TITLE
Timeouts are confusing

### ISSUE THREAD

**Issue by nerdrew** [redis/redis-rb#652]
`timeout` and `write_timeout` seem to be per-syscall timeouts, which is misleading. There doesn't seem to be an overall timeout. Is it worth adding some overall timeouts (or converting `timeout` and `write_timeout` to be overall timeouts)?

Vaguely related PR (fixes non-blocking exception handling): https://github.com/redis/redis-rb/pull/649

cc @quixoten @tarcieri

**Comment by tarcieri** [comment]
@nerdrew I wonder if we could solve this problem more generally in e.g. https://github.com/celluloid/timers

You could imagine an API like `http.rb`'s timeout:

https://github.com/httprb/http/wiki/Timeouts

...but it would handle calculating per-operation timeouts for you, based on a combination of per-operation and global timeouts.

**Comment by nerdrew** [comment]
@tarcieri I like `http.rb`'s approach to this. It would be really nice if there was a ergonomic library that handled sockets in ruby ;p

cc @zanker

**Comment by tarcieri** [comment]
There's my half-finished one:

https://github.com/socketry/socketry

Doesn't support global timeouts yet, although it has [hitimes](https://github.com/copiousfreetime/hitimes)-backed per-operation timeouts

**Comment by byroot** [comment]
Closing as this is quite old, and I'm really unsure what it is about.
