### ISSUE TITLE
Unable to executing 'latency latest' command

### ISSUE THREAD

**Issue by debbiswal** [redis/redis-rb#655]
Hi ,
I want to execute 'latency latest' command against Redis by using redis gem(redis-rb) file.
I am not finding any method related to it.
I also tried redis.client.call('latency latest') . it is not working
latency thresshold is already set on redis instance.

Any one has any idea on this?

**Comment by badboy** [comment]
you have to pass an array of the command and its arguments:

```ruby
r.client.call(["latency", "latest"])
```

**Comment by debbiswal** [comment]
Thanks @badboy
