### ISSUE TITLE
Concerns about Fixnum -> Integer

### ISSUE THREAD

**Issue by jcoyne** [redis/redis-rb#666]
Regarding this commit https://github.com/redis/redis-rb/commit/37ab9045e0fed202e42e49ccc11d41cc64de1759

I believe this introduces an error when using Ruby < 2.4 as this block will never be entered:
https://github.com/redis/redis-rb/blob/37ab9045e0fed202e42e49ccc11d41cc64de1759/lib/redis/client.rb#L459-L469 when `options[:tcp_keepalive]` is set to an integer. 

This is because `0.class` is `Fixnum` not an `Integer` when using Ruby 2.3 or below.

**Comment by badboy** [comment]
Nope, it works just fine. `case` calls the `===` (three-equals) operator on the `when` object with the `case` object as its arguments. The `===` operator on class constants effectively results in an `is_a?`. And as `Integer` is an ancestor of an integer it just works.

```
[1] pry(main)> RUBY_VERSION
=> "2.3.3"
[2] pry(main)> Integer === 42
=> true
```

**Comment by jcoyne** [comment]
@badboy thanks for the clarification.  I was looking at https://github.com/rails/rails/pull/26732/files#diff-fc90ec41ef75be8b2259526fe1a8b663R37 and saw the `0.class`, but failed to see that you were using the case comparison operator. 👍
