### ISSUE TITLE
3.3.2 causes Resque worker timeouts

### ISSUE THREAD

**Issue by timhaines** [redis/redis-rb#667]
Hi there.  I haven't developed an understanding of this yet, but am experiencing consistent Resque worker timeouts in 3.3.2 that I wasn't seeing in 3.3.1.  As there were only 2 commits in 3.3.2, I guess it's a result of this change: https://github.com/redis/redis-rb/commit/cf9d7b376a2949759638ba51619a6d825a04ac59

**Comment by badboy** [comment]
[Yeah, it's known](https://github.com/redis/redis-rb/pull/649). I try to get a release out coming week.

**Comment by djanowski** [comment]
3.3.3 is out.

**Comment by timhaines** [comment]
@djanowski Thank you!
