### ISSUE TITLE
Documentation: can same client be used by multiple threads particularly in pipeline mode?

### ISSUE THREAD

**Issue by timanovsky** [redis/redis-rb#669]
Sorry, documentation is not clear. If I issue commands in pipeline mode and use same connection from multiple threads, they will interleave, won't they?

**Comment by badboy** [comment]
If I understand you correctly this should not happen.
Are you talking about the `pipelined` method with a passed block? If so, the client is locked before executing any commands and only unlocked when the pipeline is finished. Thus it should not be possible to interfere with other commands.

**Comment by timanovsky** [comment]
@badboy Thanks for your comment.
> Are you talking about the pipelined method with a passed block?

Yes

>If so, the client is locked before executing any commands

So something like mutex is used which prevents other threads from using same connection, right? In other words if I have multiple threads with active Redis traffic I'd better use connection pool in order not to get the threads synchronized on single I/O object (of course I assume I have no logic data conflict)

**Comment by badboy** [comment]
Correct.

**Comment by timanovsky** [comment]
Thanks, it's clear now!
