### ISSUE TITLE
Please release 3.3.3

### ISSUE THREAD

**Issue by jcoyne** [redis/redis-rb#671]
It would be great to have this commit in a release https://github.com/redis/redis-rb/commit/9da74357491a77e128474aa929054fa402fc211d so that we no longer get deprecation warnings.

Thanks.

**Comment by fwininger** [comment]
:+1:

**Comment by harold-s** [comment]
:+1:

**Comment by agombault** [comment]
:+1:

**Comment by badboy** [comment]
A deprecation warning is really the least of our problems. I will get around to do this ASAP.

**Comment by jcoyne** [comment]
@badboy Thanks. I appreciate all your hard work.

**Comment by djanowski** [comment]
3.3.3 is out.

**Comment by harold-s** [comment]
Thanks !
