### ISSUE TITLE
Alternate DNS for Redis

### ISSUE THREAD

**Issue by dbenjamin57** [redis/redis-rb#680]
We heavily pound Redis with our infrastructure (approx. 8K requests a sec). Especially because Redis is our job messaging system as well (we use Sidekiq).

Now, many times we get the following errors:

```
RuntimeError: Name or service not known
RuntimeError: Temporary failure in name resolution
```
Our Redis configuration is simple:

```
$redis_config = {
    host: ENV['REDIS_HOST'],
    password: ENV['REDIS_PASSWORD'],
    port: 6379,
    driver: :hiredis
}

$redis = Redis.new($redis_config)
```
Im guessing this issue is due to the fact the DNS of our Redis isn't resolving to an IP. So I was thinking about potentially trying an alternate DNS (I have another one) in-case of failure.

Is there any way I can configure something like that using the Redis Gem?

**Comment by badboy** [comment]
redis-rb is not responsible for your DNS. It uses the system-provided mechanism. You should see that you fix that instead or use a IP directly (if it is stable)

**Comment by sixfeetover** [comment]
@dbenjamin57 Try just using resolv-replace (`require 'resolv-replace`) in your code. It's a more thread safe DNS resolver. https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#frozen-processes.
