### ISSUE TITLE
ERR unknown command 'resolve'

### ISSUE THREAD

**Issue by gregwinn** [redis/redis-rb#681]
I am getting this error in my puma.log file and am not really sure what is going on... Data seems to be loading intermittently from my redis cluster.

Has anyone seen this?

  
> cache error: ERR unknown command 'resolve'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:121:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:2705:in `block in method_missing'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
> /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.3/lib/redis.rb:2704:in `method_missing'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-cache-1.7.0/lib/rack/cache/storage.rb:38:in `create_store'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-cache-1.7.0/lib/rack/cache/storage.rb:18:in `resolve_metastore_uri'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:34:in `metastore'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:173:in `lookup'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:66:in `call!'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:51:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:225:in `call'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/server.rb:578:in `handle_request'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/server.rb:415:in `process_client'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/server.rb:275:in `block in run'
> /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

Any hints as to what is going on would be great.

**Comment by badboy** [comment]
Your rack-cache gem is sending a non-existent command. Check the code and report this upstream.
