### ISSUE TITLE
Connection spikes and timeouts

### ISSUE THREAD

**Issue by umang** [redis/redis-rb#684]
We use AWS elasticache as our redis server and redis 3.3.3 gem in our rails application. For this redis instance we use the hiredis driver.

We see redis timeout errors every once in a while [Redis::CannotConnectError(Redis::TimeoutError)]
The errors usually occur in a cluster and almost always there is a momentary spike in the number of connections on the redis server at precisely that point in time.

<img width="910" alt="screen shot 2017-03-21 at 5 31 48 pm" src="https://cloud.githubusercontent.com/assets/80904/24183244/286e9be8-0eed-11e7-9712-e4bcca23c8a4.png">

So far we have failed in understanding the spike in the number of connections and how (if at all) is it related to the timeout errors. AWS guys seems to indicate that the problem is not on the server end. Any help/pointers will be much appreciated

**Comment by badboy** [comment]
Did you configure a timeout on the client side?

I sadly cannot debug your production environment. And I don't know where those additional connections come from, so there's not much for me to help here.

**Comment by umang** [comment]
Thanks for the response anyways.

To answer your question, I have not configured a timeout on the client side, so I assume it will default to 5 seconds.

What I was wondering was what would cause new connections to go away immediately, since the timeout on the server side (AWS) is also set to the default value 0, which means that the server will not clean up for old connections.

**Comment by le0pard** [comment]
@umang @badboy I got the same problems on AWS, but I am have own instance with redis server. It was problem with ixgbevf Network Driver. Here more info about this: https://forums.aws.amazon.com/thread.jspa?threadID=254045 http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html Maybe your instance also loose network and redis gem begin growing connections for each "redis request" (get/set/etc). Was fixed by updating driver for me on all instances.

**Comment by umang** [comment]
@le0pard 

So it turns out we do have an old version of the ixgbevf driver. We will upgrade and report back it works for us well.

Thanks a ton for sharing your experience

**Comment by umang** [comment]
@le0pard 
It seems like working. Have not had any error instances since the driver update.

Thanks again!
