### ISSUE TITLE
Issuing Redis unsubscribe when websocket close has terminated Redis thread

### ISSUE THREAD

**Issue by TechRsch** [redis/redis-rb#686]
I am issuing a Redis subscribe within WebSocket (WS). When I receive the WS open, I thread the request and then instantiate the Redis client. Within the open, I thread for Redis and issue the subscription. This all works fine, until I receive an unexpected WS close. At that point, the thread running the Redis subscription is gone. If I issue an unsubscribe, I get a hang. If I don't unsubscribe, I have left a phantom subscription that causes me trouble next go round. Is there some way to delete a subscription once the thread that issued it has terminated? I have noted that the Redis instance has a mon variable for that terminated thread. 

The recovery problem is that, after termination, when the device tries to recover and open WS again, I try the sequence where "credis" is first assigned within the code.  It says that a subscription is outstanding, but fails when trying to unsubscribe it because I'm using the "wrong" Redis instance.  However, as shown above, if I try to unsubscribe through the "correct" instance, during close, Redis locks up on synchronize, which looks for the original subscribing thread, because the subscribing thread is already lost.

Basically, how do I clean up such a "phantom" subscription?

Sample Ruby code is:

```
class Backend
  include MInit

  def initialize(app)
    setup
    # @redis is assigned in setup
    @app = app
  end

  def run!(env)
    if Faye::WebSocket.websocket?(env)
      ws = Faye::WebSocket.new(env, [], ping: KEEPALIVE_TIME)
      ws_thread = Thread.fork(env) do
        credis = Redis.new(host: @redis_uri.host, port: @redis_uri.port, password: @redis_uri.password)

        subscription_count = credis.pubsub('numsub', channel)[1]
        if subscription_count > 0
          puts "Error: Multiple subscriptions on channel:#{channel}; Count:#{subscription_count};"
          # Recovery problem which results is the following command fails with: Can't unsubscribe if not subscribed.
          credis.unsubscribe(channel)
          subscription_count = credis.pubsub('numsub', channel)[1]
          puts "Error: Recovery unsubcribed on channel:#{channel}; Count:#{subscription_count};"
        end

        ws.on :open do |event|
          channel = URI.parse(event.target.url).path[1..URI.parse(event.target.url).path.length]
          redis_thread = Thread.fork do
            credis.subscribe(channel) do |on|
              on.message do |message_channel, message|
                sent = ws.send(message)
              end
              on.unsubscribe do |message_channel|
                puts "Unsubscribe on channel:#{channel};"
              end
            end
          end
        end

        ws.on :message do |event|
          handoff(ws: ws, event: event)
        end

        ws.on :close do |event|
          # Initial problem is that hang occurs here because the thread issuing subscribe has been terminated
          unsubscribed = credis.unsubscribe(channel)
        end

        ws.on :error do |event|
          ws.close
        end

        # Return async Rack response
        ws.rack_response

      end
    end
  else
    @app.call(env)
  end

  private
  def handoff(ws: nil, event: nil, source: nil, message: nil)
    # processing
  end
end
```

**Comment by badboy** [comment]
If I understand you correctly, there's still a Redis connection open. Your only way would be to hold on to that connection and explicitely close it before the thread exits.
I do not know any of the inner workings of Rack or Faye, so I can't help with that

**Comment by TechRsch** [comment]
I presented my solution on [SO here](http://stackoverflow.com/questions/43173991/using-redis-client-list-with-regex-lookahead-to-kill-redis-hanging-connection-fr/43257238#comment73766094_43257238).  Basically, I've had to parse out CLIENT LIST programmatically to get the ID stored so that I can KILL the connection during WS Close.  The code I presented on SO is:
```
# Need a variable string that is individual for each connection
queue = 'MY_APPL:' + @prefix + ':Queue:' + @client_channel
# Use the REDIS connection to issue SETNAME for LIST
setname = @client_queue.call('CLIENT', 'SETNAME', queue)
# Get the LIST of connections
list = @client_queue.call('CLIENT', 'LIST')
# Grab and store the ID that will be used for the WS Close
# Regex is explained as:
#   Positive lookahead to find line holding queue:(?=#{queue})
#   Noncapturing scan for id=:(?:id=)
#   Numbered capture of following digits:(\d*)
#   Noncapturing scan for any character up to queue:(?:.*)
#   [0] is entire line before queue, [1] is the numbered capture of the id number
@client_id = /(?:id=)(\d*)(?:.*)(?=#{queue})/.match(list)[1]
#
# The following line occurs within WS Close to kill the connection
@client_queue.call('CLIENT', 'KILL', 'ID', @client_id, 'SKIPME', 'NO')

```
It would be extremely helpful, easier, and more reliable to have a method that returns ID as well as address/port to enable KILL in such a situation.  (Actually  Parsing CLIENT LIST text is inefficient and, I assume, liable to unannounced changes over time.  Would it be possible to get such a change?

**Comment by badboy** [comment]
I still have the feeling that your client is misbehaving. Parsing `CLIENT LIST` and killing the client seems like a hacky workaround.

How does your thread die? Can't you do cleanup when it dies? it definitely leaks the connection somehow.

**Comment by TechRsch** [comment]
It is a hacky workaround, certainly.  Given the code I posted above, I am running a Redis thread within a WebSocket event-driven process.  Within the WS.open, I listen for a Redis response, originally using subscribe but now using brpop.  Without prior notice to me, eventually WS.close occurs.  At that point, the WS.open process has already deleted my Redis thread.  So, I don't have a choice but to clean up the remnants.  And, because any further Redis command on that connection immediately hangs on synchronize, since the issuing thread is gone, my last resort is a kill  

I have posted the same issue on faye-websocket-ruby and requested the opportunity to clean things up before the open deletes them.  That would be the preferred solution, of course.  Seems like a yield at that point would be prudent. 

Yet, in any case, if the only options for KILL is ID or address:port, I should be able to obtain either one of those values using a real method instead of a hack against a string.  Is that doable?

**Comment by badboy** [comment]
```ruby
 Hash[r.call("client", "list").split.map{|v| v.split('=',2)}]
```

As mentioned in that other issue there's an `onclose` event. Handle your disconnect there (you might need to hold on to the client object and maybe even a handle to your thread).

I'm gonna close this for now, as to me this still seems like it's not an issue with redis-rb itself, but with your side of handling the state.

**Comment by TechRsch** [comment]
Turns out that the problem wasn't quite as I described.  The Redis thread actually still exists.  But, Redis is hanging anyway because it is waiting for the thread to get control.  To do that, the WS.close code needs to cede control by using EM.next_tick within the WS.close as follows:
```
EM.next_tick do
      # Hang no longer occurs here
      unsubscribed = credis.unsubscribe(channel)
end
```
And, that fixed my hang.
