### ISSUE TITLE
BRPOP, given a timeout, returns data only after the timeout expires

### ISSUE THREAD

**Issue by TechRsch** [redis/redis-rb#688]
I am providing BRPOP a 5 second timeout.  I check the timers before and after the BRPOP.  Every time there is data to be returned, it returns in exactly 5 seconds.  From the documentation, I assume that it should return data immediately upon the LPUSH and not always wait for 5 seconds.

**Comment by badboy** [comment]
Can't reproduce.

No `LPUSH`:

```
$ r=Redis.new; start=Time.now; val=r.brpop("foo", 5); stop=Time.now; [start, stop, val]
=> [2017-04-19 10:00:06 +0200, 2017-04-19 10:00:11 +0200, nil]
```

`LPUSH` after a second:

```
$ r=Redis.new; start=Time.now; val=r.brpop("foo", 5); stop=Time.now; [start, stop, val]
=> [2017-04-19 10:00:37 +0200, 2017-04-19 10:00:38 +0200, ["foo", "1"]]
```

**Comment by TechRsch** [comment]
Thanks for helping clarify.  The brpop was running in a thread while lpush was running in the main process.  It appears the thread doesn't get control until the timer pops, so brpop does not read the queue until that point.  It's something my code has to handle.
