### ISSUE TITLE
Unable to unsubscribe from pub/sub

### ISSUE THREAD

**Issue by kaelumania** [redis/redis-rb#693]
I am unable to unsubscribe from outside the subscribe block/loop as the redis client synchronizes the client access. Thus, the only possible way to unsubscribe is sending a pub/sub message over the channel, that forces the loop from within `on.message` to unsubscribe, right? This seems a bit of a hassle, because the message needs to go over the server. Therefore I tried the following:

```ruby
      @thread = Thread.new do
        puts "Subscribe"
        @redis.psubscribe("__key*__:*") do |on|
          on.psubscribe do |pattern, total|
            puts "Subscribed to ##{pattern} (#{total} subscriptions)"
          end

          on.pmessage do |pattern, channel, message|
            puts "#{pattern} ##{channel}: #{message}"
          end

          on.punsubscribe do |pattern, total|
            puts "Unsubscribed from ##{pattern} (#{total} subscriptions)"
          end
        end
        puts "subscription terminated"
      end
      @thread.abort_on_exception = true
```

Then, when I tried to unsubscribe later on, from the main thread for example

- `@redis.punsunbscribe` blocks forever as it is synchronized and the thread holds the mutex.
- `@redis.close` seems to force some kind of resubscribe as I get the first `Subscribed to...` message again
- `Thread.kill @thread` kills the thread, but the client seems not to be garbage collected as I checked `redis-cli` with `client list`

**Comment by mperham** [comment]
This is as designed, otherwise the code is full of race conditions and potential to get out of sync with the server.

**Comment by byroot** [comment]
> This is as designed

Indeed AFAIK.

**Comment by alxx** [comment]
Then what is the point of the `unsubscribe` and `punsubscribe` methods? How are they supposed to be used? How do I unsubscribe in Pub/Sub?

The Redis docs say that, while the client isn't supposed to send other commands while subscribed, it should still be able to send some stuff:

> The commands that are allowed in the context of a subscribed client are SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING and QUIT.

So... how do I unsubscribe or add a channel to the subscription without closing it?

**Comment by byroot** [comment]
> How are they supposed to be used? How do I unsubscribe in Pub/Sub?

From inside the sub callback:

```ruby
redis.subscribe(...) do
  ...
  if done
    redis.unsubscribe(...)
  end
end

```

Alternatively if you know what you are doing you can bypass the mutex with `.call` but that's at your own risk: https://github.com/gmalette/pubsubstub/blob/a445c4969f2a7a1fe0894320f1ecd1d7e362d611/lib/pubsubstub/subscriber.rb#L30-L36

**Comment by alxx** [comment]
Thanks. What's the risk with bypassing the mutex? As long as the subscribing thread terminates naturally right after that, of course.

**Comment by byroot** [comment]
> What's the risk with bypassing the mutex?

The risk is that if another thread was writing a command inside the connection, you'll insert yours in the middle causing havoc.

It's only safe to do if you are certain that no command will be ever written in that connection, hence why the API doesn't let you do that.

**Comment by alxx** [comment]
> It's only safe to do if you are certain that no command will be ever written in that connection, hence why the API doesn't let you do that.

Well, no command other than the six ones permitted by Redis, right?

**Comment by byroot** [comment]
No, no commands at all.

e.g.

- Thread 1: write `UNSUBSCRIBE`
- Thread 2: write `PING`
- Thread 2: read the response expecting a `PING` response
- Thread 2: get and `UNSUBSCRIBE` response instead and fail to parse it, and raise an error.

Result: that connection is now in a broken state and likely won't recover from it.

**Comment by alxx** [comment]
So the only way to SUBSCRIBE or UNSUBSCRIBE is reactively, based on stuff that happens in the channel? I can't unsubscribe for example because it's six o'clock, unless I tell that on the channel first? And, if I do publish the magic word to make a client unsubscribe, I need to make it client-specific so the other subscribers won't react as well?

Can't we at least be allowed to issue a SUBSCRIBE command? After all, the Redis response for SUBSCRIBE is pretty specific and cannot be mistaken for the response to any other command.

**Comment by byroot** [comment]
> So the only way to SUBSCRIBE or UNSUBSCRIBE is reactively, based on stuff that happens in the channel?

Not necessarily, you can keep a queue of actions to do on the next message received, akin to the unix self-pipe trick for signal handling.

> Can't we at least be allowed to issue a SUBSCRIBE command?

I just showed you you are  allowed to by going through the unsafe `.call` API.

> After all, the Redis response for SUBSCRIBE is pretty specific and cannot be mistaken for the response to any other command.

Unfortunately that's far from being as simple as you suggest it is.

**Comment by alxx** [comment]
OK. Thank you for the clarifications.

**Comment by YouRNotPaulChan** [comment]
Maybe you can stop and restart like this, but if there is a better way, please let me know
```
    begin
      @redis.subscribe("execute_log") do |on|
        on.message do |_channel, message|
          if message == "exit"
            puts "exiting execute log listen"
            @redis.unsubscribe("execute_log")
          elsif message == "restart"
            puts "Restart execute log listen"
            @redis.unsubscribe("execute_log")
            raise SomeError, 'restart'
          else
            puts "Receive msg: #{message}"
            # do something
          end
        end

        on.unsubscribe do |channel, _subscriptions|
          bp "Unsubscribed from #{channel}, GoodBye!"
        end

        on.subscribe do |channel, subscriptions|
          puts "Subscribed to ##{channel} (#{subscriptions} subscriptions)"
        end
      end
    rescue SomeError => e
      e.message
      retry
    end
```
