### ISSUE TITLE
Redis wildcard delete

### ISSUE THREAD

**Issue by sm2017** [redis/redis-rb#696]
Sorry for opening issue here , I open a ticket before here https://www.reddit.com/r/redis/comments/6b8o64/redis_wildcard_delete/ but no body replies

I design an automatic sql result cache system , it cache the result of queries using ```SET``` command and retrieve using ```GET``` (It is not based on user , many user can use shared cache and a shared cache can be deleted by some one)

Some time I must remove cached result for example , assume you search username redis and it cached and not exists , when you register this username , I must ```DEL``` or ```EXPIRE``` cached because some one may be searched again , I use search:redis as key and I know in delete step that I must delete this key as redis is passed as argument

But in complex cases , some this when a changes is applied to database , it may be affect many many keys in many namespaces , for example (ONLY AN EXAMPLE) assume we have table ```user``` , ```favorite_color``` and we cache in the following way

**NAMESPACES:**

- user:user_id => which caches user details like username , first name , ...
- user:favorites:user_id => which caches what colors one specific user favorites (```User #1``` => red,green,bue)
- colors:user:color_name => which caches who favorites the color (blue => ```User #1```,```User #5```,```User #9```)

So if an user add / delete or change favorites color many keys must be deleted from cache

At first we have these keys in cache

- user:1
- user:2
- user:3
- user:favorites:1 => (blue)
- user:favorites:2 => (blue,red)
- user:favorites:3 => (green,yellow)
- colors:user:blue => (1,2)
- colors:user:green => (3)
- colors:user:red => (2)
- colors:user:yellow => (3)

 

So when ```user #1``` favorites yellow really user:favorites:1 and colors:user:yellow is affected but in my automated system sometime (not always - exactly 130 cases from 2000 queries) , when a changes is applied , I don't know exactly which key must be deleted , Assume we have a function that must delete keys , so in the above mentioned example assume my function know who change database (```user #1```) but don't know what color? [no color argument is passed and it is not possible or heavy cost to pass color] , So the function is forced to delete user:favorites:1 and all keys matched colors:user:*

I use asterisk symbol to show I need a ```SCAN``` and ```DELETE``` , What is the best way to wildcard delete ?

 

I know I can use LUA script to ```SCAN``` and iterate over keys then ```DELETE``` , but in redis document , I see Atomicity of lua scripts that means no other script or Redis command will be executed while a script is being executed.

1- If I have 10 million keys in my redis and I have to wildcard delete frequency (100-1000 per minutes) , is it possible in practice?

2- Is there any alternative way? Now I use ```SCAN``` and ```DELETE``` in my logic side and I have my troubles(Many RAM consumes in my logic)

3- Do you think this cache system is a wrong ?

4- Is there any advantage to use ```EXPIRE``` instead of ```DELETE``` ? or not?

**Comment by badboy** [comment]
Two possibilities: Keep track of all stored keys and do the filtering in your clients. Or use expires and deal with stale caches.

Whatever you do, if you reach for pattern-matching operations in Redis you should look for an alternative in the way you do it or something other than Redis.

This bugtracker is not for general purpose discussions on Redis use cases. Your post to the subreddit is just a day old and it was a weekend, so maybe stay calm a bit and wait for more people to wake up and help.
You can also try the [mailing list](http://groups.google.com/group/redis-db).
