### ISSUE TITLE
AWS Elasticache/Redis Cluster Support

### ISSUE THREAD

**Issue by Stickiler** [redis/redis-rb#699]
We're currently working with AWS Elasticache, and we're running into an issue where the endpoint is returning an error with message MOVED. Looking at the Redis documentation, the client library is supposed to use the MOVED error to retrieve and follow the correct endpoint url for the request, but redis-rb doesn't appear to be doing so.

Is there a configuration option I'm missing, which enables it, or is this something that isn't yet supported?

**Comment by badboy** [comment]
There is no native support for Redis Cluster in redis-rb and at this point we don't have any plans to integrate it.
There's a [minimal implementation on top available](https://github.com/antirez/redis-rb-cluster). It might need a bit more work to be truly production-ready, but it should already handle most cases.
