### ISSUE TITLE
Redis cluster fails

### ISSUE THREAD

**Issue by nginxsantos** [redis/redis-rb#700]
My redis cluster creation fails on RHEL.

Looking at the error, I think I need this client library. How do I install this?

I have already installed rubygems:
sudo yum install rubygems
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Package rubygems-2.0.14.1-29.el7.noarch already installed and latest version
Nothing to do

Redis Cluster creation fails:
-----------------------------
src/redis-trib.rb create --replicas 1 10.37.14.30:7000 10.37.14.30:7001 10.37.14.30:7002 10.37.14.30:7003 10.37.14.30:7004 10.37.14.30:7005
/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- redis (LoadError)
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from src/redis-trib.rb:25:in `<main>'

**Comment by badboy** [comment]
[As I told you twice on the mailing list already](https://groups.google.com/d/msg/redis-db/yZXS7PHAyQI/D7s2UXetAQAJ), you need to install the actual redis rubygem (redis-rb).
