### ISSUE TITLE
Redis keeps trying to connect to local host when deployed to heroku

### ISSUE THREAD

**Issue by EsdrasEtrenne** [redis/redis-rb#707]
I have a rails app deployed to heroku and I cant for the life of me figure out why it kees wanting to deploy to the local. I do not even have localhost:6379 anywhere in my code for the front end (react native) or the back end which is my Rails API.

This is the error I get any time I have a new broadcast:
```
Completed 500 Internal Server Error in 111ms (ActiveRecord: 47.1ms)
Redis::CannotConnectError (Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)):
```

Application.yaml:
```
gmail_username: "<email_address>"
gmail_password: "<password>"
AWS_ACCESS_KEY: "<access_key>"
AWS_SECRET_KEY: "<secret_key>"
AWS_BUCKET: "<my_s3_app_bucket>"
REDIS_URL: "<redis_url>"
```
Cable.yaml:
```

production:
  adapter: redis
  url: <long_url_address>
  host: <host_from_url>
  port: <port_from_url>
  password: <password_from_url>
Production.rb:
```

  config.action_cable.allowed_request_origins = ["https://lynx-v1.herokuapp.com/"]
  config.action_cable.url = "wss://lynx-v1.herokuapp.com/cable"
  config.web_socket_server_url = "wss://lynx-v1.herokuapp.com/cable"
(i set both action cable and web socket just to test which worked, no matter which i go with i still get the error)

/config/initializers/redis.rb:

```
  require "redis"

    uri = URI.parse(ENV["REDIS_URL"])
    $redis = Redis.new(
                :url => ENV["REDIS_URL"],
              )
```
I dont know what is going on. Is it some kind of default that makes Redis look for local host 6379? I follow the steps step by step and I keep getting this error.

Any help would be very appreciated

I followed the heroku redis steps on their website:
https://devcenter.heroku.com/articles/heroku-redis

And so I have the environment variables set on heroku but after all this time it is still trying to connect to the local host

**Comment by badboy** [comment]
This is _not_ an issue with this library, but with your configuration.

As mentioned [in the other issue you opened](https://github.com/antirez/redis/issues/4149) your configuration lacks the proper settings somewhere.
I don't know ActionCable or the current Rails configuration, so I can't really help you with it.

**Comment by mmplisskin** [comment]
We are having this same issue @EsdrasEtrenne and did NOT see any connections other than to the REDIS_URL, did you manage to resolve?
