### ISSUE TITLE
How can I call georadius with options?

### ISSUE THREAD

**Issue by BenjaminKim** [redis/redis-rb#711]
I would like to call [georadius](https://redis.io/commands/georadius) command with `count` and `sort` options.
But it looks like the option is not yet available. Is there a way?

```
2.4.1 :022 > $redis.georadius(
    'Addresses', '127.0292978', '37.4923661', 2, 'km', count: 1, asc: true
)
Redis::CommandError: ERR syntax error
	from (irb):22
```

**Comment by id4coding** [comment]
I too absolutely need GEO features of Redis for our Rails server. May I know when these feature will be available or how to get the GEO commands to work in Ruby / Rails through this gem?

**Comment by badboy** [comment]
Currently there's no special handling for `geo*` commands implemented, you therefore need to pass arguments one-by-one, e.g.:

```ruby
$redis.georadius('Addresses', '127.0292978', '37.4923661', 2, 'km', 'count', 1, 'asc')
```

**Comment by ViTVetal** [comment]
I tried `.georadius($ONLINE_DRIVERS_LOCATIONS, 
                                                    start_location.latitude, 
                                                    start_location.longitude,
                                                    10, 'km',  count: 10)`

it works for any values of count but for 10 return 

`[Redis::CommandError - ERR syntax error]: /home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis/client.rb:124:in `call' | /home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis.rb:2762:in `block in georadius' | /home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize' | /home/vit-vetal-/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize' | /home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
`
