### ISSUE TITLE
How to support both 3.3 and 4.0?

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#713]
Hi folks, I'm not sure what to do here.

In 3.3.3, I call `Redis.new.client`.  In 4.0 I call `Redis.new._client`.  It's impossible to support both versions without a messy version check.  Is it possible to get a 3.3.4 release with an alias for _client or am I supposed to drop support for 3.x?  Should I monkeypatch in `_client`?  Advice appreciated.

For context, this is what I'm doing:

https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web/helpers.rb#L151

**Comment by mperham** [comment]
Alternatively, if there is a better/easier API to get the URL of the Redis server in 3.3/4.0, let me know.

**Comment by djanowski** [comment]
Yeah we'll fix it

**Comment by djanowski** [comment]
3.3.4 and 4.0.1 include `Redis#connection` which is a simple hash that provides the introspection you need.
