### ISSUE TITLE
connecting to Redis in a docker container

### ISSUE THREAD

**Issue by amiracam** [redis/redis-rb#714]
hi, have Redis setup at work on a linux instance which works fine. Today I tried setting up a Redis container which starts and I then tried using the same Ruby test script I had used to test the Linux instance (successfully at work)  at home  which fails with the following stack. 

it fails upon attempting to connect i.e.

```
require 'redis'

HOST = '192.168.99.100﻿'
PORT = 32768

redis = Redis.new(host: HOST, port: PORT)
redis.ping 'hello'
```

the host / port above are the exposed host / port provided by the Docker container

```
/Users/charles/.rvm/rubies/ruby-2.3.0/bin/ruby "-e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift)" /Users/charles/IdeaProjects/TestRedis/src/testRedis.rb
/Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/connection/ruby.rb:210:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/connection/ruby.rb:210:in `connect'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/connection/ruby.rb:293:in `connect'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:334:in `establish_connection'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:99:in `block in connect'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:291:in `with_reconnect'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:98:in `connect'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:363:in `ensure_connected'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:219:in `block in process'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:304:in `logging'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:218:in `process'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis/client.rb:118:in `call'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis.rb:771:in `block in set'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis.rb:45:in `block in synchronize'
	from /Users/charles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis.rb:45:in `synchronize'
	from /Users/charles/.rvm/gems/ruby-2.3.0/gems/redis-4.0.0/lib/redis.rb:767:in `set'
	from /Users/charles/IdeaProjects/TestRedis/src/testRedis.rb:6:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

**Comment by badboy** [comment]
For some reason or another your network setup is kinda broken. `getaddrinfo` tried to resolve the given host, which in your case seems to be an IP.
This does not look like a problem of `redis-rb`.
Can you `telnet` to that IP and port?

**Comment by amiracam** [comment]
agreed, its not a redis-rb per se issue but figured you might have tested against docker and thus experienced the problem. Docker i.e. Kitematic on Mac will generate docker containers on either localhost or 192.168.99.100﻿, whether its localhost or 192.168.99.100﻿ , I can't find a way of controlling that. 

This morning Kitematic decided to use localhost and redis-rb connected fine to the server within the docker container, redid-rb has also connected fine to an IP specified node within our office network, but again fails when docker sets up to 192.168.99.100﻿.

Mind you it does the same for the Postgres container i.e. switch around IPs  but in that case I am able to connect either way.

thanks

**Comment by badboy** [comment]
Check what interface Redis is configured to listen to. Could be that it just listens on 127.0.0.1 and is therefore not reachable outside of the container.
