### ISSUE TITLE
Errno::ETIMEDOUT: Connection timed out

### ISSUE THREAD

**Issue by dabhishek** [redis/redis-rb#718]
We have enabled tcp_keepalive setting to 10 sec recently, after which connection numerous random timeout errors have started occurring. There is no common pattern as such, and this error was never seen before the keepalive was enabled. We have a timeout of 5 seconds enabled, and don't see that timing out. Have been observing the connections with netstat command from one of the app instances, but don't see any stale connections there, and not reproducible. 

Also verified with redis latency, and latency history command to see if there is a network issu, nothing insignificant. I somehow feel there is something to do with the configuration, as errors are on different redis instances. 

Any help is appreciated. 

Our connection object is:
$redis = Redis.new(:host => config["host"], :port => config["port"], :timeout => 5, :tcp_keepalive => 10)

Gem version: 3.3.1.
Ruby is 2.2.0.

Typical stack trace of the exception is shown below. 

…by/2.2.0/gems/redis-3.3.1/lib/redis/connection/
ruby.rb:  95:in `write_nonblock'
…by/2.2.0/gems/redis-3.3.1/lib/redis/connection/
ruby.rb:  95:in `_write_to_socket'
…by/2.2.0/gems/redis-3.3.1/lib/redis/connection/
ruby.rb: 115:in `block in write'
…by/2.2.0/gems/redis-3.3.1/lib/redis/connection/
ruby.rb: 114:in `loop'
…by/2.2.0/gems/redis-3.3.1/lib/redis/connection/
ruby.rb: 114:in `write'
…by/2.2.0/gems/redis-3.3.1/lib/redis/connection/
ruby.rb: 358:in `write'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 271:in `block in write'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 250:in `io'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 269:in `write'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 228:in `block (3 levels) in process'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 222:in `each'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 222:in `block (2 levels) in process'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 367:in `ensure_connected'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 221:in `block in process'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 306:in `logging'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 220:in `process'
…r_gems/ruby/2.2.0/gems/redis-3.3.1/lib/redis/
client.rb: 120:in `call'
…/bundler_gems/ruby/2.2.0/gems/redis-3.3.1/lib/
redis.rb: 862:in `block in get'
…/bundler_gems/ruby/2.2.0/gems/redis-3.3.1/lib/
redis.rb:  58:in `block in synchronize'
                   /usr/local/lib/ruby/2.2.0/
monitor.rb: 211:in `mon_synchronize'
…/bundler_gems/ruby/2.2.0/gems/redis-3.3.1/lib/
redis.rb:  58:in `synchronize'
…/bundler_gems/ruby/2.2.0/gems/redis-3.3.1/lib/
redis.rb: 861:in `get'
…kit/releases/20170920095226/lib/redis/
redis_wrapper.rb:  11:in `perform_redis_op'
(eval):17:in `block in spam_watcher_counter'

**Comment by M034B5** [comment]
@abhishekops  how did you manage to solve this?

**Comment by abhishekops** [comment]
It was due to low limit for our connection pool for workers. Try increasing your connection pool.
