### ISSUE TITLE
Release 3.3.4 silently drops support for Ruby 1.8

### ISSUE THREAD

**Issue by zts** [redis/redis-rb#719]
Commit 07d04dee5e822364e47501dc68b8a71dd9cd833c makes a change which uses Ruby 1.9 hash literals, causing this release to fail on Ruby 1.8.

The changelog for 4.0 documents dropping Ruby 1.8 support as a breaking change, so I figure this was not intentional...

**Comment by djanowski** [comment]
It wasn't. Thank you!

**Comment by djanowski** [comment]
Released 3.3.5, yanked 3.3.4.

**Comment by macfanatic** [comment]
3.3.5 isn't yet showing on rubygems.org, has it been pushed?

<img width="542" alt="screen shot 2017-09-28 at 3 31 51 pm" src="https://user-images.githubusercontent.com/162970/30986666-308f1036-a462-11e7-9bad-51627df4ebcf.png">

**Comment by djanowski** [comment]
`gem-release` had timed out, sorry. It's out now. Thanks.

**Comment by macfanatic** [comment]
Thanks!
