### ISSUE TITLE
Set Redis.current default URL

### ISSUE THREAD

**Issue by ZhaofengWu** [redis/redis-rb#722]
It looks like `Redis.current`, when there is no Redis instance, calls `Redis.new` without any parameter, which defaults the URL to `localhost`, which is not what I want. So is there a way to set a default URL for `Redis.current`? Granted, I could use `Redis.new` all the time and supply the URL, but I am afraid that that would create many unnecessary instances.

**Comment by badboy** [comment]
You can create a new instance and then set the current

```ruby
r = Redis.new
Redis.current = r
```
