### ISSUE TITLE
Documentation for Redis::Distributed

### ISSUE THREAD

**Issue by samuelebistoletti** [redis/redis-rb#727]
Hi,
I noticed that there is a module named Redis Distributed, that is not documented. Anyone can please explain me what is it meant for? It a client module for Redis Cluster?

@antirez maybe you can give me some advice on how to use Redis Cluster from inside a Ruby on Rails app, please?

thanks

**Comment by badboy** [comment]
`Redis::Distributed` provides client-side sharding to multiple Redis backends. It pre-dates Redis Cluster. And it is sadly not documented properly.
It does not work with Redis Cluster. There's currently no direct support for Cluster in this library.
There exists [redis-rb-cluster](https://github.com/antirez/redis-rb-cluster), which is a minimal wrapper around the lib to provide cluster support and probably a good starting point if you want to use Redis Cluster.

**Comment by samuelebistoletti** [comment]
Ok thanks!
