### ISSUE TITLE
Is example of unicorn config out of date?

### ISSUE THREAD

**Issue by kuzukuzu** [redis/redis-rb#751]
https://github.com/redis/redis-rb/blob/d75708f6e05d9bba7dfec65880f9a55252f3fd2a/examples/unicorn/unicorn.rb#L5-L20

In above sample, it says reconnection is needed after forking.
But it seems reconnection is fired when forking detected.

Is reconnection really needed?

**Comment by mperham** [comment]
You must reconnect after fork or configure `inherit_socket`:

```ruby
          unless inherit_socket? || Process.pid == @pid
            raise InheritedError,
              "Tried to use a connection from a child process without reconnecting. " +
              "You need to reconnect to Redis after forking " +
              "or set :inherit_socket to true."
```

If reconnection_attempts is set to 0, that exception will be raised.  Otherwise it will be swallowed by the reconnect logic.  So... safer to disconnect explicitly.

**Comment by kuzukuzu** [comment]
That makes sense.
Thanks.
