### ISSUE TITLE
Use Redis > 3.2.1 on GCP (Google Cloud Platform)

### ISSUE THREAD

**Issue by CarolHsu** [redis/redis-rb#767]
GCP does [block some Redis commands](https://cloud.google.com/memorystore/docs/reference/redis-configs) such as `CLIENT`.

According to the doc (if I am not misunderstanding), the settings can't be modified, but since this [PR](https://github.com/redis/redis-rb/pull/514/files#diff-597c124889a64c18744b52ef9687c572R97), when redis starts to connect it must call `CLIENT` command. 

A bunch of gems relies on Redis gem, which means GCP apps can't run Redis 4 or newer versions. Is there any good suggestion?

**Comment by byroot** [comment]
According to the code, `CLIENT` is only issued if you passed a `id: ` option when instantiating the Redis client.

Can't you just not pass the option?

**Comment by CarolHsu** [comment]
@byroot well it's hard to say, I found this issue because sidekiq 5, and I believe it's impossible to ask gems avoiding to pass `id:`, so I'd like to know if there's good idea to get over this constraint 😅

**Comment by byroot** [comment]
Then just instantiate the Redis connection yourself: https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control

**Comment by CarolHsu** [comment]
Wow cool @byroot you're awesome!
