### ISSUE TITLE
read_timeout for Redis::Distributed

### ISSUE THREAD

**Issue by fertobar** [redis/redis-rb#773]
based on https://github.com/redis/redis-rb/pull/709, I'm trying to set **read_timeout** for **Redis::Distributed** in  **4.0.1**, but according some metrics it seems that the setting is ignored

It's posible to set *connect_timeout* , *read_timeout* and *write_timeout* for Redis::Distributed in 4.0.1 ?

Could you provide an example for that custom settings?

**Comment by byroot** [comment]
This way: `Redis::Distributed.new(%w(redis://localhost), read_timeout: 1.3)`


Demo: 
```ruby
>> Redis::Distributed.new(%w(redis://localhost), read_timeout: 1.3).nodes.first.instance_variable_get(:@client).read_timeout
=> 1.3
```

**Comment by fertobar** [comment]
ok, thanks for the help @byroot
