### ISSUE TITLE
Running redis on the #all? block returns nil

### ISSUE THREAD

**Issue by hazi** [redis/redis-rb#787]
There was a cryptic move when using Redis with Rails.

```ruby
redis = Redis.new(url: 'redis://localhost:6379/0')
(0..0).all? { |_| redis.get('A'); false } #=> nil
```

I could not identify the specific cause.
So, I prepared a reproduction environment.

https://circleci.com/gh/hazi/rails_all_method_bug_sample/6
https://github.com/hazi/rails_all_method_bug_sample

Could you know the cause of this bug?

**Comment by byroot** [comment]
Hum, this is very very intriguing. A couple observations:

  - Can't repro on MRI 2.3.1
  - Can't repro if Rails isn't loaded
  - The only way I managed to make `all?` return `nil` was with `all? { break }`

I'm thinking this must be an MRI bug, but I'd like to reduce the repo step more.

**Comment by hazi** [comment]
Thank you!!
We build a reproduction environment of MRI v 2.3.1 and report a bug.

**Comment by hazi** [comment]
This bug have already been fixed
https://bugs.ruby-lang.org/issues/15105
