### ISSUE TITLE
Redis Cluster in broken state after resharding

### ISSUE THREAD

**Issue by Kaol-Fu** [redis/redis-rb#791]
Hello,

This issue caused a lot of headaches for me. I have tried both 4.0.2 and 4.0.3 version.

So I have the following setup:
redis-server: 4.0.1
ruby: 2.5.3
redis.rb: 4.0.2/4.0.3

Replication steps:
With this version try the cluster tutorial where you reshard the cluster so that you also move a key.

the exception that I get is the following:

> Moving slot 6918 from 172.18.0.155:7013 to 172.18.0.156:7020:
> [ERR] Calling MIGRATE: ERR Syntax error, try CLIENT (LIST | KILL | GETNAME | SETNAME | PAUSE | REPLY)

I have noticed that the output from the command has one more colon after the destination port number. Is that the problem?

**Comment by byroot** [comment]
4.0.x doesn't have cluster support. It has been added in `4.1.0.beta1`.

**Comment by supercaracal** [comment]
Are these related?

* https://github.com/antirez/redis/issues/3199
* https://github.com/antirez/redis/issues/4272
* https://github.com/antirez/redis/issues/5029

**Comment by byroot** [comment]
Oh, I see it now. Yeah `#client` doesn't do the same thing than in 3.x.

The 4.x release whole point was to deprecate access to the client object through `#client`, so I'm not sure it makes sense to revert that back.

**Comment by byroot** [comment]
Given https://github.com/antirez/redis/commit/d222eda9f089f6605d755777c32132cb8cad76c9 I don't think it's worth putting the backward compatibility code back in place.
