### ISSUE TITLE
Redis Cluster Documentation

### ISSUE THREAD

**Issue by CaDs** [redis/redis-rb#796]
I saw that cluster support was merged and tagged on 4.0.3 version but I see no documentation nor samples about how to use it.

Is `Redis::Cluster` ready for use?
If so, is any documentation about how to use a Redis cluster with `redis-rb` gem available somewhere?

Thanks a lot.

**Comment by CaDs** [comment]
@byroot Thanks a lot for the reply and for the example.

Understood, we will keep using it four our development and testing environments, but for now, we will stay away from it in production.

I will report any bugs we might be able to find.
For now, I will be closing this issue then.

Again, thanks a lot.

**Comment by byroot** [comment]
> I will report any bugs we might be able to find.

Please also report if it works for you.

**Comment by supercaracal** [comment]
I wrote wiki page. https://github.com/redis/redis-rb/wiki/Cluster-mode
