### ISSUE TITLE
Georadius with "count: 10" option

### ISSUE THREAD

**Issue by ViTVetal** [redis/redis-rb#806]
I wrote [here](https://github.com/redis/redis-rb/issues/711#issuecomment-442429054) but didn't get any response.

Look like you added changes to geo realted things in 4.0.2. 

`.georadius($ONLINE_DRIVERS_LOCATIONS, 
                                                    start_location.latitude, 
                                                    start_location.longitude,
                                                    10, 'km', 'count', 10, 'asc')`

code above works correct with version 4.0.1. 

In version 4.0.3: 
`.georadius($ONLINE_DRIVERS_LOCATIONS, 
                                                    start_location.latitude, 
                                                    start_location.longitude,
                                                    10, 'km', sort: :asc,  count: 10)`

it works for any values (0, 1, 2..9 and any value greater then 10)  of **count** but for 10 throw 

```
[Redis::CommandError - ERR syntax error]:
/home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis/client.rb:124:in `call'
/home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis.rb:2762:in `block in georadius'
/home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
/home/vit-vetal-/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/vit-vetal-/.rvm/gems/ruby-2.5.0/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
```

**Comment by byroot** [comment]
I tried reproducing this without success. Could you provide a minimal reproduction script please?

**Comment by byroot** [comment]
No repro, so closing.
