### ISSUE TITLE
Redis does not check ulimit for changes after startup

### ISSUE THREAD

**Issue by azilber** [redis/redis-rb#809]
Using Redis 5.0.2 running as pid 8353
cd /proc/8353/
# cat limits
Max open files            10240                10240                files

> config set maxclients "20000"
(error) ERR The operating system is not able to handle the specified number of clients, try with 10208

echo -n "Max open files=65536:65536" > limits
(error) ERR The operating system is not able to handle the specified number of clients, try with 10208

# cat limits
Max open files            65536                65536                files

**Comment by byroot** [comment]
Can you explain how this is related to the Ruby client?

**Comment by azilber** [comment]
Not at all.  This is related to opening a ticket at 4am.  👍
