### ISSUE TITLE
irb port display wrong when using sentinel

### ISSUE THREAD

**Issue by in4mer** [redis/redis-rb#818]
Hi,

When connecting to a redis group using a non-standard port when using sentinel, the port displays incorrectly while still serving requests:

```
irb(main):001:0> require 'redis'
=> true
irb(main):002:0> rc = Redis.new(url: "redis://gc-imdb1", sentinels: [ { host: "gc-imdb1", port: 26379 } ], role: :master)
=> #<Redis client v4.1.0 for redis://gc-imdb1:6379/0>
irb(main):003:0> rc
=> #<Redis client v4.1.0 for redis://gc-imdb1:6379/0>
irb(main):004:0> rc.ping
=> "PONG"
irb(main):005:0> rc.set("foo", "stuff")
=> "OK"
```

This group is uniforming running on a port different from standard.

**Comment by supercaracal** [comment]
Hi,

It seems that the display is changed after establishing connection by calling any command.

```
irb(main):001:0> r = Redis.new(host: 'master1', sentinels: [{ host: '127.0.0.1', port: 6400 }])
=> #<Redis client v4.1.0 for redis://master1:6379/0>
irb(main):002:0> r.ping
=> "PONG"
irb(main):003:0> r
=> #<Redis client v4.1.0 for redis://127.0.0.1:6381/0>
```

The `url` or `host` option is master-group-name when using sentinel. It seems that the `port` and `db` is dummy. I'd say that there is certainly a bit confusing but there might be no serious damage.

We're able to implement a workaround but should we separate the master-group-name to another option? (e.g. `master_group_name` ) :thinking:

**Comment by in4mer** [comment]
How interesting.. thank you for figuring that out and replying.

I did verify that changing the lookup from url to group-name using host also exhibited the same behavior as described..  it just seems strange to me that, in the process of contacting a sentinel to find out what ip:port the appropriate group-member is on, the object would display something silly.  Does the client lazy-load the connection information from the sentinel only when the first command is issued?

**Comment by supercaracal** [comment]
Yes, it does.

* [connector instantiation](https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/client.rb#L89-L91)
  * [master-group-name](https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/client.rb#L533)
* [connection establishment](https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/client.rb#L336-L337)
  * [resolving](https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/client.rb#L553-L564)
  * [masters or slaves](https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/client.rb#L591-L607)
* [command call](https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/client.rb#L224)
