### ISSUE TITLE
Parameter keys format is not consistent - ssl has to be symbol

### ISSUE THREAD

**Issue by piotr-sokolowski** [redis/redis-rb#823]
Hi,
Odd behavior: You can pass host or port as symbol or string but when it comes to ssl, it has to be symbol.
For example:
```
Redis.new('host' => App.redis_config['host'], 
          'port' => App.redis_config['port'], 
          'ssl' => App.redis_config['ssl']).get('test')
...
Redis::ConnectionError (Connection lost (ECONNRESET))
```
But this works
```
Redis.new('host' => App.redis_config['host'], 
          'port' => App.redis_config['port'], 
          ssl: App.redis_config['ssl']).get('test')
```

**Comment by byroot** [comment]
If anything, we should remove the string key support, simply because named arguments is the way forward.

So I don't think supporting string keys for the `ssl` parameter make sense.
