### ISSUE TITLE
Can I expect thread-safety if sharing a global `$redis = Redis.new(…)`?

### ISSUE THREAD

**Issue by henrik** [redis/redis-rb#826]
https://github.com/redis/redis-rb/issues/75 mentions redis-rb aims to be thread-safe since 2.2.

Does that thread-safety presuppose using a `Redis` instance per thread, or is it also supposed to be thread-safe if sharing the same instance, such as with `$redis = Redis.new(…)`?

**Comment by henrik** [comment]
Going by https://stackoverflow.com/a/34673035/6962 I guess `Redis.current` would be the recommended way to go, and I guess that also means that using a shared global variable does not come with thread-safety guarantees?

**Comment by byroot** [comment]
Redis connection do contain a mutex, so if multiple threads use the same connection you shouldn't have thread safety issues, if you do it's a bug.

However it's a rather poor way to use Redis in a threaded context.

Then you have `Redis.current` which will indeed use one connection per thread, however it makes it a bit hard to configure the connection, and it doesn't limit the amount of connections.

The best is always to use a thread pool, Sidekiq's doc have a nice example of how to do that using https://rubygems.org/gems/connection_pool : https://github.com/mperham/sidekiq/wiki/Using-Redis#complete-control

**Comment by henrik** [comment]
Thank you @byroot, appreciate it! We're changing away from it, but were curious if it was likely to be the reason for some issues we'd seen.

**Comment by leandromoreira** [comment]
@byroot just out of curiosity, how does `redis-rb` keeps the thread safety under the `multi` command usage:

```ruby
redis.multi
  # => "OK"
redis.set("key", "value")
  # => "QUEUED"
redis.incr("counter")
  # => "QUEUED"
redis.exec
  # => ["OK", 6]
```

I guess it has some internal states, what happens if some part of the application calls `inc` between `multi` and `set` in another process/thread?

**Comment by byroot** [comment]
It doesn't if you call it without a block: https://github.com/redis/redis-rb/blob/764778d6b51fea3aef93a5a7ece5beb341943133/lib/redis.rb#L2456

Yes it sucks...

> what happens if some part of the application calls inc between multi and set in another process/thread?

It's going to be executed inside your transaction...

**Comment by leandromoreira** [comment]
thank you very much @byroot the best way must be a connection pool https://github.com/mperham/connection_pool
