### ISSUE TITLE
hiredis now supports SSL

### ISSUE THREAD

**Issue by tjwallace** [redis/redis-rb#828]
SSL support in hiredis has been merged: https://github.com/redis/hiredis/pull/645

Relevant code: https://github.com/redis/redis-rb/blob/master/lib/redis/connection/hiredis.rb#L17
hiredis-rb issue: https://github.com/redis/hiredis-rb/issues/58

**Comment by espen** [comment]
Would just removing that line fix this or is there anything else that needs to be done?

**Comment by byroot** [comment]
redis-rb 5.0 now uses `redis-client` under the hood, which does have `hiredis` bindings with SSL support.
