### ISSUE TITLE
Calling to_a on Redis::Connection::TCPSocket hangs Ruby

### ISSUE THREAD

**Issue by ArturMoczulski** [redis/redis-rb#830]
## Environment

`ruby`: `v2.3.1`
`redis`: `v4.1.0`
`activesupport`: `v4.2.8`

## Steps to reproduce
```ruby
require 'redis'
redis = Redis.new(url: "redis://127.0.0.1:6379/")
redis.instance_variable_get("@client").instance_variable_get("@connection").instance_variable_get("@sock").to_a
```

## Expected outcome
`Redis::Connection::TCPSocket` converted into an array representation (purpose of a `to_a` method).

## Actual outcome
Ruby hangs, probably due to infinite recursion.

## Background
I came across this while working on Redis client serialization in our Rollbar SDK here: https://github.com/rollbar/rollbar-gem/blob/master/spec/rollbar/item_spec.rb#L682-L686. This becomes a problem when you try to use ActiveSupport JSON to serialize a Redis client instance:

1. `Object#as_json` in active_support/core_ext/object/json.rb#50 <- calls `as_json` on the `instance_values`

2. `Hash@as_json` in active_support/core_ext/object/json.rb#159 <- calls `as_json`

3. `Enumerable#as_json` in lib/active_support/core_ext/object/json.rb#128 <- calls `to_a` on a `Redis::Connection::TCPSocket` object

**Comment by ArturMoczulski** [comment]
Further debugging led me to understand that this is an issue coming from Ruby's `::Socket#to_a` which is failing in the same way as described above.

**Comment by ArturMoczulski** [comment]
I've brought up the issue on Ruby core's issue tracker: https://bugs.ruby-lang.org/issues/15636

**Comment by byroot** [comment]
As Shyouhei said it on MRI bug tracker, I don't think trying to serialize a socket into JSON make sense.

I believe it's your code that should ignore non-serializable stuff.

**Comment by ArturMoczulski** [comment]
Yes, it was explained to me that this is actually the expected behavior. Serializing a socket does make sense, but the way it's implemented just makes it a poor idea in this case.

`ActiveSupport` runs `as_json` on everything in a hash during the serialization which causes sockets to hang for extended periods of time. To ignore non-serializable stuff you have to override `as_json` for some classes which might have other unexpected side effects. It's hardly the ideal solution. But it's a good enough for me for now.
