### ISSUE TITLE
Redis cluster configuration is not compatible with redis-objects gem

### ISSUE THREAD

**Issue by suman-anand-grab** [redis/redis-rb#833]
I upgraded the redis-objects gem to latest version in order to support redis-rb with cluster mode. But it seems to have some issue during initialization. redis-objects works fine with non-cluster mode connections.

redis-objects - 1.4.3
redis-rb - 4.1.0
Rails - 5.1.1

Command - Redis.new(cluster:['redis://127.0.0.1:6379'])

Error - ArgumentError: wrong number of arguments (given 0, expected 1+)

Stacktrace - 

/grab/web-api/vendor/ruby/2.4.0/gems/redis-objects-1.4.3/lib/redis/base_object.rb:4:in `initialize'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:60:in `new'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:60:in `assign_node_key'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:55:in `block (2 levels) in build_slot_node_key_map'", "/grab/web-api/vendor/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/core_ext/range/each.rb:5:in `each'", "/grab/web-api/vendor/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/core_ext/range/each.rb:5:in `each'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:55:in `block in build_slot_node_key_map'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:54:in `each'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:54:in `each_with_object'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:54:in `build_slot_node_key_map'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster/slot.rb:14:in `initialize'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster.rb:118:in `new'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster.rb:118:in `fetch_cluster_info!'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis/cluster.rb:26:in `initialize'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis.rb:43:in `new'", "/grab/web-api/vendor/ruby/2.4.0/gems/redis-4.1.0/lib/redis.rb:43:in `initialize'"

**Comment by supercaracal** [comment]
* https://github.com/redis/redis-rb/blob/v4.1.0/lib/redis/cluster/slot.rb#L60
* https://github.com/nateware/redis-objects/blob/v1.4.3/lib/redis/set.rb

oh... I understand. Just a few days please.

**Comment by suman-anand-grab** [comment]
Thanks @supercaracal for the quick fix. Waiting for the next release :)
