### ISSUE TITLE
Release 4.1.1 missing from changelog

### ISSUE THREAD

**Issue by viraptor** [redis/redis-rb#845]
Could we get an update in https://github.com/redis/redis-rb/blob/master/CHANGELOG.md for the 4.1.1 release, please?

**Comment by bartoszkopinski** [comment]
Side question: It looks like there is quite a few (possibly breaking) changes and new features in this patch version release - https://github.com/redis/redis-rb/compare/v4.1.0...v4.1.1 
Is redis following semver?

**Comment by byroot** [comment]
@viraptor done.

@bartoszkopinski please point them out, because I don't see it.

The only one we could argue about is `url: false` but IMO some compromise had to be made until it's time for another major version.
