### ISSUE TITLE
undefined method `grep_v' for #<Array:0x000000028c8690> 

### ISSUE THREAD

**Issue by byungjikroh** [redis/redis-rb#847]
'grep_v' added on v4.1.1 only supports Ruby 2.3.X and above. 

https://github.com/redis/redis-rb/blob/0984140669b3eddbc1afb0a29a351cf6552ae249/lib/redis.rb#L3372

There is an error 'undefined method `grep_v' for #<Array:0x000000028c8690>' on Ruby 2.2.6

**Comment by byroot** [comment]
The oldest ruby we officially support is 2.3, and even that one we won't support for very long because it's now EOL.

**Comment by byungjikroh** [comment]
If so, you need to update 'required_ruby_version' to 2.3.0 on redis.gemspec file. 
Without updating it, there is an error by updating gem under Ruby 2.3.0.

https://github.com/redis/redis-rb/blob/03e70f323400bb6e87653bec6eb62b43725d5f28/redis.gemspec#L36

**Comment by byroot** [comment]
Indeed, done: https://github.com/redis/redis-rb/commit/19c36ceee6a3b936d0fac5d7447b568885e8be0c
