### ISSUE TITLE
Rubydoc out of date and confusing

### ISSUE THREAD

**Issue by annzenkina** [redis/redis-rb#848]
https://www.rubydoc.info/github/redis/redis-rb/master/Redis

I was trying to call a `client` using `rubydoc` docs, and I found it very confusing since I can't do the same in the newest version of the library, but the docs are out of date. The version specified in `rubydoc` is 3.3.1 but I can see in your changelog that the latest one is 4.1.1.

I've seen in the ReadMe a link to the new website with documentation, but I found it much later. I wanted to raise an issue as it might be confusing for someone else.

do you think we should delete `rubydoc` then to avoid ambuguity. Thanks!

**Comment by byroot** [comment]
Not sure who has control over rubydoc, but I can't delete or update anything there.

That being said, the up to date version of the documentation is there: https://www.rubydoc.info/gems/redis

**Comment by annzenkina** [comment]
Thanks for your reply. I will close the issue now.
