### ISSUE TITLE
Error parsing URI with special chars in password

### ISSUE THREAD

**Issue by javierav** [redis/redis-rb#863]
Hi.

We have a problem with random passwords generated in a hosted Redis service and this gem. The service generate passwords like `sJ3RAYkWN8SlBu4y1+hpIGoNCdMlO+XQehqs=`. If we create the following redis url `redis://:sJ3RAYkWN8SlBu4y1+hpIGoNCdMlO+XQehqs=@myredisservice.net:6379` and pass it to `Redis.new` command, we get an error in password:

```
[1] pry(main)> redis = Redis.new(url: 'redis://:sJ3RAYkWN8SlBu4y1+hpIGoNCdMlO+XQehqs=@myredisservice.net:6379')
=> #<Redis client v4.1.2 for redis://myredisservice.net:6379/0>
[2] pry(main)> redis.set("mykey", "hello world")
Redis::CommandError: ERR invalid password
```

Investigating the source code, in [this](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L434) line you are using this code: 

```ruby
defaults[:password] = CGI.unescape(uri.password) if uri.password
```

It's an error? We must escape the URI? If it's the second case may be very interesant to put a note in README file about this for prevent future issues.

Thanks.

**Comment by pjmartorell** [comment]
I have the same issue with a Redis server hosted in Azure. Since this service is only generating passwords with this kind of special symbols this issue is quite annoying. By now the only way to solve it is setting the password as a separate attribute:
```ruby
redis = Redis.new(url: 'redis://myredisservice.net:6379', password: 'sJ3RAYkWN8SlBu4y1+hpIGoNCdMlO+XQehqs=')
```

**Comment by pjmartorell** [comment]
Related with `Password having special characters breaks URI format` #11. So the proposal is to do the following?

```ruby
Redis.new(url: "redis://:#{CGI.escape('bmnACylgoJhpWRksfFgf1JrTfcHBMkl+B61FemAgy7E=')}@myredisservice.net:6379").ping
```
Looks ugly as a hell :japanese_ogre:!

**Comment by pjmartorell** [comment]
Or an alternative, in case you are storing it as an env variable is to store the URL with the password escaped:

```ruby
redis = Redis.new(url: 'redis://:sJ3RAYkWN8SlBu4y1%2BhpIGoNCdMlO%2BXQehqs%3D@myredisservice.net:6379')
```
