### ISSUE TITLE
Connections dont seem to be closing

### ISSUE THREAD

**Issue by Deekor** [redis/redis-rb#869]
Ruby 2.6.3
Rails 5.2.3

I'm testing a private endpoint with one ping every 60 seconds:
```ruby
r = Redis.new
r.set('key', 'value')
r.quit
```

The connections seem to keep piling up until I hit my max connections error.

I've tried `r.close` and that just returns `nil`

If I fire up a rails console I can:
```ruby
r = Redis.new
r.set('key', 'value')
r.quit
r.get('key') #returns value, connection must not be closed?
```

What am I missing here? Is there something about redis connection I am not understanding?

**Comment by M034B5** [comment]
@Deekor how did you manage to solve this?

**Comment by paulslaby** [comment]
> @Deekor how did you manage to solve this?

It's going to reconnect when first using the connection.
