### ISSUE TITLE
Deleting a cache entry with Redis.new.del does not work if the entry was written using Rails.cache.write 

### ISSUE THREAD

**Issue by amrocco** [redis/redis-rb#870]
If you create the entry with Redis.new.set, #del works as expected:
```
Loading development environment (Rails 5.2.3)
[1] pry(main)> redis = Redis.new
=> #<Redis client v4.1.1 for redis://127.0.0.1:6379/0>
[2] pry(main)> redis.set('the_key', 'some value')
=> "OK"
[3] pry(main)> redis.get('the_key')
=> "some value"
[4] pry(main)> redis.del('the_key')
=> 1
[5] pry(main)> redis.get('the_key')
=> nil
```

If you create the entry with Rails.cache.write, then try to delete with #del, the operation is not successful:
```
[6] pry(main)> Rails.cache.write('another_key', 'some value')
=> "OK"
[7] pry(main)> Rails.cache.read('another_key')
=> "some value"
[8] pry(main)> redis.del('another_key')
=> 0
[9] pry(main)> Rails.cache.read('another_key')
=> "some value"
[10] pry(main)> exit

```

Not sure if this behavior is intentional or not, but I thought I'd open up an issue incase it is not.

**Comment by byroot** [comment]
First this doesn't have anything to do with redis-rb, as you show it's working fine.

What you *might* have a problem with is the cache adapter for Redis that you use, either the new standard one baked inside Rails or either https://github.com/redis-store/redis-activesupport

And either way, the likely cause is that the cache keys are prefixed or suffixed in some way, you can easily see that by doing a `KEYS`.

**Comment by amrocco** [comment]
![image](https://user-images.githubusercontent.com/3812281/63455726-545c3180-c41b-11e9-9da3-6b3576b0055a.png)

Thanks!
