### ISSUE TITLE
Redis::Client has no hgetall?

### ISSUE THREAD

**Issue by hron84** [redis/redis-rb#877]
I started to get this exception:

```
/usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:442:in `call_with_namespace': undefined method `hgetall' for #<Redis::Client:0x000055c290d866e0> (NoMethodError)
	from /usr/local/bundle/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:328:in `method_missing'
	from /usr/local/bundle/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing'
	from /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/scheduling_extensions.rb:121:in `persistent_schedules'
	from /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/scheduling_extensions.rb:71:in `all_schedules'
	from /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/scheduling_extensions.rb:66:in `reload_schedule!'
	from /usr/local/bundle/gems/resque-scheduler-4.4.0/lib/resque/scheduler/scheduling_extensions.rb:55:in `schedule='
```

I tried to dig deeper, and the raw (un-namespaced) redis client is also refuses to respond to `hgetall` method. Did you remove the support of this method?

EDIT:

If I try to create Redis client with `Redis.new(url: 'redis://redis:6379/0')` instead of `Redis::Client.new(url: 'redis://redis:6379/0')` then it responds to `hgetall`

**Comment by byroot** [comment]
`Redis::Client` never had a `hgetall` or any other command method. So no it wasn't removed.

It's just that for some reason you are trying to use a `Redis::Client` instance but what you want is a `Redis` instance.

**Comment by hron84** [comment]
@byroot what's the difference between them?

**Comment by byroot** [comment]
`Redis` is the public interface.

`Redis::Client` is an internal implementation detail you shouldn't have to know about.
