### ISSUE TITLE
Redis#queue is not thread safe

### ISSUE THREAD

**Issue by ioquatix** [redis/redis-rb#878]
https://github.com/redis/redis-rb/blob/master/lib/redis.rb#L96-L123

`Redis#queue` is not thread safe because you cannot assume it's safe to read from a hash table when it's also being modified.

Additionally, the hash uses a default constructor which means `Redis#queue` may actually modify the hash table.

So there are a number of issues with the implementation.

**Comment by byroot** [comment]
Thanks

**Comment by intale** [comment]
>Redis#queue is not thread safe because you cannot assume it's safe to read from a hash table when it's also being modified.

You can assume it is safe when using native, written in C, methods. So the only thing that looks meaningful about thread safety is the notice about default constructor.
