### ISSUE TITLE
Cluster support for db id.

### ISSUE THREAD

**Issue by gothrek22** [redis/redis-rb#883]
Hi,

it seems that redis-rb when connecting to clustered redis with cluster set in the constructor fails to connect if REDIS_URI has db set like so: redis://hostname:6379/1, where 1 is db id. It works without the parameter set.

Setting db id as a separate parameter ends with the same error, which is:

`Redis::CannotConnectError (Redis client could not connect to any cluster nodes)`

**Comment by supercaracal** [comment]
https://redis.io/topics/cluster-spec#implemented-subset

> Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed.

Should we handle invalid option?

**Comment by byroot** [comment]
> Should we handle invalid option?

I don't think so

**Comment by gothrek22** [comment]
lol. Seems I've been mislead by redis-cli as it seems to support the option.
