### ISSUE TITLE
Redis::FutureNotReady: Value will be available once the pipeline executes.

### ISSUE THREAD

**Issue by yooyiten** [redis/redis-rb#884]
This error is occasionally raised when trying to use the value of a future after a pipeline block, using version 4.0.1. Is this expected and is there a recommended best practice for handling this error and/or ensuring that the pipeline has executed before accessing the value?

The code looks something like

```
redis.pipelined do
  a_key = 'a_key_name'
  another_key = 'another_key_name'
  @a_key_exists = redis.exists(a_key)
  @another_key_data = redis.hmget(another_key)
end

x, y = @another_key_data.value
```

**Comment by asoong** [comment]
I ran into this as well. This answered it for me: https://stackoverflow.com/questions/41643360/how-to-use-redis-pipeline-in-ruby-for-a-loop

**Comment by yooyiten** [comment]
Ohhh interesting. Will try a refactor to use `mget` instead for retrieval. Thanks for the lead!

**Comment by yooyiten** [comment]
Actually that won't work for a hash scenario -- perhaps Lua scripting is the only alternative per https://stackoverflow.com/questions/3329408/is-there-mget-analog-for-redis-hashes

**Comment by byroot** [comment]
If it's all in the same hash you have `hmget` https://redis.io/commands/hmget

Anyway, pipelines are fine. If you get a `Redis::FutureNotReady` it simply means that you are trying to access the value inside a `pipeline` block, which is simply a programming mistake.

Look at the backtrace and find where the `pipeline do` block is.

**Comment by yooyiten** [comment]
The values are always being accessed outside the `pipeline` block and the strange thing is that the error is fairly infrequent. We had also been thinking it could be some transient issue causing a `RuntimeError` during the pipelined read.

**Comment by byroot** [comment]
> The values are always being accessed outside the `pipeline` block

Are you sure of that? A common mistake is to have two nested blocks, e.g.:


```ruby
def some_method
  redis.pipelined do
    # blah
  end
  
end

redis.pipelined do
  # do some stuff
  some_method
end
```

Can you show a backtrace?

**Comment by byroot** [comment]
> We had also been thinking it could be some transient issue causing a `RuntimeError` during the pipelined read.

That another possiblity, but when this happens the client raises an error, so it would mean that that error is silenced somewhere.

**Comment by yooyiten** [comment]
> That another possiblity, but when this happens the client raises an error, so it would mean that that error is silenced somewhere.

🤦‍♂ I took another look at the application code in question and looks like this is the case.

```
begin
  redis.pipelined do
    result_obj.instance_variable_set(@results, redis.hmget(blah, *fields))
    result_obj.instance_variable_set(@daily_results, redis.hmget(daily_blah, *fields))
  end
rescue StandardError => error
  # error silencing
end
```

Later on in another method:

`results = result_obj.instance_variable_get(@results).value`

So occasionally something goes wrong with the pipelined read and then we get the error later on when we try to use the `value`. Thanks @byroot !

**Comment by byroot** [comment]
Welcome.

**Comment by byroot** [comment]
BTW, I tend to prefer using the `pipelined` method return values for that reason:

```ruby
@foo, @bar = redis.pipelined do 
  r.get('foo')
  r.get('bar')
end
```
