### ISSUE TITLE
Cluster with auth connects and retrieves cluster nodes but without auth

### ISSUE THREAD

**Issue by zedtux** [redis/redis-rb#888]
I have a Rails application which uses this gem in order to connect to a single Redis instance with a password, where all is working fine.

I'm migrating Redis as a Redis Cluster, and therefore I have updated my config so that it no more passes `url: 'redis://:<password>@redis-host:6379/0'` but `cluster: ['redis://:<password>@a-redis-cluster-master-host:6379/0']` which works as the `Redis.new` returned this:

```
#<Redis client v4.1.3 for redis://10.244.5.253:6379/0 redis://10.244.7.251:6379/0 redis://10.244.7.252:6379/0>
```

But now, if I try to use it, it fails with a NOAUTH error :

```ruby
irb(main):005:0>redis = Redis.new(cluster: ['redis://:<password>@redis-cluster:6379/0'])
=> #<Redis client v4.1.3 for redis://10.244.5.253:6379/0 redis://10.244.7.251:6379/0 redis://10.244.7.252:6379/0>
irb(main):006:0> redis.ping
Traceback (most recent call last):
        1: from (irb):6
Redis::CommandError (NOAUTH Authentication required.)
irb(main):007:0> redis.auth '<password>'
=> "OK"
irb(main):008:0> redis.ping
=> "PONG"
```

So it seems that the password is used to open the connection and retrieve the cluster nodes, but then it is missing or not used to open the connection to the other nodes, something like that.

I tried to add the `redis.auth "<password>"` in my initialiser, but I still have the issue in my Rails app 😞.

Is there anything wrong am I doing? Can you please help me?

**Comment by zedtux** [comment]
> I tried to add the redis.auth "<password>" in my initialiser, but I still have the issue in my Rails app 😞.

Actually I had an old version of the code on my server. So adding the `redis.auth "<password>"` in the Redis initialiser seem to work.

**Comment by supercaracal** [comment]
This is a bug. I am sorry. I would like to fix it ASAP.

**Comment by supercaracal** [comment]
Thank you for your reporting.

**Comment by byroot** [comment]
@zedtux can you try master, just to confirm it properly fixes your issue?

**Comment by supercaracal** [comment]
:pray:

MEMO:
I debugged in my local like the follows:

```diff
$ diff -u /tmp/makefile.orig makefile 
--- /tmp/makefile.orig  2020-02-01 21:47:19.499437323 +0900
+++ makefile    2020-02-01 21:44:54.487897316 +0900
@@ -93,6 +93,8 @@
                        --cluster-node-timeout 5000\
                        --pidfile              ${TMP}/redis$$port.pid\
                        --port                 $$port\
+                       --masterauth           foobar\
+                       --requirepass          foobar\
                        --unixsocket           ${TMP}/redis$$port.sock;\
        done
```

```diff
$ diff -u /tmp/orchestrator.rb.orig test/support/cluster/orchestrator.rb 
--- /tmp/orchestrator.rb.orig   2020-02-01 21:49:42.471030101 +0900
+++ test/support/cluster/orchestrator.rb        2020-02-01 21:49:57.790988694 +0900
@@ -9,6 +9,7 @@
     raise 'Redis Cluster requires at least 3 master nodes.' if node_addrs.size < 3
     @clients = node_addrs.map do |addr|
       Redis.new(url: addr,
+                password: 'foobar',
                 timeout: timeout,
                 reconnect_attempts: 10,
                 reconnect_delay: 1.5,
```

```
$ make start_cluster
$ make create_cluster
$ bin/console
```

```
irb(main):002:0> r.ping
=> "PONG"
irb(main):003:0> r.get 'key1'
=> nil
irb(main):004:0> r.get 'key2'
=> nil
irb(main):005:0> r.get 'key3'
=> nil
```

```
$ make stop_cluster
```

**Comment by zedtux** [comment]
@byroot sure I will.

**Comment by zedtux** [comment]
@byroot I confirm it works :+1:
