### ISSUE TITLE
Our call is stuck in an endless loop in call_pipeline

### ISSUE THREAD

**Issue by RichardWingetImagineLearning** [redis/redis-rb#892]
This is a weird problem. I've searched far and low and can't get any traction. Any help would be much appreciated. I'm using Aws.ElasticCache.Redis and Sidekiq. My call just gets stuck and eventually times out. It's intermittent, so I can't predict when it will happen. I also can't find patterns around it. I've tried it with gem version 4.0.3 and 4.1.3 and with sidekiq 5.2.8 and 6.0.5 . Here's my call stack:

From redis 4.1.3 with sidekiq 6.0.5:

    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from gems/redis-4.1.3/lib/redis.rb:2462:in `block in multi'
    from gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
    from /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    from gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
    from gems/redis-4.1.3/lib/redis.rb:2454:in `multi'
    from gems/sidekiq-6.0.3/lib/sidekiq/client.rb:188:in `block in raw_push'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
    from gems/sidekiq-6.0.3/lib/sidekiq/client.rb:187:in `raw_push'
    from gems/sidekiq-pro-5.0.1/lib/sidekiq/batch/client.rb:40:in `raw_push'
    from gems/sidekiq-6.0.3/lib/sidekiq/client.rb:74:in `push'
    from gems/sidekiq-6.0.3/lib/sidekiq/worker.rb:243:in `client_push'
    from gems/sidekiq-6.0.3/lib/sidekiq/worker.rb:200:in `perform_async'

From redis 4.0.3 and sidekiq 5.2.8:

    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from (eval):26:in `call_pipeline'
    from gems/redis-4.0.3/lib/redis.rb:2366:in `block in multi'
    from gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
    from /usr/local/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    from gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
    from gems/redis-4.0.3/lib/redis.rb:2358:in `multi'
    from gems/sidekiq-5.2.8/lib/sidekiq/client.rb:184:in `block in raw_push'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
    from gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
    from gems/sidekiq-5.2.8/lib/sidekiq/client.rb:183:in `raw_push'
    from gems/sidekiq-pro-5.0.0/lib/sidekiq/batch/client.rb:40:in `raw_push'
    from gems/sidekiq-5.2.8/lib/sidekiq/client.rb:74:in `push'
    from gems/sidekiq-5.2.8/lib/sidekiq/worker.rb:149:in `client_push'
    from gems/sidekiq-5.2.8/lib/sidekiq/worker.rb:93:in `perform_async'

**Comment by byroot** [comment]
```
(eval):26:in `call_pipeline'
```
This is weird.

It should be something like:

```
from gems/redis-4.0.3/lib/redis/pipeline.rb:38:in `call_pipeline'
```

I suspect this method redefined by a monkey patch using `module_eval` or `class_eval` somewhere. If it's in your project if should be too hard to track down.

If it's in a dependency however, that might be a bit more tricky. You can tell bundler to install dependencies in a specific path, and try to grep for `call_pipeline`.

Either way I highly doubt this is a bug in `redis-rb`.

**Comment by RichardWingetImagineLearning** [comment]
Ah, that makes much more sense. I'll head down that route. Thank you!
