### ISSUE TITLE
XCLAIM exception with nil result

### ISSUE THREAD

**Issue by eadz** [redis/redis-rb#905]
XCLAIM can return a nil array result.  ( `[nil]` )
It's passed to `HashifyStreamEntries` which then calls `each_slice` on nil causing an exception. 

In REDIS, the following command can return an array with a nil element. 
```sh
"xclaim" "mystream" "default" "3734fd61-ec3f-4bc1-b59d-3719d8ae40be" "1" "1589669825174-0"`
1) (nil)
```

**Comment by eadz** [comment]
Closing until I can reproduce reliably.

**Comment by eadz** [comment]
So I haven't managed to write a failing test, and my PR fix is no good, but I'm pretty sure there is a bug in `HashifyStreamEntries`

( for reference: )
```ruby
HashifyStreamEntries = lambda { |reply|
    reply.map do |entry_id, values|
      [entry_id, values.each_slice(2).to_h]
    end
  }
```

Arrays can have nil elements. The `reply` coming into the `HashifyStreamEntries` that caused the error is `[nil]`. 

<img width="1123" alt="Screen Shot 2020-05-22 at 7 38 06 PM" src="https://user-images.githubusercontent.com/11939/82643689-161ec780-9c64-11ea-90f8-7495222a8656.png">

```
# current HashifyStreamEntries
reply = [nil]
HashifyStreamEntries.call(reply) # => NoMethodError (undefined method `each_slice' for nil:NilClass)
```

Personally, I don't care about nil results, so I am using a fix of `compact` following fix:

```ruby
HashifyStreamEntries = lambda { |reply|
    reply.compact.map do |entry_id, values|
      [entry_id, values.each_slice(2).to_h]
    end
  }
```

**Comment by eadz** [comment]
would a patch using compact be acceptable?

**Comment by byroot** [comment]
Not without a reproduction.

**Comment by eadz** [comment]
I thought I explained clearly how `HashifyStreamEntries` cannot handle an array with a nil value. 
It's self evident from the code. 

Is a reproduction necessary because you do not think Redis will return an array with a nil value? Even though that's the documented behavior?

**Comment by byroot** [comment]
> Even though that's the documented behavior?

That's not the documented behavior. What the documentation says is that it returns an Array, then points to the RESPv3 (which this library doesn't use) generic description of an array, and say that an array can contain a `nil`.

The documentation doesn't say that XCLAIM can return nil.

You have to understand that I can't do blind fixes like this. What is a fix for you might very well introduce a bug for others, hence why I need to be able to reproduce and understand the bug.

By the way, what driver do you use?

**Comment by eadz** [comment]
Fair enough, ok it took some time, but I've managed to write a script which reproduces the bug every time I run it. Running redis 5.0.7 btw. 

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org/"
  gem "redis"
end

def rs; (rand * 10**10).to_i.to_s(32); end

id = rs

puts "using stream '#{id}'"
redis = Redis.current
redis.xgroup(:create, id, 'a', "$", mkstream: true)

threads = []

jids = []

clients = [:a,:b,:c]

sizes = [1,4,8]

100.times do
  jids << redis.xadd(id, test: rs)
end

threads << Thread.new do
  redis = Redis.new
  10000.times do
    sleep rand / 10000
    redis.xreadgroup(:a, sizes.sample, id, ">", count: sizes.sample)
  end
end

threads << Thread.new do
  redis = Redis.new
  10000.times do
    sleep rand / 10000
    jid = jids.sample
    redis.multi do
      redis.xack(id, clients.sample, jid)
      redis.xdel(id, jid)
    end
  end
end

threads << Thread.new do
  redis = Redis.new
  10000.times do
    sleep rand / 10000
    redis.xclaim(id, :a, clients.sample, sizes.sample, jids.sample)
  end
end

threads.each(&:join)
```

**Comment by eadz** [comment]
Sorry it's a random script, but you can see that as I mentioned, XCLAIM can return a result like `[nil]`.

**Comment by byroot** [comment]
Thank you. I'll dig into that script.

**Comment by byroot** [comment]
Thank again for the script. I merge a slightly different patch: https://github.com/redis/redis-rb/pull/929

**Comment by eadz** [comment]
Hi, 
Can we reopen this issue: 

The reason I used `compact` is that it's an array, where some of the replies can be empty. 

`XCLAIM` can take multiple IDs, so can return an array like [something, nil, nil, something]

Here is a repoduction with your fix, same problem

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org/"
  gem "redis"
end

class Redis
  EMPTY_STREAM_RESPONSE = [nil].freeze
  private_constant :EMPTY_STREAM_RESPONSE

  HashifyStreamEntries = lambda { |reply|
    return []  if reply == EMPTY_STREAM_RESPONSE
    reply.map do |entry_id, values|
      [entry_id, values.each_slice(2).to_h]
    end
  }
end

def rs; (rand * 10**10).to_i.to_s(32); end

id = rs

puts "using stream '#{id}'"
redis = Redis.current
redis.xgroup(:create, id, 'a', "$", mkstream: true)

threads = []

jids = []

clients = [:a,:b,:c]

sizes = [10,20,30]

10000.times do
  jids << redis.xadd(id, test: rs)
end

threads << Thread.new do
  redis = Redis.new
  10000.times do
    sleep rand / 10000
    redis.xreadgroup(:a, sizes.sample, id, ">", count: sizes.sample)
  end
end

threads << Thread.new do
  redis = Redis.new
  10000.times do
    sleep rand / 10000
    jid = jids.sample
    redis.multi do
      redis.xack(id, clients.sample, jid)
      redis.xdel(id, jid)
    end
  end
end

threads << Thread.new do
  redis = Redis.new
  10000.times do
    sleep rand / 10000
    redis.xclaim(id, :a, clients.sample, sizes.sample, jids.sample, jids.sample, jids.sample, jids.sample)
  end
end

threads.each(&:join)
```

**Comment by byroot** [comment]
@eadz I see. Let's go with compact then, I pushed https://github.com/redis/redis-rb/commit/9fd381b18da20248a111cd9551354907c772a00a

**Comment by eadz** [comment]
Great, thank you!  And thanks for all your work on redis-rb too!
