### ISSUE TITLE
hexists?

### ISSUE THREAD

**Issue by danlo** [redis/redis-rb#927]
Greetings,

I was upgrading, and I saw the following message:

`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. 

Will you be also making this same modification to 

```hexists```

Regards,

Daniel Lo

**Comment by byroot** [comment]
`HEXISTS` isn't variadic, it only check a single field in a single hash https://redis.io/commands/hexists

So there isn't really any reason to at this stage.

**Comment by danlo** [comment]
For future readers:  variadic means that it accepts an indefinite number of arguments
