### ISSUE TITLE
Frequent errors: "Redis::ConnectionError: Connection lost (ECONNRESET)"

### ISSUE THREAD

**Issue by vitobotta** [redis/redis-rb#931]
Hi! I've opened an issue in Sidekiq as well since it's related https://github.com/mperham/sidekiq/issues/4626

I'm using DigitalOcean's managed Redis and am seeing the error in the subject frequently in Sidekiq's logs. Everything works apart from these errors every now and then. Sometimes more frequent, sometimes less frequent. 

I am having a hard time trying to get some help from DO. In the meantime, is there something I can do to help them investigate these issues with the gem? This is what I see in the logs when the error occurs:

```
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:270:in `rescue in io'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:262:in `io'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:274:in `read'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:126:in `block in call'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:243:in `block (2 levels) in process'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:384:in `ensure_connected'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
/app/vendor/cache/ruby/2.6.0/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
```

I've seen old issues about Redis and TLS, and in fact DigitalOcean's Redis uses TLS, but the thing is that the connections mostly work, it's just that I get these "Connection lost" errors randomly. What can I do to investigate or solve?

Thanks!

**Comment by vitobotta** [comment]
I am testing with reconnect_attempts set to 3. Let's see...

**Comment by vitobotta** [comment]
Seems to be working better.

**Comment by Bmorrical** [comment]
Hi @vitobotta how did you set "reconnect_attempts set to 3"?

**Comment by vitobotta** [comment]
@Bmorrical Like `config.cache_store = :redis_cache_store, { url: Settings.redis_cache_url, reconnect_attempts: 3, namespace: Settings.kube_namespace }`

**Comment by DavertMik** [comment]
@vitobotta I have this issue with DO hosted Redis as well, let's check this solution. If no, you are not the only one who faces this.

**Comment by JYorston** [comment]
👍  We're also seeing this but the app seems to be running absolutely fine. At a loss as to what the root cause is.

**Comment by pen-pal** [comment]
were you able to fix it?
if so how did you do it.

some of the jobs on my end goes to dead because of these failures.
