### ISSUE TITLE
ERR wrong number of arguments for hset command (Redis::CommandError) when calling with empty array

### ISSUE THREAD

**Issue by sgujrati-up** [redis/redis-rb#939]
We have been using [redic](https://github.com/amakawa/redic) gem for long time. Recently, we decided to switch to `redis-rb`. `redic` allows calling `hset` with `[]`. However, `redis-rb` throws `ERR wrong number of arguments for 'hset' command (Redis::CommandError)` error. When I call `hset` thru `redis-cli` with `[]`, it does work. So I expect it to work with `redis-rb` as well.

Can someone tell me why `redis-rb` throws this error when calling `hset` with empty array `[]`?

**Comment by byroot** [comment]
> When I call `hset` thru `redis-cli` with `[]`, it does work

I doubt so:

```
127.0.0.1:6379> hset somekey
(error) ERR wrong number of arguments for 'hset' command
```

`[]` has no meaning in redis-cli.

Now that this is said, redis-rb could silently not issue the command when you give it an empty collection.

**Comment by sgujrati-up** [comment]
This is what I meant when I said `when I call hset thru redis-cli with [], it does work`

Output from `redis-cli`
```
127.0.0.1:6379> hset mykey myfield
(error) ERR wrong number of arguments for 'hset' command
127.0.0.1:6379> hset mykey myfield []
(integer) 1
```

Output from `irb` when using `redis-rb`:
```
2.7.1 :001 > require "redis"
 => true 
2.7.1 :005 > redis = Redis.new(url: "redis://:pwd@localhost:6379")
2.7.1 :006 > redis.call("HSET", "mykey", "myfield", [])
Traceback (most recent call last):
       11: from /Users/sumeetgujrati/.rvm/rubies/ruby-2.7.1/bin/irb:23:in `<main>'
       10: from /Users/sumeetgujrati/.rvm/rubies/ruby-2.7.1/bin/irb:23:in `load'
        9: from /Users/sumeetgujrati/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        8: from (irb):6
        7: from /Users/sumeetgujrati/.rvm/gems/ruby-2.7.1/gems/redis-4.2.1/lib/redis.rb:104:in `call'
        6: from /Users/sumeetgujrati/.rvm/gems/ruby-2.7.1/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
        5: from /Users/sumeetgujrati/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
        4: from /Users/sumeetgujrati/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
        3: from /Users/sumeetgujrati/.rvm/gems/ruby-2.7.1/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
        2: from /Users/sumeetgujrati/.rvm/gems/ruby-2.7.1/gems/redis-4.2.1/lib/redis.rb:105:in `block in call'
        1: from /Users/sumeetgujrati/.rvm/gems/ruby-2.7.1/gems/redis-4.2.1/lib/redis/client.rb:127:in `call'
Redis::CommandError (ERR wrong number of arguments for 'hset' command)
```

Output from `irb` when using `redic`:
```
2.7.1 :009 > require "redic"
 => true 
2.7.1 :011 > redis_redic = Redic.new("redis://:pwd@localhost:6379")
2.7.1 :012 > redis_redic.call("HSET", "mykey", "myfield", [])
 => 0 
```

**Comment by byroot** [comment]
Ok, so in your initial issue I understood that you where doing `redis.hset("myhash")`.

I'll look into what's going on here, it is indeed a bug. However please note that you are relying on an implicit `#to_s` here, which isn't a good idea at at (I should really deprecate that).

In the meantime you can easily work around this with `redis.hset("myhash", "mykey", [].to_s)`.

**Comment by sgujrati-up** [comment]
Thanks for looking into it. `[].to_s` is what I am doing as work around.
