### ISSUE TITLE
Stale IP Address after A New Master Gets Elected

### ISSUE THREAD

**Issue by alexgaganashvili** [redis/redis-rb#942]
Hi,

After a new master gets elected, a client still holds on to the old IP address it retrieved during bootstrap. It looks as if the client would not talk to sentinels at runtime. As a result, we're seeing the following errors:
Redis::CannotConnectError: Error connecting to Redis on <old_master_ip_address>:6379 (Errno::ECONNREFUSED)

Thanks,
Alex

**Comment by supercaracal** [comment]
I tried to reproduce the following behavior with this repository.

```
$ make start_all
$ ps x | grep redi[s]
   9324 ?        Ssl    0:10 tmp/cache/redis-6.0/src/redis-server *:6381
   9331 ?        Ssl    0:12 tmp/cache/redis-6.0/src/redis-server *:6382
   9340 ?        Ssl    0:16 tmp/cache/redis-6.0/src/redis-server *:6400 [sentinel]
   9347 ?        Ssl    0:16 tmp/cache/redis-6.0/src/redis-server *:6401 [sentinel]
   9354 ?        Ssl    0:16 tmp/cache/redis-6.0/src/redis-server *:6402 [sentinel]
   9361 ?        Ssl    0:10 tmp/cache/redis-6.0/src/redis-server *:7000 [cluster]
   9363 ?        Ssl    0:10 tmp/cache/redis-6.0/src/redis-server *:7001 [cluster]
   9369 ?        Ssl    0:10 tmp/cache/redis-6.0/src/redis-server *:7002 [cluster]
   9375 ?        Ssl    0:11 tmp/cache/redis-6.0/src/redis-server *:7003 [cluster]
   9385 ?        Ssl    0:11 tmp/cache/redis-6.0/src/redis-server *:7004 [cluster]
   9391 ?        Ssl    0:10 tmp/cache/redis-6.0/src/redis-server *:7005 [cluster]
```

The above three Sentinels are watching the following two nodes.

| Node | Role |
| --- | --- |
| `:6381` | Primary |
| `:6382` | Replica |

```
$ bin/console

irb(main):001:0> r = Redis.new(host: 'master1', sentinels: (6400..6402).map { |port| { host: 'localhost', port: port } })

irb(main):002:0> r.inspect
=> "#<Redis client v4.2.1 for redis://127.0.0.1:6381/0>"

irb(main):003:0> r.debug :sleep, 300
Traceback (most recent call last):
---snip---
Redis::TimeoutError (Connection timed out)

irb(main):004:0> r.inspect
=> "#<Redis client v4.2.1 for redis://127.0.0.1:6382/0>"
```

It seems that the gem is working fine after failover is occurred.

Could you tell me your environment?

1. Gem version
2. Redis version
3. Number of Sentinels

**Comment by alexgaganashvili** [comment]
@supercaracal , I'm running Redis Sentinel in Kubernetes (https://docs.bitnami.com/tutorials/deploy-redis-sentinel-production-cluster/).

**Comment by alexgaganashvili** [comment]
Let's put this on hold for now. I need to confirm how the dev-s initializing redis connection. I don't want you to spend time troubleshooting it in vain. Thanks.

**Comment by supercaracal** [comment]
* https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-master-statefulset.yaml
* https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-slave-statefulset.yaml
* https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/configmap.yaml

It looks like the sidecar pattern. It seems that the pattern is same as the following documentation.

[Example 2: basic setup with three boxes](https://redis.io/topics/sentinel#example-2-basic-setup-with-three-boxes)

1. Is `min-replicas-to-write` parameter greater than number of enabed replicas? (default: 0)
2. Is `NetworkPolicy` manifest correct?

Something might be figure out if you get Sentinel stdout log.
