### ISSUE TITLE
Redis gem not able to create tcp keep alive connections on jruby

### ISSUE THREAD

**Issue by anubhav0712** [redis/redis-rb#947]
I was trying to test the tcp keep alive functionality, using the following script.
```
require 'redis'

option = {
    :url => 'redis://localhost:6380',
    :tcp_keepalive => 60
}
conn = Redis.new(option)
puts "starting psubscribe...."
conn.psubscribe('some:key') do |on|
    on.pmessage do |pattern, channel, msg|
      puts "Do something!"
    end
end
```
And checked the connection information using netstat.

Initially, I ran this script on **jruby 9.2.8.0**. And saw the following output from netstat.
![image](https://user-images.githubusercontent.com/47751987/93733231-39498b80-fbf2-11ea-8162-a941fb8fe3aa.png)

But when I run the same script on **ruby 2.5.1p57** . It worked fine
![image](https://user-images.githubusercontent.com/47751987/93733284-83327180-fbf2-11ea-8629-5a8c43cf7239.png)

Redis gem version is v**3.2.1** . I even tried updating the gem to v**4** but the result is same.
So is there any other configuration i'm missing, that can make tcp_keepalive work for redis_client on jruby?

**Comment by byroot** [comment]
If it doesn't work it's likely because JRuby doesn't provide the necessary constructs: https://github.com/redis/redis-rb/blob/d6626e6ef0c49374a888074652c4c9b2237dc8eb/lib/redis/connection/ruby.rb#L319-L327

Either way this code was removed in 5.0, so closing.
