### ISSUE TITLE
Support non-exception nonblocking I/O

### ISSUE THREAD

**Issue by nateberkopec** [redis/redis-rb#948]
Since Ruby 2.3, nonblocking I/O methods take `exception: false`, so they no longer have to raise exceptions when they would block.

https://github.com/redis/redis-rb/blob/eac9b3526dc0909d3fe3a12728e4aaef73a5a042/lib/redis/connection/ruby.rb#L51

Not raising exceptions and immediately rescuing will increase performance.

Linking: https://github.com/petergoldstein/dalli/issues/756

**Comment by byroot** [comment]
Yeah I meant to use that since a while, I need to finish it: https://github.com/redis/redis-rb/pull/926

**Comment by nateberkopec** [comment]
Cheers! Just noticed it today in production, glad it's already on your radar.

**Comment by byroot** [comment]
Done.
