### ISSUE TITLE
Lua script evaluated twice?

### ISSUE THREAD

**Issue by alanhala** [redis/redis-rb#953]
Hey, I have this Lua script which is basically a get or set returning also if the key was set or not.
```lua
local key = KEYS[1]
local next_value = ARGV[1]
local expire_in = tonumber(ARGV[2] or -1)
local current_value = redis.call("get", key)

if current_value then
  return { false, current_value }
else
  redis.call("set", key, next_value, "EX", expire_in)
  return { true, next_value }
end
```

I have the suspicion that this script is run twice because sometimes the call returns that the value was not set but instead it was fetched. Could it be that the request to redis sometimes timeouts and then there's some retry which ends up returning that the key already existed?

I saw that there's a reconnect_attempts. But I guess that is used for fetching a connection not for retrying commands, right?

**Comment by bpo** [comment]
@alanhala When `reconnect_attempts` is set to a value > 0, commands can be duplicated. See #668 for related discussion.

**Comment by alanhala** [comment]
Thanks for the reply. I'll test if setting that value to 0 fixes the problem and sorry for duplicating the issue if that's the case!
