### ISSUE TITLE
Resolve CNAME when connecting

### ISSUE THREAD

**Issue by sandstrom** [redis/redis-rb#957]
It seems like this client won't resolve CNAME DNS entries when resolving a domain name to an IP-address.

Is this by design or because `Socket.getaddrinfo` won't do it by default?

(happy to elaborate if needed)

**Comment by bpo** [comment]
@sandstrom you may want to elaborate further on what you're seeing. I use this client regularly with CNAMEs, fwiw.

**Comment by sandstrom** [comment]
Thanks @bpo 💯 🎉 

After checking again I've noticed that this was a misunderstanding on my part.
