### ISSUE TITLE
Cannot use zincrby inside multi

### ISSUE THREAD

**Issue by souljuse** [redis/redis-rb#965]
I am trying to use a zincrby inside a multi statement but it gives me an error.

To reproduce:

```ruby
redis.multi
redis.zincrby("foo", 1,  "bar")
redis.exec

```

It gives me this error 

```
ArgumentError: invalid value for Float(): "QUEUED"
from .../redis.rb:3394:in `Float'
```

**Comment by byroot** [comment]
Uh, I'm surprised this would even work, but indeed seems like the interface authorize it.

In the mean time I'd say use the block API:

```ruby
redis.multi do
  redis.zincrby ...
end
```

**Comment by byroot** [comment]
Fixed in https://github.com/redis/redis-rb/commit/086221ec109835b3051b3f122820c370ad758014

**Comment by byroot** [comment]
Actually, I figured since it do work for commands that don't parse the response, removing it might break some people's code. 

So instead I pushed https://github.com/redis/redis-rb/commit/c4be8f49c6d18f1e5ee2d2c8dbf7e4c94fa109ad
