### ISSUE TITLE
overwrite default `redis.new` config?

### ISSUE THREAD

**Issue by Deekor** [redis/redis-rb#970]
Is there a way to overwrite the default behavior of `Redis.new` in a initializer? id like it to pass some default `ssl_params` in, which would allow our devs to continue to use simply `redis.new` and I could change the params based on the current rails env

**Comment by byroot** [comment]
There's plenty of way to do this in Ruby, but the simplest is to prepend a module that redefine `initialize`. 

I don't think `redis-rb` should provide such feature though, because it's used by many libraries, and it's not good to have movable defaults for libraries.
