### ISSUE TITLE
LPOP count support?

### ISSUE THREAD

**Issue by adamgamble** [redis/redis-rb#976]
In the redis documentation, lpop supports a count argument. I can't seem to figure out how to do that with redis-rb.
Am I missing something or does redis-rb not support the count argument?

https://redis.io/commands/lpop

**Comment by supercaracal** [comment]
> &gt;= 6.2: Added the count argument.

I think it is the latter. It seems that the Gem just haven't support it yet.

**Comment by bpo** [comment]
Hi - you can do this today with the `call` command, which supports arbitrary commands so you don't need to wait on any client modifications when using a new command (or using modules, etc):

```ruby
redis.call :lpop, 'mylist'
=> "one"
redis.call :lpop, 'mylist', 2
=> ["two", "three"]
```
