### ISSUE TITLE
[v4.3.0] Redis::CommandError: ERR wrong number of arguments for 'auth' command

### ISSUE THREAD

**Issue by lucascaton** [redis/redis-rb#989]
Hi there,

I just updated to [version 4.3.0](https://github.com/redis/redis-rb/releases/tag/v4.3.0) and Sidekiq fails to start because of something related to `Redis::CommandError`.
Here's the full stack trace:

```
pid=12 tid=gv0 INFO: Booting Sidekiq 6.2.1 with redis options {:url=>"redis://myapp-production:REDACTED@redis-myapp-production:6379"}
pid=12 tid=gv0 WARN: Redis::CommandError: ERR wrong number of arguments for 'auth' command
pid=12 tid=gv0 WARN: /app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:137:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:118:in `block in connect'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:318:in `with_reconnect'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:116:in `connect'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:391:in `ensure_connected'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:243:in `block in process'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:330:in `logging'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:242:in `process'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis/client.rb:136:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis.rb:2194:in `block in hget'
/app/vendor/bundle/ruby/2.7.0/gems/redis-4.3.0/lib/redis.rb:70:in `block in synchronize'
```

**Comment by byroot** [comment]
What is your redis server version?

**Comment by lucascaton** [comment]
@ byroot `Redis 6.2.4 (00000000/0) 64 bit`

**Comment by lucascaton** [comment]
@byroot `Redis 6.2.4 (00000000/0) 64 bit`

**Comment by byroot** [comment]
Hum, weird, I would have expected something older. The bug is likely here: https://github.com/redis/redis-rb/pull/967/files#diff-5bc007010e6c2e0aa70b64d6f87985c20986ee1b2882b63a89b52659ee9c91f8R118

Seems like we always pass 2 args to AUTH, but only Redis 6+ support two arguments, before that it's one max.

cc @supercaracal

**Comment by lucascaton** [comment]
I'm sorry @byroot - the actual version my server is running is `5.0.7`. Isn't that version compatible with this gem?

**Comment by byroot** [comment]
Yeah, that's what I figured after being unable to repro on 6.x. I tried 5.x and I know see the error. I'll try getting a fix ASAP.

**Comment by byroot** [comment]
`4.3.1` is out with the fix.

**Comment by lucascaton** [comment]
Thanks, @byroot - it's working now!
