### ISSUE TITLE
Feature request: Cluster mode: A way to group keys by cluster node

### ISSUE THREAD

**Issue by cbatson** [redis/redis-rb#994]
Given a set of arbitrary keys, presently, there does not appear to be a straightforward way to group keys by cluster node, for use with `mget` for instance.

I humbly request a documented public method which, when given a key as input, returns the node ID associated with that key (taking into account any presence of a hash tag, of course).

This will permit the caller to group arbitrary keys by node, and then issue the needed number of (for instance) `mget` commands to the cluster to retrieve the desired values.

**Comment by supercaracal** [comment]
Redis Gem has a client-side-consistent-hashing feature. It looks like similar feature is implemented. https://github.com/redis/redis-rb/pull/687

The above feature might be useful for cluster mode too. Too many hash tags sometimes occur imbalances of shards.

**Comment by cbatson** [comment]
Thank you @supercaracal. I'm actually going to backpeddle on this request. I misunderstood Redis, but now know it's a limitation that queries involving multiple _slots_ are not permitted. This severely limits the use of multi-key operations like `mget`, and so this feature request is significantly less valuable as a result.

Here's an example:

The keys `aa` and `cc` map to different slots:

```
irb(main):001:0> key1 = 'aa'
=> "aa"
irb(main):002:0> slot1 = Redis::Cluster::KeySlotConverter.convert(key1)
=> 1180
irb(main):005:0> key2 = 'cc'
=> "cc"
irb(main):006:0> slot2 = Redis::Cluster::KeySlotConverter.convert(key2)
=> 700
```

On my test cluster, a single node handles slots 0 through 1605, which includes the above to keys. Yet

```
$ nc xxx.cache.amazonaws.com 6379
MGET aa bb
-CROSSSLOT Keys in request don't hash to the same slot
```

So my dream of grouping keys by node for `mget` is shattered.

I will close this but feel free to re-open if you desire.
