### ISSUE TITLE
I18n redis 4+ integration. Reason of removed methods `[]` `[]=`

### ISSUE THREAD

**Issue by mPanasiewicz** [redis/redis-rb#997]
Dear Contributors,

I have an issue with using redis as a backend store for [I18n](https://github.com/ruby-i18n/i18n) gem. Unfortunately the redis-rb gem above 3 is not working with the I18n because I18n needs methods `[]` `[]=` [comment](https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/key_value.rb#L28-L30). These methods were removed long time ago [git commit](https://github.com/redis/redis-rb/pull/653/commits/c61ad43e10d2f39c717bfcf94f3b65abeb34f877).
My question are:

1. Why did you remove these methods from the library
2. How can I fix it the right way?
3. Is there any chance to revert the commit to return these methods to the library??

My own solution I described [here](https://stackoverflow.com/a/68026970/3193634) but I'm thinking if there is any way to avoid patching the `Redis` library.

Thank you!

**Comment by byroot** [comment]
> 1. Why did you remove these methods from the library

Not sure as it was done by a former maintainer.

> How can I fix it the right way?

```ruby
class RedisHash
  def initialize(redis)
    @redis = redis
  end

  def [](key)
    @redis.get(key)
  end

  def []=(key, value)
    @redis.set(key, value)
  end  
end

I18n::Backend::KeyValue.new(RedisHash.new(your_redis_client))
```

> Is there any chance to revert the commit to return these methods to the library??

No chance at all.

**Comment by mPanasiewicz** [comment]
@byroot Thank you very much for a fast answer. I appreciate that. I will do as you suggest.
Kind Regards!
